### PR TITLE
Fix test and example incompatibility with ARM Macs

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

This includes a few commits from the master branch which fix issues with compiling the examples and tests on Macs, particle Apple Silicon Macs. For the sake of having simple cherry-picks without conflicts I included a commit that reduces the number of times CatchMain.cpp is compiled which is also a nice benefit since that speeds up compile times significantly. 

See #1918, #1898, and #1949 for more discussion about these commits.

## Tasks

* [ ] Tested on Linux
* [ ] Tested on Windows
* [x] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — CHANGES_REQUESTED** [review]
Can't really update Catch on the 2.6.x branch as it requires C++17 and also bumps the CMake version.

**Comment by ChrisThrasher** [comment]
Catch2 v2 uses C++11, not 17 but now I remember that SFML 2.x uses C++03 so it doesn't matter either way. I expected that to have broken the CI pipeline but everything is still passing. Not sure what to make of that.

The latest commit in the Catch2 1.x release series doesn't build for Arm Macs so I suppose the tests will always be broken for Arm Macs. That's too bad. I'll keep the example fix in here since that's still a small compatibility improvement.

**Comment by ChrisThrasher** [comment]
> it requires C++17

Are you referring to this line in test/CMakeLists.txt?

```cmake
target_compile_features(sfml-test-main PRIVATE cxx_std_17)
```

I forgot this was in here but I use Catch2 v2.13.7 in many other C++11 projects without issue. I tried removing that and my local build still works. Either way it's not a huge deal so I'll just keep those commits out of this PR.

**Comment by eXpl0it3r** [comment]
Don't exactly see an easy solution for this either. I want to keep SFML 2.x C++03 compatible, if it means that tests can't be executed on a newer platform, then I find this a better trade off, than requiring all the other platforms to support C++11.

SFML 2.6 will be the last SFML 2.x version (excluding potential bugfix releases), so there shouldn't really be a big issue not having tests executed on macOS ARM

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Pull request merged**
