### PR TITLE
Updated platform-specific handle documentation

### PR DESCRIPTION
**Pull request by mantognini**
This improves the documentation about platform-specific window handle types.

### CODE REVIEW

**Comment by Foaly** [comment]
I'm not an OSX programmer, so I don't know if this is self-explanatory, but maybe you should note what is returned in what case.

**Comment by Bromeon** [comment]
Yup. Maybe the whole case differentiation can be made more readable by using a list, where each item explains one platform.

**Comment by mantognini** [comment]
You're both right, I'll rework on that PR soon.

(Initially I wanted to dedicate a full page of the doxygen documentation to OS specific limitations but actually that would just add links everywhere without making it really visible. And it takes more time to do.)

**Comment by mantognini** [comment]
I was thinking, instead of duplicating this information in multiple place, why not have `sf::WindowHandle` as a symbol in the doc?

If you don't want to generate the doc to see how it looks like, here are the relevant screenshots.

screenshot 2015-09-25 17 44 21

And the detailed documentation:

screenshot 2015-09-25 17 45 32


To do that, we need to trick Doxygen a bit as you can see [here](https://github.com/SFML/SFML/pull/961/files#diff-ba198ceac8f16f658380841e4678c306R2004) and [there](https://github.com/SFML/SFML/pull/961/files#diff-53df55348a509d8fcc3dced5ac6a0c90R65)

So here are my questions:

 - do you like it or would you do it differently?
 - regarding Android, there was a discussion about the handle a few days/weeks ago. Should I update anything there or keep it defined as a `ANativeWindow` in the doc as well?

**Comment by mantognini** [comment]
@SFML/sfml Here's a cute little hamster to attract your attention on this PR. :hamster:

**Comment by Bromeon** [comment]
For code symbols, you should use `\p` or `\c` (typewriter font), not `\a` (italics).

And are you sure that the now enabled markdown support doesn't break other parts of the documentation? Maybe you could run a diff through the generated files...

Concerning `#elif defined(SFML_DOXYGEN)`, that's a nice way of doing it. I solved this problem a bit differently in Aurora, see [Config.hpp](https://github.com/Bromeon/Aurora/blob/master/include/Aurora/Config.hpp#L39) and [doxyfile.txt](https://github.com/Bromeon/Aurora/blob/master/doc/doxyfile.txt#L1558). But your way is perfectly fine if we have so few occurrences. What I would change however is the identifier `"platform-specific"` to something like `"{platform-specific}"`, so it's clear that it's not an actual identifier (it is already because of the dash, but it may not be for future ones).

I could also benefit from `SFML_DOXYGEN` in my shader uniform PR, so that
```cpp
typedef priv::Matrix<4, 4> Mat4;
```
is documented as
```cpp
typedef {implementation-defined} Mat4;
```

**Comment by mantognini** [comment]
> For code symbols, you should use \p or \c (typewriter font), not \a (italics).

Fixed.

> And are you sure that the now enabled markdown support doesn't break other parts of the documentation? 

Actually it fixes a few things. Such as simple `*bold*` to [list](https://github.com/SFML/SFML/blob/master/include/SFML/Graphics/Transformable.hpp#L423-L425) even. Nothing broken to report.

> What I would change however is the identifier "platform-specific" to something like "{platform-specific}"

Yep, I agree but Doxygen doesn't handle this: it simply says:

> WindowHandle.hpp:78: warning: documented symbol `sf::WindowHandle' was not declared or defined.

**Comment by Bromeon** [comment]
> Yep, I agree but Doxygen doesn't handle this: it simply says:

> > WindowHandle.hpp:78: warning: documented symbol `sf::WindowHandle' was not declared or defined.

That's annoying. It does accept `-` within identifiers, but not `{}`... quite arbitrary. Does it work with normal parentheses `(implementation-defined)` or square brackets `[implementation-defined]`?

**Comment by mantognini** [comment]
> Does it work with normal parentheses (platform-specific) or square brackets [platform-specific]?

Nope. :-|

**Comment by Bromeon** [comment]
Too bad.

Little anectode: I had this very problem [more than half a decade ago](http://doxygen.10944.n7.nabble.com/Hide-typedef-initializer-td4395.html). After getting no meaningful answers from the community, I just implemented what I wanted myself and submitted a patch to Dimitri that extends the `\hideinitializer` command to typedefs, which would allow to omit a typedef's referred-type for the sake of hiding implementation details from the API. Unfortunately, the patch has not been integrated the last time I checked... maybe you could check again if `\hideinitializer` works meanwhile.

If somebody were interested in taking another contribution attempt to Doxygen, I'd gladly search for that patch, but at the moment I don't have the time to do it myself.

**Comment by mantognini** [comment]
I couldn't make `\hideinitializer` work with typename.. But I think it's already good as it is; at least for the time being.

What about
> regarding Android, there was a discussion about the handle a few days/weeks ago. Should I update anything there or keep it defined as a ANativeWindow in the doc as well?

?

**Comment by mantognini** [comment]
@MarioLiebisch or @Sonkun ?

**Comment by MarioLiebisch** [comment]
Leave `ANativeWindow` for now, this needs updating, but only once the actual code is updated as well (otherwise it would be wrong and misleading).

**Comment by mantognini** [comment]
Ok, it's updated. Let me know if there's anything else I should change. The screenshots above are up-to-date.

**Comment by Bromeon** [comment]
Minor issues:

* _Ma**x** OS X_
* _either `NSWindow*` or `NSView*` disguised as `void*`_ -- the precedence is not clear, I would add a comma:
  _either `NSWindow*` or `NSView*`**,** disguised as `void*`_
* I would add parentheses to function calls for consistency: _`sf::Window::getNativeHandle()` will return the handle..._

**Comment by mantognini** [comment]
Fixed. ;-)

**Comment by MarioLiebisch** [comment]
Android specific implementation/updates are now in branch [feature/android-handles](https://github.com/SFML/SFML/compare/feature/android-handles).

Haven't created a PR yet as I assume this one should be merged first. Not sure how GitHub reacts to that. :)

Also the example updates still need some work (comments + better variable names; possibly moving the code in its own inline/include file as well).

**Comment by mantognini** [comment]
Before this gets too cold, has anyone any additional suggestion/comment?

**Comment by Bromeon** [comment]
I'd say it looks good :)

:+1:

**Comment by MarioLiebisch** [comment]
Change of plan, scrap the Android changes I've described above. Android just returns `ANativeWindow`. Leave it like that. I'll have to expose the activity in a different way (since you might need it isolated from a window instance).

**Comment by eXpl0it3r** [comment]
@MarioLiebisch So the current changes are okay?

**Comment by binary1248** [comment]
Checks in with me. :+1:

**Comment by MarioLiebisch** [comment]
@eXpl0it3r Almost, actually it returns an `ANativeWindow*` I think.

**Comment by mantognini** [comment]
Let me know when you're sure and I'll update it. ;)

**Comment by MarioLiebisch** [comment]
It does, since `ANativeWindow`is a `struct`.

**Comment by eXpl0it3r** [comment]
Try to be a bit more specific with your comments. How should we know what exactly you mean with "It does"? It does be a pointer? It does be a value? It does need to change? :wink:

**Comment by eXpl0it3r** [comment]
So is this ready?

**Comment by mantognini** [comment]
I don't know; awaiting for @MarioLiebisch to give a more precise answer.

**Comment by MarioLiebisch** [comment]
`ANativeActivity` is a struct, the function returns a pointer, i.e. `ANativeActivity*`.

**Comment by mantognini** [comment]
I didn't update the screenshot above but now it should be alright for Android too. =]

**Comment by mantognini** [comment]
Rebased and ready for merge.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Just a quick screenshot before I merge it:

WindowHandle

**Pull request merged**
