### PR TITLE
Fix improper cast inside packet operator

### PR DESCRIPTION
**Pull request by szymonj99**
* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [x] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

Very tiny PR to fix a cast issue for one of the Packet operators.

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

Before the following code would return output as being 0.
Now it returns the correct value.

```cpp
sf::Packet newPacket;
sf::Int32 input = 1234;
sf::Int32 output;
newPacket << input;
newPacket >> output;
std::cout <<  "input: " << input << " output: " << output << "\n";
```

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Regression from: 0468612ac0bbd3095b160b8a23ba5346d8705095

**Review by eXpl0it3r — CHANGES_REQUESTED** [review]
Could you rebase on `2.6.x` and change the base branch to `2.6.x` for the PR?

**Comment by vittorioromeo** [comment]
Could we add a unit test for this? Would be nice to catch these issues automatically.

**Comment by szymonj99** [comment]
> Could we add a unit test for this? Would be nice to catch these issues automatically.

Sure, would be nice.
I'm not able to do it however. I have limited time available meaning others would have to write and maintain the tests.

I'll rebase and push the change in a bit.

**Comment by reconndev** [comment]
> Could we add a unit test for this? Would be nice to catch these issues automatically.

Good suggestion. In fact, I did write a unit test just for that and the code breaks because this change is insufficient. There a duplicate mistake at `src/SFML/Network/Packet.cpp:181` which requires fixing as well.

I created a separate PR with fix and unit tests here: #1871 rebased onto 2.6.x as well.

**Comment by vittorioromeo** [comment]
I am closing this in favour of #1871, which includes the fix provided here plus another one and a unit test. Thanks everyone!

**Pull request closed without merging**
