### PR TITLE
Add tests for `SFML_USE_SYSTEM_DEPS` option

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

I just realized we have no tests for the `SFML_USE_SYSTEM_DEPS` option so I added this special case CI job.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Review by binary1248 — APPROVED** [review]

**Review by eXpl0it3r — APPROVED** [review]
Not sure how useful this is to run on Linux, as we're always using system dependencies on Linux to begin with. 🤔

**Comment by ChrisThrasher** [comment]
I'm now realizing that the Linux builds use system deps irrespective of the value of `SFML_USE_SYSTEM_DEPS`. That's a good point. This job is pretty useless as-is. I'll see about using macOS instead so that we're actually testing something meaningful.

**Comment by ChrisThrasher** [comment]
I switched over to using macOS and it still automatically works without having to install anything extra.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Pull request merged**
