### PR TITLE
Fixed sf::Keyboard::RAlt events

### PR DESCRIPTION
**Pull request by binary1248**
Fixed sf::Keyboard::RAlt events not being triggered by keyboards on which the right Alt key functions as a level 3 shift.

http://en.sfml-dev.org/forums/index.php?topic=18433.0

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Can anyone else confirm that this fixes the bug? @TankOs

**Comment by binary1248** [comment]
This PR is outdated, will rebase onto Xlib events once that is done.

**Comment by TankOs** [comment]
I'm curious -- the changes look weird at least. :P

**Comment by binary1248** [comment]
I really only changed 1 line. The changes GitHub shows are from another commit that has already been merged and whitespace changes to adjust alignment.

**Comment by TankOs** [comment]
Alright, that explains my confusion.

**Comment by binary1248** [comment]
Closing this.

Users who want to use their right Alt or AltGr key on keyboards/layouts where it functions as such will have to tell X themselves that it should function as an Alt as well. The default behaviour when this is not the case is for the key to not function as an Alt in any application present on the system. In order to stay consistent with other applications, SFML should not map ISO_Level3_Shift to RAlt either. It is up to the user to adjust this behaviour themselves if they want to.

**Pull request closed without merging**
