### PR TITLE
Provide an option to specify the number of parallel jobs clang-tidy should be run with

### PR DESCRIPTION
**Pull request by binary1248**
Title.

This would allow me to get rid of the patching step necessary to limit CPU usage when running CI using Buildbot.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Why does the build bot rub clang-tidy?

**Comment by binary1248** [comment]
It always ran clang-tidy as part of its static analysis run, even before we started using GitHub Actions. After clang-tidy support was added to our CMake configuration buildbot would just use that instead of manually invoking clang-tidy like it originally did.

**Comment by ChrisThrasher** [comment]
I think the Buildbot ought to stop running clang-tidy. Is it analyzing any codepaths that aren't already analyzed by our 6 clang-tidy jobs in GitHub Actions?

**Comment by binary1248** [comment]
I would also have preferred to cut down on buildbot jobs, but @eXpl0it3r prefers that we keep everything redundant just in case.

**Comment by ChrisThrasher** [comment]
Running clang-tidy is not hard. Should we ever somehow lose our GitHub Actions CI pipeline it is very easy to add it to our Buildbot pipeline. There is no need to be continuously running clang-tidy while we wait on GitHub to cut us off.

**Comment by binary1248** [comment]
Disabled running clang-tidy on Buildbot for now.

**Pull request closed without merging**
