### PR TITLE
Change Vector2 and Vector3 length function

### PR DESCRIPTION
**Pull request by LDprg**
* [x] Has this change been discussed on [Github](https://github.com/SFML/SFML/issues/2190) before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [x] If you have additional steps which need to be performed list them as tasks!

----

## Description

Replacing hypot because of bad performance.

Perfomance with hypot:
grafik

Performance with a normal sqrt instead
grafik

GLM and EIgen only for comparison reasons

As you can see using a normal sqrt speeds up the length function by a factor of ~10.

This PR is related to the issue #2190

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

Testet with the benchmark code. 

Test and Benchmark code:
[main.zip](https://github.com/SFML/SFML/files/9494334/main.zip)!

Obviously the change is platform independent.

### CODE REVIEW

**Comment by Bromeon** [comment]
This is a crazy result!

An explanation can be found on StackOverflow: https://stackoverflow.com/questions/3764978/why-hypot-function-is-so-slow

Feedback for the code:
* formatting currently doesn't pass (there should be space between operands, and no space on empty lines)
* maybe add a comment that `std::hypot` is too slow, just to avoid regressions in the future

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by LDhtl** [comment]
From my side this is finsihed couldn't find any other uses of hypot, which should be replaced.

**Review by Bromeon — APPROVED** [review]

**Review by vittorioromeo — APPROVED** [review]
LGTM, thank you for the contributions and the benchmarks. @LDprg: the next step to speed this up even further is replace `std::sqrt` with the `fastInverseSqrt` that other libraries use -- I would be happy to see a PR for that.

**Comment by Bromeon** [comment]
@LDhtl and @LDprg the same person? 🙂 

Thanks a lot for spotting and improving this performance bottleneck!

**Comment by Marioalexsan** [comment]
> LGTM, thank you for the contributions and the benchmarks. @LDprg: the next step to speed this up even further is replace `std::sqrt` with the `fastInverseSqrt` that other libraries use -- I would be happy to see a PR for that.

Fast inverse square root does not have perfect accuracy unlike `std::sqrt`, so I'm not sure if this is a straightforward replacement.

**Comment by LDprg** [comment]
Well there are different ways of doing a fast inverse sqrt, with different accuracy and performance. But it seems like they are all working only with float type (so no double precision possible). Maybe it's the best to add a separate function like fastlength().

**Comment by vittorioromeo** [comment]
Some more interesting reading here:
https://stackoverflow.com/questions/71608126/is-it-still-worth-using-the-quake-fast-inverse-square-root-algorithm-nowadays-on

**Pull request merged**
