### PR TITLE
Update OpenAL-soft for OS X to version 1.17.2

### LINKED ISSUE #900: The OpenAL-Soft version shipped with SFML is buggy
As stated in this [thread](http://en.sfml-dev.org/forums/index.php?topic=18245.msg131282#msg131282), commit ce16554763177d7285248e81e9b0e0201f0c43e3, introduced to fix OpenAL thread safety (#541 & #831), actually breaks other parts of the audio module.

I won't be able to solve this before 2.3.1 so I'm wondering if you should temporarily revert this commit and propose a properly fixed version in 2.3.2 (for example). Thoughts?

### SSCCE

```cpp
#include <SFML/Audio.hpp>

using namespace sf;

int main(int argc, char const** argv)
{
    if (!SoundBufferRecorder::isAvailable()) {
        return EXIT_FAILURE;
    }

    sf::SoundBufferRecorder recorder;

    recorder.start();

    recorder.stop();

    return EXIT_SUCCESS;
}

```

### Trace

```
0   libsystem_c.dylib               0x00007fff91c7c152 strlen + 18
1   org.sfml-dev.OpenAL             0x0000000101da3a8c al_string_copy_cstr + 28
2   org.sfml-dev.OpenAL             0x0000000101db21b3 ca_open_capture + 2115
3   org.sfml-dev.OpenAL             0x0000000101d9451b alcCaptureOpenDevice + 587
4   libsfml-audio.2.3.dylib         0x0000000101d3ac98 sf::SoundRecorder::start(unsigned int) + 296
5   sound-capture                   0x0000000101d2c894 main + 228
6   libdyld.dylib                   0x00007fff917c95c9 start + 1
```

### PR DESCRIPTION
**Pull request by mantognini**
This PR attempts to fix #900 and #1000.

The first one seems to run fine on my machine. However, since I haven't yet upgraded my computer to 10.11, I can't test the second one. In any case, third party testing would be nice.

Note: it is known that OpenAL-soft might emit a warning regarding SSE on OS X 10.11 such as this one:

> AL lib: (WW) UpdateDeviceParams: SSE performs best with multiple of 4 update sizes (1114)

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
So is this good to go? Can any other OS X user test this?

**Comment by mantognini** [comment]
It was only partially tested. Regarding #1000, @willm127 did test this [10 days ago](http://en.sfml-dev.org/forums/index.php?topic=19305.msg142242#msg142242). Apart from a warning (kcat/openal-soft#32), it seemed fine.

But it remains to test whether #900 is fixed or not...

**Comment by mantognini** [comment]
Due to the lack of testers on OS X, I move this PR to `accepted` and ready to be merged.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by Foaly** [comment]
Wouldn't it be a good idea to update all OpenAL libraries to 1.17.2, not just on OSX? Looking through the changlog there are a few interessting things that everybody could benefit from. Mainly bugfixes (like UTF8 fixes for windows) or performance improvments using SSE extensions. There were also a whole range of effects added (Chorus, Flanger, Distortion, Equalizer, and Compressor) which could be interessting.

**Comment by mantognini** [comment]
I'm not against it, but through a different PR.

**Pull request merged**
