### PR TITLE
Update Image.cpp

### PR DESCRIPTION
**Pull request by shadowmouse791**
Added asserts into getPixel and setPixel to check validity of coordinates.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
As discussed on the forum, the `#ifdef` are not needed.
Additionally there should be a space after the `//` comment slashes and you should squash the commit into one.

**Comment by Bromeon** [comment]
And the conditions separated by && should be in parentheses, see [here](http://www.sfml-dev.org/style.php#parenthesis-braces). The check whether x and y are bigger or equal to zero is pointless, as they're unsigned integers.

And as mentioned on the forum, we don't add any security with this assertion, because `std::vector::operator[]` already checks indices in every decent implementation.

**Comment by shadowmouse791** [comment]
Not sure how to combine the commits, should I just make a new pull request with the corrected code?

**Comment by shadowmouse791** [comment]
Oh, I've screwed this up trying to combine commits and putting the pull request on my own fork. I'll try again tomorrow, it's late and I've got a couple of exams tomorrow.

**Comment by Bromeon** [comment]
Take your time, there's no need to hurry! And good luck with the exams :grinning:

**Comment by shadowmouse791** [comment]
Thanks. English lit tomorrow. Why couldn't I have specialised in programming when I learnt it (year 6)?

**Comment by eXpl0it3r** [comment]
Given [the discussion](http://en.sfml-dev.org/forums/index.php?topic=18170.0) I'm closing this PR for now, but feel free to update and re-open it if the discussion ends up going in favor of it.

**Pull request closed without merging**
