### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by root-k1d**
## Tasks

* [ ] Tested on Linux
* [X] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

### Preamble

Maybe use: 
```cpp
namespace sf::priv 
{ 

} // namespace sf::priv
```
instead of:  
```cpp
namespace sf 
{ 
namespace priv 
{ 

} // namespace priv

} // namespace sf
```

### Before:
```cpp
namespace sf
{
namespace priv
{
    ////////////////////////////////////////////////////////////
    void foo();

} // namespace priv


} // namespace sf
```

### After:
```cpp
namespace sf::priv
{
    ////////////////////////////////////////////////////////////
    void foo();

} // namespace sf::priv
```

### Before:
```cpp
namespace sf
{
namespace priv
{
    ////////////////////////////////////////////////////////////
    void foo();

} // namespace priv
    ////////////////////////////////////////////////////////////
    void bar();

} // namespace sf
```

### After:
```cpp
namespace sf::priv
{
    ////////////////////////////////////////////////////////////
    void foo();

} // namespace sf::priv

namespace sf
{
    ////////////////////////////////////////////////////////////
    void bar();

} // namespace sf
```

### Before:

```cpp
// *.hpp
namespace sf
{
    namespace priv
    {
        ////////////////////////////////////////////////////////////
        template<typename T>
        void bar(T);

    } // namespace priv

    ////////////////////////////////////////////////////////////
    template<typename T>
    void foo(T);

    #include <*.inl>

} // namespace sf


// *.inl
////////////////////////////////////////////////////////////
template<typename T>
void foo(T)
{
}

namespace priv
{
    ////////////////////////////////////////////////////////////
    template<typename T>
    void bar(T);

} // namespace priv

```

### After:

```cpp
// *.hpp
namespace sf
{
    ////////////////////////////////////////////////////////////
    template<typename T>
    void foo(T);

} // namespace sf

#include <*.inl>

// *.inl

namespace sf
{
////////////////////////////////////////////////////////////
template<typename T>
void foo(T)
{

} // namespace sf

} // namespace sf

namespace sf::priv
{
    ////////////////////////////////////////////////////////////
    template<typename T>
    void foo(T)
    {
    }

} // namespace sf::priv

```

### Before:
```cpp
// *.cpp

namespace sf
{
    ////////////////////////////////////////////////////////////
    void foo()
    {
       
    }

} // namespace sf
```

### In some place:

```cpp
// *.cpp

namespace sf
{

    ////////////////////////////////////////////////////////////
    void foo()
    {
       
    }

} // namespace sf
```

### After:
```cpp
// *.cpp

namespace sf
{
    ////////////////////////////////////////////////////////////
    void foo()
    {
        
    }

} // namespace sf
```

### Before:
```cpp
// *.cpp

namespace sf
{
    ////////////////////////////////////////////////////////////
    void foo()
    {
        
    }
} // namespace sf
```

### After:
```cpp
// *.cpp

namespace sf
{
    ////////////////////////////////////////////////////////////
    void foo()
    {
        
    }

} // namespace sf
```

### Before:
```cpp
// *.cpp

namespace 
{

} // namespace


namespace sf
{
    
} // namespace sf
```

### In some place:

```cpp
// *.cpp

namespace 
{

} // namespace

namespace sf
{
    
} // namespace sf
```
### After:
```cpp
// *.cpp

namespace 
{

} // namespace

namespace sf
{
    
} // namespace sf
```

### Before:
```cpp
// *.cpp

namespace 
{
    ////////////////////////////////////////////////////////////
    void foo()
    {

    }
} // namespace
```

### In some place:

```cpp
// *.cpp

namespace 
{
    ////////////////////////////////////////////////////////////
    void foo()
    {
        
    }

} // namespace
```

### After:
```cpp
// *.cpp

namespace 
{
    ////////////////////////////////////////////////////////////
    void foo()
    {
        
    }

} // namespace
```

### Before: 
```cpp
// Some.hpp
#ifndef SFML_SOME_HPP
#define SFML_FONT_HPP

////////////////////////////////////////////////////////////
/// \brief 
///
////////////////////////////////////////////////////////////
class Some
{

};

#endif // SFML_SOME_HPP
```

### In some place:

```cpp
// Some.hpp
#ifndef SFML_SOME_HPP
#define SFML_FONT_HPP

////////////////////////////////////////////////////////////
/// \brief 
///
////////////////////////////////////////////////////////////
class Some
{

};


#endif // SFML_SOME_HPP
```

```cpp
// Some.hpp
#ifndef SFML_SOME_HPP
#define SFML_FONT_HPP


////////////////////////////////////////////////////////////
/// \brief 
///
////////////////////////////////////////////////////////////
class Some
{

};

#endif // SFML_SOME_HPP
```

### After:

```cpp
// Some.hpp
#ifndef SFML_SOME_HPP
#define SFML_FONT_HPP


////////////////////////////////////////////////////////////
/// \brief 
///
////////////////////////////////////////////////////////////
class Some
{

};


#endif // SFML_SOME_HPP
```

and etc...

### Comment
i formatted only windows files. I can format all if it`s need.

### CODE REVIEW

**Comment by Bambo-Borris** [comment]
Did you use clang-format for this change?

**Comment by root-k1d** [comment]
> Did you use clang-format for this change?

No, it`s handmade format, in some place people forget add new line and etc

**Comment by Bambo-Borris** [comment]
> > Did you use clang-format for this change?
> 
> No, it`s handmade format, in some place people forget add new or add 2 line instead of 1 line and etc

There was recently a large formatting related PR that radically updated all of the SFML C++ source code. I would argue your change is probably unnecessary since the rules that we want to follow were codified and added during the merge of that PR.

**Comment by Bromeon** [comment]
Moving `sf` into the `.inl` file and combining `sf::priv` probably makes sense. But instead of a nested `namespace Literals` inside `sf`, you would close `sf` and then open a new `namespace sf::Literals {` again -- why?

Can the empty lines not be hardcoded via ClangFormat config? This is the kind of change that is purely opinion-based and has a lot of bikeshedding potential 😉

**Comment by root-k1d** [comment]
> Moving `sf` into the `.inl` file and combining `sf::priv` probably makes sense. But instead of a nested `namespace Literals` inside `sf`, you would close `sf` and then open a new `namespace sf::Literals {` again -- why?
> 
> Can the empty lines not be hardcoded via ClangFormat config? This is the kind of change that is purely opinion-based and has a lot of bikeshedding potential 😉

For uniformity

### 1

```cpp
namespace sf
{
namespace priv
{

} // namespace priv

namespace Literals
{

} // namespace Literals

} // namespace sf
```

### 2

```cpp
namespace sf::priv
{

} // namespace sf::priv

namespace sf
{

} // namespace sf

namespace sf::Literals
{

} // namespace sf::Literals

```

I find it easier to read the code I provided in the second example. He better divides the areas of responsibility

**Comment by ChrisThrasher** [comment]
> Can the empty lines not be hardcoded via ClangFormat config?

@Bromeon Via `MaxEmptyLinesToKeep` we can enforce how many consecutive empty lines are allowed which is currently set to 2. However, I don't believe there is any way to enforce any of the ideas outlined in this PR.

> > Moving `sf` into the `.inl` file and combining `sf::priv` probably makes sense. But instead of a nested `namespace Literals` inside `sf`, you would close `sf` and then open a new `namespace sf::Literals {` again -- why?
> > Can the empty lines not be hardcoded via ClangFormat config? This is the kind of change that is purely opinion-based and has a lot of bikeshedding potential 😉
> 
> For uniformity

@root-k1d I'd prefer we not do this. I think the status quo is better where we don't open `namespace sf` more than once per file. Besides, it will take a huge amount of effort to review such a broad-sweeping change which cannot be enforced by any tools.

**Comment by Bromeon** [comment]
Why close this? I think there was value to some parts of this PR, like adding namespace around `.inl` files.

But I'm happy to hear the opinion of other team members, @eXpl0it3r @vittorioromeo? 🙂

**Comment by vittorioromeo** [comment]
I like nested namespaces, and I'd rather see option (2) specified [here](https://github.com/root-k1d) compared to option (1). 

I'm also in favour of closing namespaces before an `#include` of an `.inl` file, and re-opening them in the `.inl` files. It makes the `.inl` files more self-contained. 

Regardless, all of these changes should have separate PRs.

**Comment by eXpl0it3r** [comment]
I don't have any strong feelings for any of the formatting.

I don't really see the goal of having `*.inl` files be more self-contained, as they really shouldn't be used in any other way, than the way they are currently used. Rather I'd be happy for them to throw a lot of compiler errors, if someone would try to include it.

Additionally, I feel like if we add new stylings, it should be mandatory to encode it with clang-tidy, otherwise we risk the styling not being adhered to. Actually quite surprised that our CI didn't complain about any of the changes.

**Pull request closed without merging**
