### PR TITLE
update Info.plist file for Issue #1020

### PR DESCRIPTION
**Pull request by kipbits**

### CODE REVIEW

**Comment by Bromeon** [comment]
What the hell? One PR is enough for one feature/bugfix. And even then, the very least is to read the [Contribution Guidelines](http://www.sfml-dev.org/contribute.php) and provide a description. 

I'll close all the others, please discuss only here.

**Comment by eXpl0it3r** [comment]
What exactly do these changes do?

**Comment by mantognini** [comment]
It's related to #1020. But see my comment: https://github.com/SFML/SFML/issues/1020#issuecomment-167429583.

**Comment by kipbits** [comment]
Sorry, I this is related to my [forum post](http://en.sfml-dev.org/forums/index.php?topic=19498.msg140542#msg140542) on submitting to Mac AppStore. All external libs used in a project need to have these lines added to there .plist for them to pass a validation phase on submit. 

Sorry for the confusion

**Comment by Bromeon** [comment]
Alright, seems like 7 pull requests weren't enough...

Discussion continues in https://github.com/SFML/SFML/pull/1033.

**Pull request closed without merging**
