### PR TITLE
Add static PCH CI jobs for Windows/Linux

### PR DESCRIPTION
**Pull request by vittorioromeo**
I don't know what I'm doing, but let's see if it works...

### CODE REVIEW

**Comment by vittorioromeo** [comment]
It doesn't seem that the CI for this PR picked up the new jobs I added. How am I supposed to test this before merging the PR? @eXpl0it3r @ChrisThrasher @binary1248 let me know if you have any idea :)

**Comment by ChrisThrasher** [comment]
You can test new CI jobs in your own fork. I’ve done it a lot in the past.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by vittorioromeo** [comment]
> You can test new CI jobs in your own fork. I’ve done it a lot in the past.

Turns out it actually does work here, I just screwed up the YAML syntax a bit but got no diagnostics about that.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by vittorioromeo** [comment]
The output seems good, I can see the PCH file being used in every job I added.

**Review by eXpl0it3r — APPROVED** [review]

**Pull request merged**
