### PR TITLE
Clipboard Support

### PR DESCRIPTION
**Pull request by Mischa-Alff**
Please don't merge this yet. As of writing this, this PR is for review purposes.

I've added clipboard support to SFML for Windows and Linux (X11). Still working on Android.
This PR also adds a clipboard example (which is primarily for testing, but also serves as a viable example for the usage of the clipboard API).

The API is simple. The user sees it as: `sf::String sf::Window::getClipboard()` and `void sf::Window::setClipboard(const sf::String&)`.

Clipboard support is really important. All of SFML's competitors have it built-in, and using 3rd-party software for it often is buggy or doesn't work. I've added clipboard support because it's not only essential to game development (copy & pasting links to chat or IPs to the server browser, or copying level codes to the clipboard in case you're going for a Gameboy style), but it's also essential to general application development.

For now the API only supports text. Image support is more complicated and not as much of a necessity as text support is.

The X11 implementation is fully ICCCM compliant.

I tried my best to make the code coherent and to comment everything. It was my first time working with X11 (and thus Xproto and xcb), so there may be some issues with it.

This PR uses the XCB patch.

### CODE REVIEW

**Comment by mantognini** [comment]
This PR cannot be merged as is. Also I don't remember if the implementation needs only small changes or complete rewrite... maybe we should close it for now?

**Comment by Mischa-Alff** [comment]
I can rewrite it and/or fix any issues with it if someone comes up with a viable API.

**Comment by Quintus** [comment]
I haven’t followed the entire discussion around X11 clipboard support in SFML, but I want to point out a little detail that seems to not have been mentioned. While it is true that under "normal" circumstances the clipboard contents vanish if you close the window owning the clipboard, there’s a way around that. All major Linux desktop environments ship with a special "clipboard manager" daemon you can interact with using the `CLIPBOARD_MANAGER` X11 atom; and if you’re not using a larger desktop environment, you should be aware that your nonworking (vanishing) clipboard results from the clipboard manager missing (and install one yourself). If you tell the clipboard manager to take over the clipboard, it will obtain ownership of `CLIPBOARD` and release your burden of maintaining the ownership of it.

We all love X11’s API, do we?

Valete,
Quintus

**Comment by Mischa-Alff** [comment]
This isn't a viable solution. "All your users must have a 3rd party,
non-build-requirement piece of software installed that you don't know about
and your software will mostly run fine without it until it doesn't" will
not work

On Sun, Jan 10, 2016 at 11:30 PM, Marvin Gülker <notifications@github.com>
wrote:

> I haven’t followed the entire discussion around X11 clipboard support in
> SFML, but I want to point out a little detail that seems to not have been
> mentioned. While it is true that under "normal" circumstances the clipboard
> contents vanish if you close the window owning the clipboard, there’s a way
> around that. All major Linux desktop environments ship with a special
> "clipboard manager" daemon you can interact with using the
> CLIPBOARD_MANAGER X11 atom; and if you’re not using a larger desktop
> environment, you should be aware that your nonworking (vanishing) clipboard
> results from the clipboard manager missing (and install one yourself). If
> you tell the clipboard manager to take over the clipboard, it will obtain
> ownership of CLIPBOARD and release your burden of maintaining the
> ownership of it.
>
> We all love X11’s API, do we?
>
> Valete,
> Quintus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SFML/SFML/pull/715#issuecomment-170399915>.
>



-- 
Mischa Alff
Game Jammer, Game Developer, and Physics Technologies Enthuisiast
Web Developer
Destrock: http://destrock.com
GitHub: http://github.com/Mischa-Alff
Twitter: http://twitter.com/MisterAster

**Comment by mantognini** [comment]
Superseded by #1204.

**Pull request closed without merging**
