### PR TITLE
Removed unnecessary sf:: prefixes

### PR DESCRIPTION
**Pull request by Bromeon**
Just code style. There might be a few more `sf::` occurrences within the `sf`namespace, but I wasn't sure how to exclude all uses in comments with a regex. Does anybody have a good idea? :grimacing:

### CODE REVIEW

**Comment by LaurentGomila** [comment]
:+1:

**Comment by TankOs** [comment]
:+1: :cat2:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged into 2.3.x soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
@Bromeon can you rebase this?

**Pull request merged**
