### PR TITLE
Added Cmake flag to enable/disable building certain audio features

### PR DESCRIPTION
**Pull request by samizzo**
As discussed here http://en.sfml-dev.org/forums/index.php?topic=20340.msg146308 this change adds a Cmake flag to allow enabling or disabling the building of certain audio features (flac, vorbis encoding).

### CODE REVIEW

**Comment by LaurentGomila** [comment]
I don't know if this will be accepted, but here are my comments.

I don't think it make sense to partially disable a format (writer only), especially since the other is completely disabled (reader + writer) by the corresponding option. It seems like you did exactly what was needed in *your* specific environment.

No need to add preprocessor instructions to skip the files when they are already excluded from the CMake project. We'd better make sure that they are properly excluded everywhere they are referenced (install rules, #include, ...).

The options could also be named more consistently (compared to other build options too).

**Comment by samizzo** [comment]
True I did what I needed, but surely in a large percentage of cases where someone is using SFML for a game they don't need audio encoding or writing?

For the option names would names like `SFML_FLAC` be more appropriate rather than `SFML_ENABLE_FLAC`?

You're right, we don't need to preprocessor macros; that was a mistake I should have removed before issuing the pull request.

Thanks for taking a look!

**Comment by LaurentGomila** [comment]
> True I did what I needed, but surely in a large percentage of cases where someone is using SFML for a game they don't need audio encoding or writing?

People will most likely want to exclude specific *dependencies*, not features. There's no reason to exclude functionality just because you don't need it (SFML doesn't run on tiny environments where size matters), the only reason I see for this whole thing is to avoid dependencies that you don't use.

> For the option names would names like SFML_FLAC be more appropriate rather than SFML_ENABLE_FLAC?

`SFML_ENABLE_` could be a good enough prefix for all optional features. The module variables are named `SFML_BUILD_XXX` but I don't think we can find a common prefix for both set of options. So I'm fine with this naming, as loing as the suffix is consistent too (ie. FLAC vs VORBIS_ENCODING ;).

**Comment by samizzo** [comment]
> People will most likely want to exclude specific dependencies, not features. There's no reason to exclude functionality just because you don't need it (SFML doesn't run on tiny environments where size matters), the only reason I see for this whole thing is to avoid dependencies that you don't use.

Yeah but excluding specific dependencies means excluding some features. In the case of FLAC if I want to exclude that dependency then I have to disable the feature.

> SFML_ENABLE_ could be a good enough prefix for all optional features. The module variables are named SFML_BUILD_XXX but I don't think we can find a common prefix for both set of options. So I'm fine with this naming, as long as the suffix is consistent too (ie. FLAC vs VORBIS_ENCODING ;).

In this case the FLAC flag is disabling the entire FLAC dependency and feature, and the VORBIS_ENCODING flag is disabling just the Vorbis encoding because Vorbis encoding requires a separate library. How do you suggest handling this?

**Comment by LaurentGomila** [comment]
> Yeah but excluding specific dependencies means excluding some features. In the case of FLAC if I want to exclude that dependency then I have to disable the feature.

If it wasn't clear, what I meant is that you should have SFML_ENABLE_VORBIS that get rids of all the vorbis dependencies, not SFML_ENABLE_VORBIS_ENCODER which leaves the vorbis decoder in.

> In this case the FLAC flag is disabling the entire FLAC dependency and feature, and the VORBIS_ENCODING flag is disabling just the Vorbis encoding because Vorbis encoding requires a separate library. How do you suggest handling this?

Why would you want to get rid of only one of the vorbis libraries? I don't think we have to implement such a fined-grained control.

**Comment by samizzo** [comment]
> Why would you want to get rid of only one of the vorbis libraries? I don't think we have to implement such a fined-grained control.

Because one might want to play audio but not encode audio.. which is what my use case is.

**Comment by LaurentGomila** [comment]
> Because one might want to play audio but not encode audio.. which is what my use case is.

Alright but in terms of dependencies (and matching packages to install), is it really a problem? My point is: do we really need to be able to disable every single bit of dependencies, or can't grouping them by format be a reasonable compromise?

**Comment by samizzo** [comment]
Maybe I'm missing something so I'll just describe exactly what I wanted to do. I wanted to disable two dependencies that I didn't need: the FLAC library (because I don't need FLAC support), and the Vorbis encoder library (because I don't need Vorbis encoding support). Those two things were extra libraries that were being linked in and I didn't want that. I still want to keep the ability to *play* Vorbis audio though.

So that's why my PR is as it is. If there's another way to accomplish that I'm happy to try it!

**Comment by LaurentGomila** [comment]
I perfectly understand what you need.

What I'm asking is, do we really need to implement exactly what you need, or can't we find a better compromise that would involve less specific options. More specifically, would `SFML_ENABLE_VORBIS` (ie. either get *all* the vorbis libs or none) be acceptable, even if it means eventually getting one library that you're not going to use (the encoder). Or is it really important to be able to disable every single library one by one, which gives more control but adds more (and less consistent) build options.

**Comment by samizzo** [comment]
I feel that it is important to be able to disable the libraries that I don't want to link against.

**Comment by MarioLiebisch** [comment]
> Or is it really important to be able to disable every single library one by one, which gives more control but adds more (and less consistent) build options.

I think at least in the case of FLAC it's somewhat reasonable. I don't think it's that commonly used. And depending on what you're trying to build it for, it can be a real PITA (at least last time I tried), because it wasn't using CMake (I think autotool, but not sure right now).

**Comment by aggsol** [comment]
So? What is the verdict? Might this be interesting with https://github.com/SFML/SFML/issues/1232 in mind? Having flags for certain reducing dependencies regarding mp3 or ogg is the better usecase.

**Comment by mantognini** [comment]
I personally don't think we need such on/off switch for dependencies. We already have modules for a high level categorisation, but either you use the audio module with its features, or you don't.

I have this opinion because, when you're looking for a tool, it becomes really complex to know what dependencies are really needed if you're not familiar with what the tool does implementation-wise. Take Debian and its APT package manager: some tools *suggest* other dependencies. What do you make of them? Do you need to install them or not to get the full set of features the tool provides?

If we were targeting embedded systems, sure, we should be especially careful not to drag extra dependencies the user does need. But SFML targets systems big enough not to care about that. I'm pretty sure that a decent game based on SFML has image/sound ressources that dwarf the size of its binary dependencies.

Another argument against such "modularity" is maintenance costs. There are already plenty of cake options. Adding more would make things only harder to update consistently.

**Comment by eXpl0it3r** [comment]
This PR is outdated and I believe there's a general discussion to be had first. If anyone wants to pick up the discussion, start a thread on the forum and I'll gladly move it to the development section. 🙂

**Pull request closed without merging**
