### PR TITLE
Added a project template for Android

### PR DESCRIPTION
**Pull request by MarioLiebisch**
This is just a barebone project that can be used as a starting point for Android ports as well as the creation of new projects from scratch.

The included readme file lists all necessary steps to customize the template and get someone interested started.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
There's been no decision on the issue, as such there should also be no milestone assign.

**Comment by mantognini** [comment]
@ Android users: what's the status of this PR?

**Comment by Bromeon** [comment]
Another half year passed, is this PR still relevant and up-to-date?

**Comment by mantognini** [comment]
This got really old and didn't attract much attention. I'm closing it now, but feel free to reopen if you want to improve on it/maintain it/... ;-)

**Pull request closed without merging**
