### PR TITLE
Use `struct` when all type members are public

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

This follows an existing precedent where any type that exclusively contains `public` functions and data is marked as a `struct`. At this point I think we've found all the types that are entirely public but please let me know if I missed any.

If one day we change our mind and want to add private data, we can do that without issue so this change doesn't preclude any future change we may want to make.

https://github.com/SFML/SFML/commit/73a5a7382df0a82fb74bc8ffcca60eac8d3416a5
https://github.com/SFML/SFML/pull/2590
https://github.com/SFML/SFML/pull/2889
https://github.com/SFML/SFML/pull/2898

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
I thought the policy was to use `struct` for pure data-structures, i.e. when they have no member functions or constructors.

**Comment by ChrisThrasher** [comment]
> I thought the policy was to use `struct` for pure data-structures, i.e. when they have no member functions or constructors.

I saw past precedent like `sf::RenderStates` being a struct with constructors so that's what motivated me. My rationale was as simple as "if everything is public use struct". Ultimately this is not a very important PR so if you're not a fan of this change then that's no problem with me. While we could theoretically sit down and construct a robust rationale for using `class` vs `struct` I'll admit that's not a great use of our time.

**Comment by ZXShady** [comment]
will this be documented? so users who used to forward declare them on MSVC for example won't get crazy linker errors

**Comment by eXpl0it3r** [comment]
Yes, we'll be writing a migration guide.

**Comment by ChrisThrasher** [comment]
I don't think this PR is important enough to spend time debating in time to land before v3 ships.

**Pull request closed without merging**
