### PR TITLE
Added more colors

### PR DESCRIPTION
**Pull request by RUSshy**

### CODE REVIEW

**Comment by naezith** [comment]
Yes, please.

**Comment by MarioLiebisch** [comment]
Your PR removes `sf::Color::Transparent`, which breaks compatibility. Although while I agree we could certainly define more colors, I also think some of  the more obscure ones are more or less bloat.

Maybe we could agree on a common/generic set, possibly predefined names given in other standards, such as CSS?

**Comment by minirop** [comment]
@MarioLiebisch those are the CSS "level 3" colours: https://drafts.csswg.org/css-color-3/#svg-color

**Comment by MarioLiebisch** [comment]
Ah, okay. Some, like blanched almond, sounded really weird to me.

**Comment by RUSshy** [comment]
I added the missing Transparent color, yes these are the CSS3 colors

**Comment by kimci86** [comment]
The Color class documentation should probably be updated.

**Comment by RUSshy** [comment]
Done :p

**Comment by Hapaxia** [comment]
Although these _are_ the [official CSS3 colour names](https://www.w3schools.com/cssref/css_colors.asp), this list unexpectedly breaks compatibility:
"Green" is now only half the brightness that it was. It used to be pure, full green; now it's half green (0, 128, 0) whereas "lime" is full green (0, 255, 0).

**Comment by RUSshy** [comment]
That is why it bugged me and i added the full list of CSS3 colors

Maybe it make sense to add them for SFML 3.0, so it can finally comply with this standard ? ?

**Comment by Hapaxia** [comment]
I think Green being full green makes more sense as it's describing its channel fully used.
This is not least useful when multiplying with a texture where you'd use Green to filter only the green channel; with the CSS list, you'd have to use Lime to filter the green channel (or resort to manual values).

**Comment by TankOs** [comment]
That can indeed be a problem. What about moving all those colors (which I like in general) into their own namespace, e.g. `css3`?

**Comment by LaurentGomila** [comment]
Maybe I missed it, or it's just too obvious, but so far nobody explained the rationale for adding these colors to SFML.

**Comment by TankOs** [comment]
@LaurentGomila Convenience, just like the colors that already exist in sf::Color.

**Comment by LaurentGomila** [comment]
Convenience in which use case? I personally never use these named colors, even the ones that already exist; except maybe black, white and transparent but I could easily live without them being predefined.

**Comment by TankOs** [comment]
@LaurentGomila I used them for some diagrams and UI things, where solid colors played a role. Plus having dyschromatopsia, named colors can help.

**Comment by mantognini** [comment]
I'd argue that this fits perfectly in an add-on to SFML: the CSS (v3) is just one of many, many palettes of colors available out there. For some applications it might be more adapted to use a palette for Nintendo Game Boy Color, while for others might prefer using the Commodore palette. Why selecting the CSS ones and not the X11 color names, or the ones available in Latex? It seems to me to be really arbitrary and choosing one or the other in SFML is not ideal. The set of colors currently available is convenient for debugging, but that's it. Personally, I'm fine with it being that way. It creates more opportunities for great extensions to SFML.

**Comment by mantognini** [comment]
Since my previous comment seems to be accepted -- or at least not debated -- I'm closing this.

**Pull request closed without merging**
