### PR TITLE
Enable and require C++17 support

### PR DESCRIPTION
**Pull request by vittorioromeo**
Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [x] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

This change enables (and requires) C++17 support in all library and executable targets generated by SFML's CMake build.

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

Compiling via CI and executing tests should be enough. There are no expected behavioral changes that might affect the correctness of the existing code.

I've also checked that `-std=c++17` is actually passed by using `CMAKE_EXPORT_COMPILE_COMMANDS`.

### CODE REVIEW

**Comment by SuperV1234** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by vittorioromeo** [comment]
@eXpl0it3r: can this be merged, or should we wait for #1854?

**Comment by Bromeon** [comment]
`cxx_std_17` [requires CMake 3.8](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html), could you adjust the minimum version?

Also, how does this flag relate to the following option?
```cmake
set(CMAKE_CXX_STANDARD 17)
```

**Comment by vittorioromeo** [comment]
> `cxx_std_17` [requires CMake 3.8](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html), could you adjust the minimum version?

Done.

> Also, how does this flag relate to the following option?
> 
> ```cmake
> set(CMAKE_CXX_STANDARD 17)
> ```

That flag is a global setting, it's not on a per-target basis. Global settings are generally frowned upon in "modern CMake" as they can become viral.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Review by Bromeon — APPROVED** [review]
> That flag is a global setting, it's not on a per-target basis. Global settings are generally frowned upon in "modern CMake" as they can become viral.

I see, thanks for the explanation!

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
The first two commits could also be squashed, one doesn't really gain more by having them separated

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
C++17, here we come! 😄

**Pull request merged**
