### PR TITLE
Added an assignment operator to SoundSource

### PR DESCRIPTION
**Pull request by mantognini**
Added an assignment operator to SoundSource.

See @minirop's [PVS-Studio report](http://en.sfml-dev.org/forums/index.php?topic=17906.msg128549#msg128549)

Regarding the implementation, I didn't write the "SFML standard" code, that is:
```cpp
SoundSource& SoundSource::operator =(const SoundSource& right)
{
    SoundSource temp(right);

    std::swap(m_source, temp.m_source);

    return *this;
}
```

Because this would have implied editing the destructor too so that temp would be properly deallocated. I wanted to keep this PR as minimal as possible but let me know if you prefer something different.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
> Because this would have implied editing the destructor too so that temp would be properly deallocated

What do you mean? If the destructor doesn't properly deallocates the class' resources, then there's a problem ;)

And something else: I don't like where you've put this operator =. I tend to put members in the following order:
1. ctors
2. dtor
3. functions
4. operators

**Comment by mantognini** [comment]
> What do you mean? If the destructor doesn't properly deallocates the class' resources, then there's a problem ;)

Actually, my reasoning was incorrect. Everything should fine.

(The invariant 'm_source is always valid during the lifetime of the object' is fine but I somehow thought it would not be the case with the implementation of `=` with swap...)

> I don't like where you've put this operator =. 

Fixed. ;-)

**Comment by Bromeon** [comment]
This is the copy-and-swap idiom (just with inline implementation of swap), it **must** work :wink:

Looks good.

**Comment by mantognini** [comment]
> Should we rethink the semantics?

Good question but I've no idea.. @LaurentGomila?

**Comment by LaurentGomila** [comment]
Well... I don't remember :neutral_face:

**Comment by Bromeon** [comment]
Here is the implementation of `sf::Sound::operator=`. Note the comment in the beginning:
```cpp
Sound& Sound::operator =(const Sound& right)
{
    // Here we don't use the copy-and-swap idiom, because it would mess up
    // the list of sound instances contained in the buffers

    // Detach the sound instance from the previous buffer (if any)
    if (m_buffer)
    {
        stop();
        m_buffer->detachSound(this);
        m_buffer = NULL;
    }

    // Copy the sound attributes
    if (right.m_buffer)
        setBuffer(*right.m_buffer);
    setLoop(right.getLoop());
    setPitch(right.getPitch());
    setVolume(right.getVolume());
    setPosition(right.getPosition());
    setRelativeToListener(right.isRelativeToListener());
    setMinDistance(right.getMinDistance());
    setAttenuation(right.getAttenuation());

    return *this;
}
```
All the assigned attributes except *loop* and *sound buffer* are inherited from `sf::SoundSource`. I think we should move the corresponding code to `sf::SoundSource::operator=` and invoke it in the derived class.

**Comment by mantognini** [comment]
You're probably right but I won't have time during the next week or so to do it so I changed the milestone to 2.4 in order not to block us further with this minor issue.

**Comment by Bromeon** [comment]
Do you guys agree on what I wrote on Apr 14, 2015? If so, I could adapt this commit correspondingly (assuming @mantognini won't mind, as he unassigned himself).

**Comment by mantognini** [comment]
I don't mind. I wanted to review this PR and its decision soon but hadn't had time (and won't probably have time this week) so you're more than welcome to work on it. ;)

(Quickly glancing at your last comment, I still agree with you.)

**Comment by Bromeon** [comment]
I got rid of copy-and-swap in the base class, and used attribute-wise get/set combinations instead. The derived class' assignment operator calls the base class' one. For such changes, it would be really nice to verify with a test case that nothing breaks :grinning: 

The amended commit still carries author information for mantognini, signed off by me. The original commit was cc2c5c5c7d5a9e652c5cf8fca6b551b80df2f32a.

**Comment by mantognini** [comment]
At first sight it looks good. :-)

**Comment by eXpl0it3r** [comment]
Could someone review this?

**Comment by binary1248** [comment]
Looks and works good for me. :+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
