### PR TITLE
Finally done removing custom fixed width integer aliases 

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

Last PR in a series following #2192, #2196, and #2199.

### CODE REVIEW

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
Added some missing headers in extended CI pipeline jobs.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
Added another missing header only caught in the extended CI pipeline.

**Comment by vittorioromeo** [comment]
https://us04web.zoom.us/j/73938690065?pwd=4ars7cgAjQNCTXxy1H4ewGaGFytYs3.1

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by vittorioromeo — APPROVED** [review]
LGTM

**Pull request merged**
