### PR TITLE
Feature/grab mouse

### PR DESCRIPTION
**Pull request by mantognini**
Related to #394.

Adds `sf::Window::setCursorGrabbed` implementations for Linux, Windows and Mac OS X. Android and iOS devices have a «not applicable» implementation.

**Requires testing on:**
- [x] Linux
- [x] Windows
- [ ] OS X
- [ ] iOS (build check only)
- [x] Android (build check only)

Here are a few scenarios to be tested:

1. Grabbing the cursor works when the window has the focus.
2. When grabbed, the cursor should not be able to leave the window.
3. Closing the window should release the cursor.
4. When grabbed, the window should not be resizable by dragging one of its sides.
5. When switching to another app, the cursor should be released and re-grabbed when reactivating the SFML app.
6. If the cursor is outside the view when it is grabbed the cursor should be projected into the window (and thus generate a mouse in event).
7. The user should not be able to move fast the cursor and click outside the window to activate another application.
8. The user should not be able to use the window bar to move, minimize, maximize or close the window.
9. Fullscreen windows should grab the cursor correctly with 2+ monitors.
10. Programmatically moving the window should keep the cursor inside the rendering area in case the cursor was grabbed and properly update the "grab area" to match the new window position.
11. Like 10. but when programmatically resizing the window.

[This code](https://gist.github.com/mantognini/20226256cbac2b138db0) can be useful for testing.

Below is the list of issue from the above list that need to be fixed before merging this PR:

 - Linux: 5 (should be fixed, confirmation needed)
 - OS X: N/A
 - Window: N/A
 - iOS: N/A
 - Android: N/A

**Regarding OS X:** [Updated on 25/4/2016]
~~The current impl is not bad but still an approximation of the feature (test n° 7 is somewhat supported and n° 8 is not supported at all) . It seems really hard to do it on Mac. Other libs (e.g. SDL) have even more bugs or undesired behaviour than this implementation. However, a lot of tricks are used which is not nice at all for future modifications of `SFOpenGLView` (among other things).~~

~~Commit d16d38e contains a more detailed explanation of the known issues (in commit message and comments in the code itself). I'm reluctant to include this commit in SFML codebase because it will considerably increase the complexity of the code and make it really hard to maintain. All that to "only" workaround a stupid corner case... Please let me know what you think.~~

~~An alternative for games that need grabbing would be to hide the cursor and use relative motion, preventing the cursor to actually move. This would involve much fewer corner cases in the implementations. Actually, SDL also provides this alternative.~~

Please refer to commit 4f5baa53ece0f8777c23d1027098ceff7c2cea3c for detailed description of the workarounds involved.

### CODE REVIEW

**Comment by binary1248** [comment]
Bump. :stuck_out_tongue:

**Comment by mantognini** [comment]
I'm still interested in feedback regarding these two points from the description above (no need to actually read the code to have an opinion about it).

First:

> The current impl is not bad but still an approximation of the feature (test n° 7 is somewhat supported and n° 8 is not supported at all) . It seems really hard to do it on Mac. Other libs (e.g. SDL) have even more bugs or undesired behaviour than this implementation. However, a lot of tricks are used which is not nice at all for future modifications of SFOpenGLView (among other things).
> 
> Commit d16d38e contains a more detailed explanation of the known issues (in commit message and comments in the code itself). I'm reluctant to include this commit in SFML codebase because it will considerably increase the complexity of the code and make it really hard to maintain. All that to "only" workaround a stupid corner case... Please let me know what you think.

Secondly (well that was not really a question but... opinions are welcomed):

> An alternative for games that need grabbing would be to hide the cursor and use relative motion, preventing the cursor to actually move. This would involve much fewer corner cases in the implementations. Actually, SDL also provides this alternative.

**Comment by mantognini** [comment]
[Some build](http://sfml-dev.org:8080/job/sfml-windows7-64-tdm481/39/) got stuck in "pending" state apparently. Can it be easily restarted? I'd rather not dig into github API to unstuck it if possible. :-)

**Comment by mantognini** [comment]
Sorry, actually it doesn't matter since I'll have to rebase the branch someday so it'll run again...

**Comment by eXpl0it3r** [comment]
>  Can it be easily restarted? I'd rather not dig into github API to unstuck it if possible

No and it has nothing to do with the GItHub API, unless you simply wanted to change the status.

Also don't worry about it. If it builds on all the other Windows setups it will most certainly also run on this. It aborted because of a broken build script.

**Comment by Bromeon** [comment]
The oldest pending pull request... It needs rebase. About the points mentioned by @mantognini:

> Commit d16d38e contains a more detailed explanation of the known issues (in commit message and comments in the code itself). I'm reluctant to include this commit in SFML codebase because it will considerably increase the complexity of the code and make it really hard to maintain. All that to "only" workaround a stupid corner case... Please let me know what you think.

It's really difficult to tell as a non-OSX user how much this would affect usability. If you personally consider it not really important (or the workaround creates more problems than it solves), you can leave it out -- but maybe keep the code somewhere around, in case it gets relevant again.

> An alternative for games that need grabbing would be to hide the cursor and use relative motion, preventing the cursor to actually move. This would involve much fewer corner cases in the implementations. Actually, SDL also provides this alternative.

I assume you mean a FPS-style view where the cursor remains always centered. What do you mean with "SDL provides this alternative"? This is a UI decision of the higher-level application logic, not something in the library API, is it? SFML should already enable this by making the cursor invisible and setting its position.

**Comment by eXpl0it3r** [comment]
> I assume you mean a FPS-style view where the cursor remains always centered. What do you mean with "SDL provides this alternative"?

I'm not sure, but it sounds more like a third option. Where the mouse "stops" having an absolute position and all you get is the delta values.

**Comment by mantognini** [comment]
> I assume you mean a FPS-style view where the cursor remains always centered.

Yes

> What do you mean with "SDL provides this alternative"? This is a UI decision of the higher-level application logic, not something in the library API, isn't it?

With SDL you can choose the behaviour you want through `SDL_SetRelativeMouseMode` which description reads as follows:

> While the mouse is in relative mode, the cursor is hidden, and the driver will try to report continuous motion in the current window. Only relative motion events will be delivered, the mouse position will not change.

Actually, when I looked at this feature a while ago I thought I saw another function to clamp the cursor inside a window. Either I don't recall correctly or the function disappeared since then... Whichever is more likely, I let you judge. =P

> SFML should already enable this by making the cursor invisible and setting its position.

Yes, but that's by far not as efficient as having a dedicated OS function; at least on OS X where setting the cursor position too frequently will significantly slow down things (again, if I remember correctly after those two years...)

**Comment by Bromeon** [comment]
Ah, so the "relative mouse mode" is actually something supported on OS level? Okay, I didn't know that. But I think we should keep the thread here about mouse grabbing and discuss relative mouse movement on the forum, as it would also come with new event types etc.

Or do you think we should not support grabbing at all?

**Comment by MarioLiebisch** [comment]
In the end grabbing the mouse cursor is important, that's why I initially started this.

You'll need this functionality whenever you want to control something with cursor movement that is not a cursor (or to make edge movement easier).

If you want the camera to move based on mouse movement or when you want to do some action once the cursor hits the corner of the window (think classic RTS gameplay), there's hardly a way around capturing the cursor.

> SFML should already enable this by making the cursor invisible and setting its position.

It's not that easy. Assume some lag between two times resetting the cursor (for whatever reason): If you manage to move the cursor outside and click, you'll lose window focus and things go south. While it sounds unlikely, it can happen. I've seen it happen to me in a few games with improper implementation.

Some programs even have options for that (e.g. most virtual machines offer something like "capture mouse cursor" or "seamless mode", which is essentially this).

**Comment by mantognini** [comment]
Sorry for the latency between answers...

> Or do you think we should not support grabbing at all?

Well, we only need one of the two (grabbing vs hidden+fixed+relative movement), and with the latter we can implement the former without much trouble (performance-wise but also algorithmic-wise as you only need min() & max() to implement it) while it seems the reciprocal is not that simple. 

The other benefit, for me at least, is that the implementation for OS X would require a lot less hacking and workarounds.

**Comment by mantognini** [comment]
I meant we can hide the system cursor, fix its position (say, to the center of the window) and using only relative motions, the user can display a sprite where the cursor should be. So we wouldn't use the system cursor per se, you're right about that. It's for sure slightly less convenient for the user to code the last part himself, but I'm guessing people are more interested in FPS-like cursor. (or am I wrong to assume that?)

**Comment by MarioLiebisch** [comment]
Don't forget that mouse movement is independent from event handling. So it would still - in theory - be possible, to move the cursor outside the window and click between two updates, resulting in a fokus switch and the window no longer receiving events (at least on Windows; not sure how Mac OS X or X11 would handle that.

**Comment by mantognini** [comment]
This cannot happen on OS X as the cursor is really fixed and clicks happen on the cursor position. Isn't it a thing like that on Windows? How can FPS implement reliably cursor handling then?

-----Original Message-----

**Comment by MarioLiebisch** [comment]
Updating the cursor position happen through messaging. So if I move the cursor and click before SFML can react to the mouse movement (and the window manager notices the position change request), the mouse click already happened (focus change).

**Comment by mantognini** [comment]
So, if I understand correctly, the current PR is not perfect for Windows too?

**Comment by MarioLiebisch** [comment]
This PR traps the mouse cursor inside the client area on window manager level (outside window messaging). It won't be able to be moved outside or generate window events outside, no matter how often SFML handles events.

**Comment by mantognini** [comment]
Oh, okay. From your previous message I thought there were no "complementary" feature to the message passing thing.

**Comment by Bromeon** [comment]
So it seems like we need both for total flexibility? Since we almost have an implementation for mouse grabbing, let's continue with that now :wink:

Are there changes planned for Windows? Otherwise I could test it. About the OS X implementation, as I said, maybe we could go with the simpler one and think about the imperfect workaround when the need actually arises.

**Comment by MarioLiebisch** [comment]
Think it should be fine for Windows.

**Comment by mantognini** [comment]
Okay, so I'll update and review this branch in the coming days. I'll let you know when it makes sense to test it. ;-)

**Comment by mantognini** [comment]
I've managed to rebase this branch and fix the conflict due to line ending. Quite a mess to solve to be honest.

I've also reworked the OS X implementation in a much better way -- there are still some rather fancy workarounds but at least it seems to work correctly. However, my work is based on #1042. This means that this PR (#614) should not be merged before #1042.

Also, regarding the Linux implementation: since the first implementation of this feature by @MarioLiebisch, we switched to XCB and therefore needs to be rewritten. I've kept most of the code (sometimes in the form of a comment when it was obviously not going to compile) so that the update should be, hopefully, rather easy.

If someone has time to fix it for Linux, you can send me a patch (ideally by posting it here).

**Comment by mantognini** [comment]
> If someone has time to fix it for Linux, you can send me a patch (ideally by posting it here).

Still calling for volunteer! :wink:

**Comment by Schilleey** [comment]
It would be really nice to have the "relative movement" feature. Many other frameworks provide this feature too. In GLFW you could use the **glfwSetInputMode** function:

> GLFW_CURSOR_DISABLED hides and grabs the cursor, providing virtual and unlimited cursor movement. This is useful for implementing for example 3D camera controls.

Thanks for the great work so far :)

**Comment by mantognini** [comment]
@Schilleey I agree with you. It was mentioned above I believe, but for now we should rather work out one feature since we still need an update for the Linux implementation. Speaking of which, do you by any chance know this XCB stuff? :-)

**Comment by Schilleey** [comment]
> Speaking of which, do you by any chance know this XCB stuff? :-)

Sorry, I got no experience with XCB :(

**Comment by binary1248** [comment]
Unix implementation is done.

**Comment by mantognini** [comment]
This branch was rebased.

**Comment by eXpl0it3r** [comment]
So are implementations for all three major platforms ready? Shall we commence with in-depth testing?

@mantognini Do you want to do a rebase (again)? :wink:

**Comment by mantognini** [comment]
Rebased and ready for testing. 😉

**Comment by eXpl0it3r** [comment]
Thanks! :smiley:

**Comment by eXpl0it3r** [comment]
I just tested the code and ran into an issue (on Windows). If you grab the mouse cursor and then move the window, the locked rectangle won't move with the window, so you'll be trapped at the old location of the window. If you change the window position before grabbing the mouse, the locked rectangle will be placed correctly.

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window1(sf::VideoMode(800, 600), "SFML1");
    window1.setFramerateLimit(60);
    window1.setMouseCursorGrabbed(true);
    window1.setPosition({0, 300}); // Moving here

    while (window1.isOpen())
    {
        sf::Event event;
        while (window1.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window1.close();
        }

        window1.clear();
        window1.display();
    }
}
```

I guess one needs to update the locking area when moving the window.

Other than that it seems to work fine on Windows, even with multiple windows.

**Comment by mantognini** [comment]
> I guess one needs to update the locking area when moving the window.

Or prevent the window to be moved? I think that's what I did for Mac.

**Comment by eXpl0it3r** [comment]
Seems a bit unintuitive to disable a "random" function.

**Comment by binary1248** [comment]
This is obviously an oversight in the Windows implementation. Instead of undefining features so that we have less work to do implementing others, we should just fix the problem. :wink:

**Comment by mantognini** [comment]
Well, the definition is this:

> If set, grabs the mouse cursor inside this window's client area so it may no longer be moved outside its bounds.

So it does make sense to prevent dragging the title bar.

**Comment by eXpl0it3r** [comment]
> So it does make sense to prevent dragging the title bar.

You can't drag the title bar, but we still have `window.setPosition()` as shown in my code above. Should that suddenly stop working?

**Comment by mantognini** [comment]
I should have read your piece of code... now I've to debug the OS X impl as well. Damned! :(

**Comment by mantognini** [comment]
Alright... rebased and OS X impl fixed.

**Comment by eXpl0it3r** [comment]
For Windows the fix might be as easy as to add two lines to [the setPosition WindowImplWin32](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Win32/WindowImplWin32.cpp#L279):

```cpp
if(m_cursorGrabbed)
    grabCursor(true);
```

Looking through the code I noticed that nothing happens in fullscreen mode (on Windows), why is that? On my two monitor setup I can certainly move my mouse out of the window which for an FPS is not what I want. Does grabbing not work in fullscreen?

**Comment by binary1248** [comment]
@MarioLiebisch wrote those lines in 89e0d5c458d9b8455816df263288438a8e515e22, so he should know best, but it looks to me like an optimization that doesn't take multiple monitors into account?

**Comment by mantognini** [comment]
I added the suggested changes. Let me know how it goes.

Regarding fullscreen, I should probably test this on OS X as well but I don't have a monitor close-by...

**Comment by eXpl0it3r** [comment]
Quickly testing it on Windows again and it seems to be enough to remove [these two lines](https://github.com/SFML/SFML/pull/614/files#diff-f70b88213909f545b38d4f8774e66839R506).

> but I don't have a monitor close-by...

How can you live without a second monitor? :scream_cat:

**Comment by mantognini** [comment]
Cool! I'll apply the patch next week.

> How can you live without a second monitor? 🙀

I've got only a 15" and I don't mind it. Shocking, isn't it? :stuck_out_tongue_winking_eye:

**Comment by nabijaczleweli** [comment]
Filthy casual :P

**Comment by mantognini** [comment]
I've applied the patch suggested by @eXpl0it3r and rebased against master. Thankfully, OS X didn't need a patch for multi monitor support. :-)

**Comment by mantognini** [comment]
I've updated the PR description to include a list of OSes that need to be tested as well as a list of scenarios to be examined. It would be great if someone different from the implemented could test those.

**Comment by victorlevasseur** [comment]
Tested on Linux. Works nice except that the mouse is not re-grabbed when the window gets back the focus. 

Specs : Fedora 23 (x64), Gnome 3.18

**Comment by mantognini** [comment]
Thanks for testing! 😃 

I've updated the description (and I'll try to keep it up-to-date) with a list of defects to simplify bookkeeping.

**Comment by victorlevasseur** [comment]
Just a small precision : after having taken the focus back (and failed re-grabbing the mouse), the next call to setMouseGrabbed(true) is ignored.

**Comment by victorlevasseur** [comment]
More information : this bug only occurs when the window get the focus back while the mouse is outside the window area.

**Comment by victorlevasseur** [comment]
It seems that SDL avoids this problem by trying to grab the mouse until it succeeds (but this would cause the app to freeze if the grab is impossible).

**Comment by victorlevasseur** [comment]
I managed to fix this on my own Github fork of SFML. Can I send you a PR to add the commit to the official branch or should I send a patch instead ?

**Comment by mantognini** [comment]
Great! You can create a PR and I'll manually integrate it on this branch so that other can test your fix. :-)

**Comment by victorlevasseur** [comment]
Done (#1107). :+1:

**Comment by mantognini** [comment]
The proposed patch was included in this PR, so linux users feedback (on both the implementation and its effect) is welcome.

**Comment by eXpl0it3r** [comment]
I just tested it again on Windows and all 11 points seem to work as expected, except for point 8, which I'm not certain how you meant it exactly.

> 8. The user should not be able to use the window bar to move, minimize, maximize or close the window.

Does that mean one should under no circumstances be able to move the window? On Windows I can't minimize, maximize or close the window via the window bar, but I can move the window, when I first "tab out" of the window and then move the cursor to the bar. Not sure how other OS handle this, but personally I think this may very well be left as OS-specific quirk (unless there's a clean "fix").

Additionally I've successfully tested another point, that being: When you change the mouse cursor programmatically, it shouldn't leave the grabbed area.

I added the following few lines to your code:

```cpp
case sf::Keyboard::M:
	sf::Mouse::setPosition({-10,-10});
	break;

case sf::Keyboard::R:
	window.setSize({100, 100});
	break;

case sf::Keyboard::P:
	window.setPosition({0, 0});
	break;
```

**Comment by victorlevasseur** [comment]
> Does that mean one should under no circumstances be able to move the window? On Windows I can't minimize, maximize or close the window via the window bar, but I can move the window, when I first "tab out" of the window and then move the cursor to the bar. Not sure how other OS handle this, but personally I think this may very well be left as OS-specific quirk (unless there's a clean "fix").

I think it should be the case only when the window has the focus (that's the way I understood it).

**Comment by mantognini** [comment]
Yes, that's what I had in mind.

**Comment by victorlevasseur** [comment]
I can confirm that all points work well on Linux.

**Comment by eXpl0it3r** [comment]
I assume you've tested it on OS X, @mantognini? Doubt we can find anyone for iOS, so should I add it to the merge list?

**Comment by mantognini** [comment]
Yes, you can go ahead.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
