### PR TITLE
Add sfml include directory to target interface

### PR DESCRIPTION
**Pull request by rroohhh**
Adding the sfml include directory to the target interface makes using sfml as a subproject in cmake easier, because linking against one of the sfml libraries then pulls in the sfml include directory automatically to the target include directories.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Can you describe the use case a bit more detailed?

Also note that our preferred platform to discuss changes is according to the [contribution guidelines](http://www.sfml-dev.org/contribute.php) [our forum](http://en.sfml-dev.org/forums/index.php).

**Comment by MarioLiebisch** [comment]
Never used it myself, but I guess this allows you to add SFML as a subproject and you're then able to just use `target_link_librararies(mytarget sfml-graphics sfml-window sfml-system)` for example and you'd also get the correct include directories set without calling `include_directories(...)` explicitly.

**Comment by rroohhh** [comment]
@eXpl0it3r it allows exactly what @MarioLiebisch  says

**Comment by mantognini** [comment]
That could be interesting to have, but I believe this feature was added in CMake 3.0. I am right? If so it would require bumping the cmake requirement as well. I'm not against this, however I remember that at one point someone tried to do that and it broke SFML build system... maybe I'm wrong but this should get investigated.

Also, nowadays, can we expect v3.0 to be available on the supported platforms? I know this is okay on OS X (or I should say macOS...), but what about Linux package managers? (I expect that on Windows the user has to use cmake installer anyway so this ain't an issue.)

**Comment by rroohhh** [comment]
I think [v2.8.11](https://cmake.org/cmake/help/v2.8.11/cmake.html#command:target_include_directories) should be fine. That should be available on (nearly) all systems.

**Comment by eXpl0it3r** [comment]
Debian 7 is still only on 2.8.9: https://packages.debian.org/source/wheezy/cmake

**Comment by rroohhh** [comment]
But cmake 2.8.11 is in backports (https://packages.debian.org/wheezy-backports/cmake)

**Comment by LaurentGomila** [comment]
May I ask why you would want to add SFML as a sub-project of something else? You usually bring a pre-compiled SFML with find_package, and the include path is properly managed with that.

**Comment by rroohhh** [comment]
I do that for all libraries I use, because it makes it easier for me to update to new versions, when the package provided by the distribution is not up to date. Also it makes it easier to compile a project with a bunch of dependencies on a new system.

**Comment by imerr** [comment]
I definitely agree with rroohhhhere, just including dependencies as cmake sub projects makes dependencies so much easier (especially when using git submodules or something like that to automatically fetch them)

**Comment by eXpl0it3r** [comment]
The latest changes now mix different issues (Intel compiler support). The different adjustments should be committed in separate PRs.

**Comment by rroohhh** [comment]
Sorry pushed to the wrong branch. Should be fixed now.

**Comment by eXpl0it3r** [comment]
Is this still relevant with the changes we did with CMake, @Ceylo?

**Comment by Ceylo** [comment]
No, this is now done already at https://github.com/SFML/SFML/blob/master/cmake/Macros.cmake#L163

**Pull request closed without merging**
