### PR TITLE
Only spawn Resized event when window size changes.

### PR DESCRIPTION
**Pull request by TankOs**

### CODE REVIEW

**Comment by kimci86** [comment]
I just tested it.
Now, moving the window does not push Resized events.

However, some problems remain: one event is pushed on window creation (initializing properly m_previousSize could solve it) and two events are pushed when the window is maximized.
Only one is pushed when the window is restored though, which is good.

**Comment by TankOs** [comment]
> one event is pushed on window creation

I don't really consider this to be a bug.

> one event is pushed on window creation

Thanks, will look into it.

**Comment by TankOs** [comment]
I talked with @kimci86 at IRC about this. At some place he got indeed multiple Resized events, but in a way that can't be avoided: kimci's window manager reported size changes, and that's what the SFML event is for. ;-)

Keep in mind that manually altering the window might often result in 2 events, as the window manager takes over and adjusts the size, so that the window decoration fits etc.

**Comment by TankOs** [comment]
Feel free to merge :+1: :cat2:

**Comment by mantognini** [comment]
BTW, some time ago, we discussed a similar issue. The conclusion was to let the user deal with multiple events. Now, sure, it's appreciated not to fire 1000 events in the face of the user at once. But it's alright to have a few dups.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged into 2.3.x soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in 608b4fb28d68ea9ba251f31965f533d082cdd816 on branch 2.3.x

**Pull request closed without merging**
