### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by r-e-d**
Fix the comment in sf::Touch::getPosition

### CODE REVIEW

**Comment by TankOs** [comment]
Thanks :)

**Comment by r-e-d** [comment]
Can someone merge this now that 2.3.2 is released :)

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in aa4f0681db4ecdd582921db6305e323ec3e385e1

**Pull request closed without merging**
