### PR TITLE
Deduplicate `Window{Base}::create` implementations

### LINKED ISSUE #2851: Deduplicate implementations of `WindowBase::create` and `Window::create`
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

These two functions are nearly identical in their implementation. It would make the library easier to maintain if the common code was extracted out into one place.

### Use Cases

Gotta add some text here so GitHub will let me submit the issue.

### API Example

_No response_

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

Closes #2851

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by binary1248** [comment]
This change adds an OpenGL specific header to `WindowBase` although it was specifically designed to be OpenGL-free. If you really want to reuse that common block of code in `::create` you should move the differentiating lines of code into `::initialize` instead of adding `ContextSettings` to `::create`.

**Comment by ChrisThrasher** [comment]
> This change adds an OpenGL specific header to WindowBase

What's the problem with doing this? WindowBase.cpp already used it.

**Comment by binary1248** [comment]
Not in the header. Everyone should know by now that OpenGL forces one to have to make dirty implementation decisions from time to time. Creating a "dummy context" in `::create` was necessary even when not using OpenGL in order to not break stuff on specific OSes. This is unavoidable, but we still get to choose whether we want to expose this dirtiness via the public header. The header was clean before this change, and would no longer be after it.

**Comment by ChrisThrasher** [comment]
> The header was clean before this change, and would no longer be after it.

It's only "dirty" in some philosophical sense. I cannot think of any technical issues with what I did.

**Comment by ChrisThrasher** [comment]
I used a forward declaration to avoid including ContextSettings.hpp.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by binary1248** [comment]
Deduplicating code no matter the design cost can also devolve into a philosophical debate. The code before worked in every technical sense. We can't preach a different standard every day depending on what metric we are looking at.

Like I said, the only reason `WindowBase` exists is to provide Vulkan users with a class that is from their point of view OpenGL-free. Having to break this requirement just to save a few lines of code makes the entire class useless. If we were really hellbent on reducing the total lines of code we could just throw out `WindowBase` entirely and tell people to use `Window` instead.

When designing new public interfaces and eventually writing the accompanying implementation we should never let the implementation dictate what the public interface will look like if there are viable alternatives. Having a clean API philosophy is what separates good/learnable libraries from those that were written by people who "just needed to get the job done". We should really hold ourselves to higher standards.

**Comment by ChrisThrasher** [comment]
Let me know if the latest state of the PR works for you or if that forward declaration is unacceptable.

**Comment by binary1248** [comment]
Forward declarations just alleviate the need to have to include a header which is C-legacy, having to expose private function signatures in the publicly visible header is also C++-legacy. The semantic dependency they force is still there. Hypothetically, if we were to rename `ContextSettings` to `SomeOtherContextSettings` or one day even completely get rid of the OpenGL implementation, we would also have to touch this header although the class really shouldn't have anything to do with OpenGL.

This is a uniquely C/C++ problem, as you noticed it is much harder to design clean APIs around weird OS implementation requirements than would be necessary in other languages. Over the decades C++ developers have designed workarounds for this problem like PIMPL, but they all come with their own tradeoffs. The tradeoff that was made in the current implementation was duplication of that small block of code, however IMHO it is the lesser of all evils if we really value having a clean _C++_ API.

**Comment by ChrisThrasher** [comment]
> you should move the differentiating lines of code into ::initialize instead of adding ContextSettings to ::create.

If you explain this some more then perhaps we can find a solution that satisfies your ideals of cleanliness. Otherwise this is the solution we're best off moving forward with.

**Comment by binary1248** [comment]
https://github.com/SFML/SFML/compare/master...window_create

**Comment by ChrisThrasher** [comment]
Your solution looks pretty obvious in hindsight. Thanks!

**Review by binary1248 — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Pull request merged**
