### PR TITLE
Update year to 2022 (master branch)

### PR DESCRIPTION
**Pull request by Bromeon**
Follow-up to https://github.com/SFML/SFML/pull/1954.

Excludes license file, which is handled by https://github.com/SFML/SFML/pull/2001.

### CODE REVIEW

**Review by eXpl0it3r — APPROVED** [review]
Hmm odd, your [other commit](https://github.com/SFML/SFML/commit/3b069726022929ec00cc91417db2c5114ff9c86e) is on master already, guess we just overlooked some files 😄

**Comment by Bromeon** [comment]
Oh, good catch! Would it make more sense if I fix that (and we then back-merge `2.6.x` to `master`)?
Or do you want me to create a separate PR for `2.6.x`?
Maybe in terms of potential future merge conflicts, one "source of truth" (2.6.x) is better. There are a few new files though...

Let me know what you think.

**Comment by eXpl0it3r** [comment]
I guess it would make sense to update it on the `2.6.x` branch as well and then one for the new files on master

**Comment by Bromeon** [comment]
Created a separate PR for `2.6.x`.

I wondered why I missed the initial changes. I use a `grep` version on Git-for-Windows; maybe I used it wrong? 🤔

**Comment by vittorioromeo** [comment]
LGTM, merging it in

**Comment by eXpl0it3r** [comment]
Will be interesting to see how git handles the backmerge from `2.6.x` 😅

**Pull request merged**
