### PR TITLE
Preparations for SFML 2.3.2

### PR DESCRIPTION
**Pull request by eXpl0it3r**
All the issues and PRs which were marked for 2.3.2 have been merged. Now we need to test it and we should be ready for a new patch release.

### CODE REVIEW

**Comment by binary1248** [comment]
:+1:

Everything works as expected for me. Looks like Jenkins had a bad time with GitHub when it wanted to build. :stuck_out_tongue:

**Comment by eXpl0it3r** [comment]
So since (apparently) nothing has happened while I took a break from SFML related stuff, shall we proceed with the release?

**Comment by binary1248** [comment]
If there was anything wrong with it people would have noticed by now.... so I guess it's release time...

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon into the 2.3.x branch, unless someone raises any concerns.

**Comment by mantognini** [comment]
:+1:

**Comment by MarioLiebisch** [comment]
What's the status on the **feature/VS2015** branch? I'd consider that quite a major thing, especially considering number of people using VS2015 won't decline.

**Comment by eXpl0it3r** [comment]
> What's the status on the feature/VS2015 branch? I'd consider that quite a major thing, especially considering number of people using VS2015 won't decline.

Well see the internal discussion. I wanted to move things quickly, but others want to have further in-depth discussions. :wink:

**Pull request merged**
