### PR TITLE
Add support to test the vulkan example on CPU

### PR DESCRIPTION
**Pull request by caramelli**
In addition to the discrete and integrated devices, I also test the vulkan example on CPU with this change proposal.

### CODE REVIEW

**Review by binary1248 — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by caramelli** [comment]
CI / Windows VS2019 x86 Static Debug (pull_request) failed. Any ideas?

**Comment by caramelli** [comment]
CI / Windows VS2019 x86 Static Debug is now OK (without changing anything on my side).

**Comment by eXpl0it3r** [comment]
Maybe it just needed a retrigger, didn't see the failure myself

**Comment by vittorioromeo** [comment]
> Maybe it just needed a retrigger, didn't see the failure myself

Yes, it was a spurious failure. I retriggered it

**Pull request merged**
