### PR TITLE
Skip glTexCoordPointer() call if not needed (performance optimization)

### PR DESCRIPTION
**Pull request by hobby8**
Aimed at saving memory bandwidth for drawing operations not involving textures nor shaders.
More details in [this forum thread](http://en.sfml-dev.org/forums/index.php?topic=19441.0).

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
Merged in 973ac8ddcd5eea22a01556405e16c554c7dd9788 on master

**Comment by naezith** [comment]
This update broke one of my shaders, it was working beautifully before. It's broken because my quad does not have a texture so gl_TexCoord[0].xy is (0,0) everywhere in the quad.

Is there an alternative variable I can use for that? I am [drawing these bars](https://puu.sh/vQ7Qw/9fa0d05493.png) and I need to know which pixel I am at.

```cpp
void JumpPad::renderBar() {
        sf::VertexArray quad(sf::Quads, 4);
        sf::FloatRect new_rect = jp_rect.getGlobalBounds();
        quad[0].position = sf::Vector2f(new_rect.left, new_rect.top);
        quad[1].position = sf::Vector2f(new_rect.left + new_rect.width, new_rect.top);
        quad[2].position = sf::Vector2f(new_rect.left + new_rect.width, new_rect.top + new_rect.height);
        quad[3].position = sf::Vector2f(new_rect.left, new_rect.top + new_rect.height);

        quad[0].texCoords = sf::Vector2f(0, 0);
        quad[1].texCoords = sf::Vector2f(1, 0);
        quad[2].texCoords = sf::Vector2f(1, 1);
        quad[3].texCoords = sf::Vector2f(0, 1);

        Game::i().rt.draw(quad);
}



// Rendering all jump pads
    sf::Shader::bind(&shader_jump_pad);
    sf::Texture::bind(nullptr);
    for(auto& jp : jumppads) jp.renderBar();
    sf::Shader::bind(nullptr);
```

**Comment by LaurentGomila** [comment]
`Shader::bind` and `Texture::bind` are meant for use with OpenGL drawing. Why are you using them together with regular `RenderTarget::draw` calls?

The "right" way to do it would be:
```cpp
Game::i().rt.draw(quad, &shader_jump_pad);
```

**Comment by naezith** [comment]
I was doing what you wrote but binding once was faster as I remember, coded it long time ago. They work nicely now without gl_TexCoord

**Pull request closed without merging**
