### PR TITLE
Drop 32 bit support on iOS

### PR DESCRIPTION
**Pull request by JonnyPtn**
see #1372

### CODE REVIEW

**Comment by Ceylo** [comment]
Now that you have a single simulator I’d also remove all references to SIMULATOR64 and keep only SIMULATOR.

**Comment by JonnyPtn** [comment]
Very good point - done!

**Comment by JonnyPtn** [comment]
1 week bump...

**Comment by eXpl0it3r** [comment]
Merged in b196aac5c7ee90e4a33d8d7c642b01b813f6fea0

**Pull request closed without merging**
