### PR TITLE
Edit gitignore to ignore clion default output directory

### PR DESCRIPTION
**Pull request by LDprg**
* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [x] If you have additional steps which need to be performed list them as tasks!

----

## Description

Just a small fix to prevent git to add Clion standard ouput paths.

## Tasks

* [x] Tested on Linux
* [x] Tested on Windows
* [x] Tested on macOS
* [x] Tested on iOS
* [x] Tested on Android

## How to test this PR?

Obviously this change will work on every platform.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Just use a binary directory named `build` to avoid needing to do this. Otherwise, set up a global .gitignore so that we don't have to keep adding stuff to this file.

https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

**Comment by Bromeon** [comment]
> Just use a binary directory named `build` to avoid needing to do this. Otherwise, set up a global .gitignore so that we don't have to keep adding stuff to this file. Or you can also make a binary directory outside of the repo. You've got a few options.

So we explicitly gitignore the project folder `.idea`, but then don't go the full mile and instead say "you need to take care of the build folder yourself"? That doesn't make sense to me.

Of course people can set up things themselves, but the point of this `.gitignore` file is precisely that they don't have to.

CLion is a popular IDE, and @LDprg already put in the effort to open a pull request. I don't see a reason to _not_ merge this.

**Comment by ChrisThrasher** [comment]
> So we explicitly gitignore the project folder .idea, but then don't go the full mile and instead say "you need to take care of the build folder yourself"? That doesn't make sense to me.

You're confusing my ideas (keep the .gitignore minimal) with the SFML team's idea (make the .gitignore file big). In past discussions I've disagreed with adding stuff like .idea and other IDE-specific directories to the .gitignore when that file need not include anything more than the `build` directory.

**Comment by Bromeon** [comment]
@ChrisThrasher Ah, I see.

My opinion on such things is: it's a very small change for us (here even more since a PR is readily mergable), with near-zero downsides, but it saves _many_* users from spending extra time on configuration or having ignored files show up in Git.

I'm not sure if it's our job to educate people on using global .gitignores. Which btw also comes with drawbacks, as certain projects want their IDE config at least partially versioned (notably single developers or a team on the same IDE).

\_________
\* hard to say how many. Purely utilitarian, even 1-2 might pay off already time-wise.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
Thanks for this enhancement! 🙂

**Pull request merged**
