### PR TITLE
Clarify Image::copy implementation

### PR DESCRIPTION
**Pull request by kimci86**
## Description

As discussed in the recent `sf::Image` PR https://github.com/SFML/SFML/pull/2117#pullrequestreview-1014201329, I thought the `Image::copy` implementation was at least confusing if not buggy, so here is I hope a cleaner version.

@Bambo-Borris @vittorioromeo What do you think?

## How to test this PR?

- Unit tests on CI

### CODE REVIEW

**Comment by Bambo-Borris** [comment]
Yeah I totally agree, it looked super ugly and needed some TLC. Really happy to see the tests uncovered some problems, and they provide reassurance these changes haven't introduced any new problems. Looks good to me

**Review by Bambo-Borris — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by vittorioromeo — APPROVED** [review]
Looks like a significant improvement to me. Allowing others to take a look before merging

**Comment by eXpl0it3r** [comment]
Thanks for the clarifications! 🥳

**Pull request merged**
