### PR TITLE
Updated the binary libs from exlibs/libs-ios

### PR DESCRIPTION
**Pull request by sol-prog**
Updated the binary libs from exlibs/libs-ios in order to work with Xcode 8 and iOS 10.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
What about libvorbisenc.a and libvorbisfile.a? Are they now included in libvorbis?

**Comment by sol-prog** [comment]
AFAIK, libvorbis contains everything now. I took the source code from here https://xiph.org/downloads/ . No libvorbisenc or libvorbisfile in there.

**Comment by eXpl0it3r** [comment]
Yes, I vaguely remember them including everything in a more "recent" up to date.

**Comment by MarioLiebisch** [comment]
Are the headers still compatible? Or would we have to update everything at once?

**Comment by sol-prog** [comment]
My SFML build uses the headers provided here, I've changed only the compiled libraries.

**Comment by eXpl0it3r** [comment]
Btw. do these libs now contain multiple version for armv7, arm64, i386, x86_64? And is that reason why they are relatively large compared to say Windows libs?

**Comment by sol-prog** [comment]
Yes, these are fat binaries which contains armv7, arm64, i386 and x86_64.

**Comment by sol-prog** [comment]
You can check this with something like:

`xcrun lipo -info <lib_name>.a`

**Comment by eXpl0it3r** [comment]
Thanks! I'll mark this then ready for merging.

We greatly appreciate any other contributions you could make with regards to iOS.

**Comment by eXpl0it3r** [comment]
Merged in 700fc7d9e0f97c7cf1b9be28dcb01d766a451d04

**Pull request closed without merging**
