### PR TITLE
Added CPack definitions and an NSIS template for easy packaging

### PR DESCRIPTION
**Pull request by MarioLiebisch**
This change allows simple packaging using CPack, i.e. `cpack .` in your build directory. This will use a default packager based on the operating system and environment.

It's also possible to pick specific packagers/generators to create compressed archives or packages (e.g. `cpack -G ZIP .` to create a ZIP archive).

If the [Nullsoft Scriptable Install System](https://sourceforge.net/projects/nsis/) ist available, `cpack -G NSIS .` may be used to create a wizard style installer for Windows:

NSIS Installation Wizard

---

_The "compiler identification" for the path and "Add/Remove Programs" entries (Windows) still need some better solution to not only show "GNU" or "MSVC"._

**_Any suggestions?**_

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Are BMPs the only supported format?

**Comment by binary1248** [comment]
I use NSIS at work. From what I can tell, it uses BMPs because that is the only format for which there are native win32 functions.

**Comment by MarioLiebisch** [comment]
Yep, as far as I know the original assets (WinAPI resources) in the setup program are just replaced with these. I could try using some compressed/smaller format (palettized or RLE), but not sure it's worth it?

**Comment by binary1248** [comment]
Those images aren't meant to be that big anyway. Compared to the rest of the contents they normally don't make up a noticeable amount of the total size.

**Comment by MarioLiebisch** [comment]
Just tried it. 8 bit works fine. Down to 60 KB for both images. Could of course just skip these, was more like a "if we're going that far…" addition. :)

**Comment by eXpl0it3r** [comment]
This is outdated.

I'm not sure I really see the use-case for this. When exactly do you want an installer just to install some SFML DLLs?

**Comment by binary1248** [comment]
In a perfect world, the installer would also make sure you don't have to do anything else to get SFML up and running on your development machine. This includes adding the necessary templates to IDEs, setting up environment variables, adding shortcuts to e.g. the examples directory, being able to easily reverse the changes i.e. uninstall whatever version you installed.

It would be a nice addition, not necessarily essential, and considering that more and more package managers are becoming available maybe at some point no longer relevant, but none the less still a stop-gap solution for now.

**Comment by eXpl0it3r** [comment]
Resolved merge commit and rebased onto master.

This PR adds:
- Add CPack support
- Add additional configurations for NSIS

While I believe NSIS isn't necessarily needed, CPack support might be quite useful and might be integrated/utilized in CI setups.

**Review by binary1248 — APPROVED** [review]

**Pull request merged**
