### PR TITLE
Loosen restrictions on unrecognized compilers

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

A core tenet of CMake is the idea that you can use any valid C++ compiler. By enumerating all supported compilers and emitting and hard error when an unrecognized compiler is detected, we are violating that tenet.

Relaxing this message from a fatal error to merely a warning continues to communicate to users that their build may not succeed but it leaves the door open for the build to potential succeed if the compiler meets all of our requirements.

Partially addresses #2583

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Alternatively we can entirely remove that `else()` block since most CMake projects I've seen simply don't do this kind of compiler detection logic in the first place. It's not necessarily warning-worthy to use an unrecognized compiler. There are other popular compilers than MSVC, GCC, and Clang (and their variants).

**Comment by ChrisThrasher** [comment]
@VictorEijkhout Would you please test this PR and let us know to what extent it fixes your issues with Intel compilers?

**Comment by VictorEijkhout** [comment]
```cmake -D CMAKE_INSTALL_PREFIX=/work2/00434/eijkhout/sfml/installation-sfml-git-clx-intel23                                           -D CMAKE_VERBOSE_MAKEFILE=ON                     -D BUILD_SHARED_LIBS=TRUE                     /work2/00434/eijkhout/sfml/sfml-git
-- The C compiler identification is IntelLLVM 2023.1.0
-- The CXX compiler identification is IntelLLVM 2023.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/compiler/2023.1.0/linux/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2023.1.0/linux/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/Config.cmake:134 (message):
  Unrecognized compiler: IntelLLVM.  Use at your own risk.
```

and then 

```
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- UDev not found.
```

but that's my problem, not yours, I'm guessing.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/actions/runs/5349006137/jobs/9699625624

I was able to add an Intel oneAPI CI job to 2.6.0 and it passes so I'm hopeful you should be able to make this work as soon this PR gets merged. There could still be lingering issues since I'm not sure if this compiler is binary compatible with the Ubuntu packages we're linking against that assume the GCC ABI. That much will require further testing.

**Review by eXpl0it3r — APPROVED** [review]

**Pull request merged**
