### PR TITLE
Mac External Frameworks Info.plist Update for AppStore Validation

### PR DESCRIPTION
**Pull request by kipbits**
Sorry for previous confusion. 
I added some lines defining CFBundleSupportedPlatforms to all the Info.plist for mac external frameworks. This allows a project using those frameworks to pass validation phase on submit to the app store review. this is related to [issue 1020](https://github.com/SFML/SFML/issues/1020) based on the forum thread [[SOLVED]Mac App Upload Error: (freetype)](http://en.sfml-dev.org/forums/index.php?topic=19498.msg140542#msg140542).

### CODE REVIEW

**Comment by kipbits** [comment]
sorry for original confusion

**Comment by Bromeon** [comment]
We tell you 7 pull requests is exaggerated, and as a result, you create an 8th? :neutral_face: 

You can edit your pull requests after you created them. Please make use of this, it makes things more difficult for everyone if the same feature/bugfix is spread about so many issues and pull requests. It would be nice if you created only a single issue/PR in the future, not 8. Please also read our [Contribution Guidelines](http://www.sfml-dev.org/contribute.php) beforehand to check whether it is actually appropriate.

**Comment by kipbits** [comment]
This PR encompasses all 7 previous PR's. Sorry again. I'm a newB. Now I know

**Comment by mantognini** [comment]
Could you squash everything into one commit and update this PR? Thanks.

**Comment by kipbits** [comment]
oops, a minute

**Comment by kipbits** [comment]
having trouble finding the options for consolidating commits. I'll have a look at it again in the morning

**Comment by Bromeon** [comment]
You can use `git rebase -i` for interactive rebasing, then you can choose what do do with every commit (-> squash). If you have a GUI such as TortoiseGit, you can also combine all the commits with 2 clicks.

**Comment by kipbits** [comment]
OK, I started from the begging and made a new PR: https://github.com/SFML/SFML/pull/1036

**Comment by Bromeon** [comment]
Thanks for repeatedly ignoring the advice regarding the creation of useless PRs.

**Pull request closed without merging**
