### PR TITLE
Fixed XK_* inconsistency in InpuImpl.cpp

### PR DESCRIPTION
**Pull request by eXpl0it3r**
As discussed [here](https://github.com/SFML/SFML/pull/910#issuecomment-129477066) I seem to have changed the wrong values when rebasing @mickelson's code.

Thanks @Hapaxia for spotting it and pointing it out!

### CODE REVIEW

**Comment by TankOs** [comment]
:+1: :cat2:

**Comment by binary1248** [comment]
:+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon into the 2.3.x branch, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
We noticed some more inconsistency with the `XK_*` codes. It's not that important since it's just about the keys and not about the actual values.

**Comment by silverweed** [comment]
Just so you know: on Debian 8.0 it appears the numpad keys are mapped to `Key::NumpadX` only when the Numlock is *OFF*, otherwise it's still "Unknown". Gonna test on my other Linux machine asap, but I expect the same behaviour.

**Comment by aubade** [comment]
I can confirm the same results as silverweed. The Numpad keys only work when numlock is turned off.

**Pull request merged**
