### PR TITLE
Bump macOS requirements for unstable

### PR DESCRIPTION
**Pull request by mantognini**
In order to use C++14 at least 10.9 is required.

Let's see if this build on all OSes... :-)

### CODE REVIEW

**Comment by mantognini** [comment]
SFMLBuildMaster: Build this please.

**Comment by mantognini** [comment]
Hum.. any idea why the CI doesn't start? Is it related to the outdated certificate for ci.sfml-dev.org, or is it a setting issue with buildbot itself?

**Comment by binary1248** [comment]
I went ahead and cherry picked these commits onto a cleaned up unstable. Just experiment around with unstable to your liking... it will need cleaning up every now and then anyway.

**Comment by mantognini** [comment]
Seems like the build for mac are now successful. Good. :-)

**Pull request closed without merging**
