### PR TITLE
Window/Unix: fix SFML issue #1228, getPosition() returns incorrect results on Linux

### PR DESCRIPTION
**Pull request by llongi**
Fixes SFML issue #1228, getPosition() returns incorrect results on Linux depending on the used WM, as well as not returning values that are in-sync with what was given to setPosition(x, y).

See https://github.com/SFML/SFML/issues/1228#issuecomment-323557761 for a complete description of current patch, as well as testing results comparing current approach to approach in patch for over 20 different window managers.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
It's a huge work that you've done, many thanks.

I'm not a X11/WM expert, so here is my only comment: some parts or your patch don't follow our [coding guidelines](https://www.sfml-dev.org/style.php), you should fix them before we can merge your work.

**Comment by eXpl0it3r** [comment]
Can you squash the two commits?

**Comment by llongi** [comment]
Squash done.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
Merged in 58b7c2c48a7aa6eef1160862fb1805fedd33818f 🎉

**Pull request closed without merging**
