### PR TITLE
Added functionality to allow polymorphism with sf::SoundSource

### PR DESCRIPTION
**Pull request by JonnyPtn**
following on from #1094, which I stupidly had pulling from my master. Now pulling from it's own branch.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by Foaly** [comment]
What happened here? After the build servers are notified again I think this can be merged.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
Merged in e31b925234676472f2705f8cfe0dc46901518929

**Pull request closed without merging**
