### PR TITLE
Added a wrapper class for angles

### PR DESCRIPTION
**Pull request by MarioLiebisch**
`sf::Angle` works in a similar way to `sf::Time` providing conversion between radians and degrees in addition to basic mathematical operands.

Angles are always normalized to provide values within _[0, 360[ deg_ resp. _[0, 2 PI[ rad_.

In addition, there's a constructor taking a floating point value to provide backward compatibility with existing source code.

Right now conversion offers radians as well as degrees, although I could imagine adding [some more units](http://en.wikipedia.org/wiki/Angle#Units), such as _grads_ or _seconds of arc_.

### CODE REVIEW

**Comment by binary1248** [comment]
Bump.

So is this still up for discussion? Or are we just going to roll this into the new SFML 3 API?

**Comment by eXpl0it3r** [comment]
I'd delay it for SFML 3.

**Comment by mantognini** [comment]
Me too.

**Comment by LaurentGomila** [comment]
Yup.

**Comment by zsbzsb** [comment]
I agree.

**Comment by mantognini** [comment]
Closing PR since we decided to delay it for a very long time. =P

**Comment by Foaly** [comment]
I'd still keep it open though, so it's not forgotten. I would find this little helper very useful.

**Comment by eXpl0it3r** [comment]
Yes, I think that's what we usually agreed to. Either create an issue for this or keep the PR open as "issue", so we don't forget once we get there...

**Comment by Bromeon** [comment]
I created a new milestone **3.x** and assigned it.

**Comment by ChrisThrasher** [comment]
I’m here from the far future of 2022 where SFML 3.0 development is in full swing. Do we want to resurrect this PR and get it rebased on master? I really like the idea of `sf::Angle` and want to see what a full implementation would look like. I can write unit tests for it too.

**Comment by Bromeon** [comment]
While this is an exciting feature in terms of type safety, I wonder whether this improves ergonomics in practice? I looked into this lately for godot-rust (see above for issue linking here):

> From a short research, [Ogre](https://www.ogre3d.org/docs/api/1.9/class_ogre_1_1_angle.html) is the only game engine I found with an `Angle` class.
Godot (GDScript, C#, C++), Unity, Unreal, Torque3D, HaxeFlixel, Löve2D seem to use floats. Not entirely sure if everyone uses radians (e.g. SFML and I think SDL use degrees by default).

Of course we should not blindly follow the industry, especially not gamedev which is notorious for the wrong design choices. Yet one thing to consider is that most engines/libraries just stick to one convention and call it a day.

In other words, I'm not sure if using radians instead of degrees in SFML would be a source of errors that would justify
```cpp
sprite.rotate(sf::Angle::degrees(30.f));
```
instead of:
```cpp
sprite.rotate(30.f);
```

Probably, user defined literals could help here. However, they cannot be used when the numbers come from other sources (2D physics, serialized formats, user input, network, ...).

What I'm also a bit worried about, is that this could significantly increase the number of conversions needed in SFML code, _in addition_ to the noise we already have due to `static_cast` proliferation. A PR might be the only way to find out, but I don't want people to do a lot of work which may not be merged eventually. Maybe we could refactor only a small part of the API to see how it would look?

**Comment by JekiTheMonkey** [comment]
> In other words, I'm not sure if using radians instead of degrees in SFML would be a source of errors that would justify
> 
> ```c++
> sprite.rotate(sf::Angle::degrees(30.f));
> ```
> 
> instead of:
> 
> ```c++
> sprite.rotate(30.f);
> ```
I think we should follow the `sf::Time` design for this since `sf::Angle` class has to perform similar task. So the first option should be the right way, but it has to be changed a bit. 

To create a temporary `sf::Time` object `sf::seconds`, `sf::milliseconds` and `sf::microseconds` functions are used, they are not in the `Time`'s namespace, so the `degrees` and `radians` functions should be also wrapped only in `sf` namespace. So as the result a temporary `degrees` or `radians` objects would be created with following functions - `sf::degrees` and `sf::radians`.

**Comment by vittorioromeo** [comment]
Also, good opportunity for UDLs. E.g. 

```c++
sprite.rotate(30.f_deg);
```

**Comment by ChrisThrasher** [comment]
I've finished implementing this in #1969 including `constexpr` support and user defined literals for radians and degrees.

**Comment by eXpl0it3r** [comment]
Superseded: #1969

**Pull request closed without merging**
