### PR TITLE
Android: Updated the example to build with gradle

### PR DESCRIPTION
**Pull request by MarioLiebisch**
This PR is mostly for visibility and you should consider it a work in progress.
It basically addresses #1311 and supercedes/includes #1315.

This updates the Android example to use Gradle rather than Ant for building.

To configure the example, simply run `gradle`. To build it, run `gradle build`, and to install it, run `gradle installDebug` or `gradle installRelease`.

Here are some known and so far not fixed issues (at least on my Nexus 5), but I don't think they're actually demo project related:

- Loading `canary.wav` fails for me.
- Once you switch to another app, the EGL context is no longer valid/restored.
- There's something broken with loading the shared STL libraries.

Feedback and bugfixes are appreciated, I'm really short on time right now. :(

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
I assume this isn't SFML 2.5 ready, right? Will you find time anytime soon, to get it ready?

**Comment by eXpl0it3r** [comment]
@MarioLiebisch The CI build failed. Anything that needs to be update on the CI or with this branch?

**Comment by binary1248** [comment]
Is there a tutorial or step by step guide for this somewhere? 😛

**Comment by MarioLiebisch** [comment]
It's really just that. Get Gradle, standalone or by using npm, and invoke it for everything:

    cd path/to/example
    npm install -g gradle
    gradle release

**Comment by binary1248** [comment]
There... after 2 hours of trial and error it actually builds. Better merge this quick since all other branches will fail to build on Android now. 😁

**Comment by texus** [comment]
If I run `gradle release` then it gives the error `Task 'release' not found in root project 'android'` (same for debug). Using `gradle build` and `gradle installDebug` did work.

In order to build for x86 I also had to edit app/build.gradle as it has the armeabi-v7a hardcoded.

Gradle also doens't seem to run in my gnome-terminal, I had to run it using xterm or add `TERM=dumb` before the command. Otherwise it would complain about not being able to get the termcap entry.

I haven't gotten the apk to actually run without crashing, but I'll just wait with that until SFML 2.6, hopefully things will be more stable by then.

**Comment by MarioLiebisch** [comment]
ah, sorry, yeah, the correct/valid targets are `build`, `buildDebug`, and `buildRelease` (plus `install` variants.).

**Comment by MarioLiebisch** [comment]
Hm yeah, haven't touched it for too long it seems. For some reason there's a target `build`, but not `buildRelease` or `buildDebug`. There's `assemble` for all three though.

**Comment by eXpl0it3r** [comment]
@MarioLiebisch Can you check why this fails? https://ci.sfml-dev.org/#/builders/12/builds/143

**Comment by MarioLiebisch** [comment]
Patching fails due to missing file or file permission. No idea, but that's not really related to the changes from what I can see.

**Comment by binary1248** [comment]
It was still based on a revision before this PR was merged. Can be safely ignored.

**Comment by MarioLiebisch** [comment]
If that's not the issue, what's the output of `gradle tasks`?

**Comment by binary1248** [comment]
Whatever it is supposed to be. 😁

All the other branches based off a revision after this PR build correctly, so no need to invest more effort here.

**Comment by MarioLiebisch** [comment]
Ah okay, so it was really just that patching issue then. Fine with me. :D

**Comment by eXpl0it3r** [comment]
Ah sorry didn't think it through properly 😄

**Pull request merged**
