### PR TITLE
Back-merge changes from 2.6.x to master

### PR DESCRIPTION
**Pull request by eXpl0it3r**
## Description

Bring additional changes merged onto the 2.6.x branch to the master branch

## Testing

CI should be enough to confirm the success or failure

### CODE REVIEW

**Comment by Bromeon** [comment]
Nice, thank you 🙂 

Is this a merge commit, or simply cherry-picked commits applied on `master`? I don't see it in the Git web UI.

**Comment by eXpl0it3r** [comment]
It's a merge commit. We did cherry-picking last time with 2.5.x and it was kind of annoying to do, plus you end up with two different commits that are hard to link back.
In this case, merging and merge commits really are the right tool for the job IMHO.

**Review by vittorioromeo — APPROVED** [review]

**Comment by vittorioromeo** [comment]
LGTM, you have some conflicts to solve @eXpl0it3r :)

**Comment by eXpl0it3r** [comment]
❌ ❌ ❌ ❌

**Comment by eXpl0it3r** [comment]
We should always merge backmerges first before moving the target branch, because you can't rebase those...

**Pull request merged**
