### PR TITLE
Change comment chars in FindSFML.cmake to #

### PR DESCRIPTION
**Pull request by r0mai**
So they can be copy-pasted without change

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Good catch :+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in fb40e7e43feba13378d11658540c636e47e4389d

**Comment by r0mai** [comment]
Thank you!

**Pull request closed without merging**
