### PR TITLE
Android: Copy the selected EGL context's settings to SFML

### PR DESCRIPTION
**Pull request by MarioLiebisch**
This fixes the bug described in [this forum thread](http://en.sfml-dev.org/forums/index.php?topic=19620.0).

In short, SFML picks a matching OpenGL ES context config, but won't copy that information back to it's internal `sf::ContextSettings` object for querying.

*Open for comments and review/testing.*

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Looks good.

However this file would really need some cleaning... I'll post comments here, I'm not sure it deserves a separate PR.

**Comment by LaurentGomila** [comment]
```cpp
     // On Android, its native activity handles this for us
     sf::priv::ActivityStates* states = sf::priv::getActivity(NULL);
     sf::Lock lock(states->mutex);
 
     return states->display;
```
-> Misses one level of indentation

```cpp
 EglContext::EglContext(EglContext* shared) :
 m_display (EGL_NO_DISPLAY),
 m_context (EGL_NO_CONTEXT),
 m_surface (EGL_NO_SURFACE),
 m_config  (NULL)
```
-> Useless empty space between member names and (

```cpp
    EGLint attrib_list[] = {
```
-> { should be under

```cpp
#if !defined(SFML_SYSTEM_ANDROID)
    // Create EGL surface (except on Android because the window is created
    // asynchronously, its activity manager will call it for us)
    createSurface((EGLNativeWindowType)owner->getSystemHandle());
#endif
```
-> Needs some empty space :)

```cpp

    if (currentContext == m_context)
    {
        eglCheck(eglMakeCurrent(m_display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT));
    }

    // Destroy context
    if (m_context != EGL_NO_CONTEXT)
    {
        eglCheck(eglDestroyContext(m_display, m_context));
    }

    // Destroy surface
    if (m_surface != EGL_NO_SURFACE)
    {
        eglCheck(eglDestroySurface(m_display, m_surface));
    }
```
-> All these { } should be removed

```cpp

    EGLContext toShared;

    if (shared)
        toShared = shared->m_context;
    else
        toShared = EGL_NO_CONTEXT;

    // Create EGL context
    m_context = eglCheck(eglCreateContext(m_display, m_config, toShared, contextVersion));
```
->
`m_context = eglCheck(eglCreateContext(m_display, m_config, shared ? shared->m_context : EGL_NO_CONTEXT, contextVersion));`

**Comment by MarioLiebisch** [comment]
I'd say let's skip the cleanup for now. As mentioned in the added comment, I don't think parts of the current implementation are ideal (but it's unrelated to this bug; e.g. I think matched configs are not sorted), so there might be even more changes than just that formatting.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by TankOs** [comment]
@MarioLiebisch himself raised a concern. ;)

**Comment by MarioLiebisch** [comment]
@TankOs Nah, it's fine. While still not perfect as a whole, this PR fixes a clearly broken feature that is only related to the potentially weird context selection. We've got two bugs here (one unconfirmed), so nothing wrong in fixing this one first.

**Comment by TankOs** [comment]
Ah alright, got it wrong then.

**Pull request merged**
