### PR TITLE
Increased version to 2.3 and updated the changelog.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Needs to be updated as soon as everything is merged. In the mean time feel free to point out stuff that I missed to update.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
:+1:

**Comment by zsbzsb** [comment]
readme.txt still has links pointing at 2.2 tutorials, I am assuming you probably want to update those ;)

**Comment by eXpl0it3r** [comment]
Thanks! I forgot them last time already. :wink:

**Comment by LaurentGomila** [comment]
Maybe we could create a redirection from the latest release to a more generic URL (like "http://www.sfml-dev.org/tutorials/2" or even "http://www.sfml-dev.org/tutorials/latest") so that we don't have to update the readme everytime; would also be better for search engines I guess.

**Comment by mantognini** [comment]
I agree. This could also be useful for documentation/download links.

**Comment by eXpl0it3r** [comment]
It has come up before and I'm generally for it. The only problem I see, is that if people post these generic links when talking about a specific version it might cause confusion. Then again if it's a redirect people copying from the address bar won't post it too often.

**Comment by MarioLiebisch** [comment]
Just force a visible redirect first, i.e. not just an alias so the address bar points to the specific version immediately?

**Comment by eXpl0it3r** [comment]
That's what would happen, thus I said it's probably less of an issue. :wink:

**Comment by eXpl0it3r** [comment]
Is this branch missing anything?

**Comment by binary1248** [comment]
:+1:

**Comment by mantognini** [comment]
Looks okay – change log for 2.1 doesn't use tags (e.g. [Linux], [OS X], ...) but that should **not** delay us further. :dragon_face:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by mantognini** [comment]
:tada: :smiley: 

@DomT4 Do you plan to update the brew formula? In that case, please note that we are now no longer relying on libsndfile but rather ogg, flac and vorbis. Also on OS X we don't use the default OpenAL shipped by Apple. (The changelog has a comprehensive list of important changes.)

**Pull request merged**
