### PR TITLE
Clarify documentation on Rect::contains function bounds

### PR DESCRIPTION
**Pull request by Mischa-Alff**
Add documentation clarifying that points on a Rect's "border" will not be considered as if they were contained by the Rect.

Perhaps this behaviour could be changed? Or another function could be added? For now this should suffice.

Thanks

### CODE REVIEW

**Comment by mantognini** [comment]
I guess this doesn't hurt, even though *inside* means in it, so excluding the border (at least according to my understanding of the word).

> Perhaps this behaviour could be changed?

Probably not, otherwise we can't properly handle zero-sized rectangles.

**Comment by MarioLiebisch** [comment]
Big question for me would be whether "on the border" is even that accurate to answer with floating point inaccuracies. Same for intersections: Don't have time to check right now, but do both exclude the edges? IMO it would be a lot more natural to simply include the edges in both cases (as far as possible).

**Comment by Mischa-Alff** [comment]
Context: Someone complained about this not being more explicit and refused to do a PR, so I filmed myself making this one in 3 minutes to prove how easy it was.

However, I do agree that such functions should be more explicit in explaining whether they are inclusive or exclusive to their bounds.

As for floating point inaccuracies: that's a valid point, but I don't think it's too important either.

Not having it include the border prevents the classic case of calculating a point that *should* be on the border but due to floating point inaccuracies is slightly off. Including the border just makes floating point inaccuracies a "fact of life". Most of these algorithms that I have seen don't care for floating point issues and leave it up to the user to make sure their input is as they want it.

Plus, the classic solution of using an epsilon could lead to unwanted behavior for smaller numbers. Perhaps we could add an epsilon that is passed as an optional argument to each function?

We could also just simply change the code to use `>=` or `<=` for comparisons, or add functions that are inclusive to the border, and not care about floating point inaccuracies or any related problems.

**Comment by MarioLiebisch** [comment]
I'd vote for changing the behavior to include the edges, simply due to the fact noone uses a rectangle to see whether some point is on the outline. The typical use case would be inside. If one really wanted to check the outline, they'd most likely use a different approach or a second, rectangle to actually get an area rather than a direct line.

**Comment by Mischa-Alff** [comment]
In any case, the purpose of this PR is not to change the implementation of the `.contains` functions. It is to improve SFML's documentation.

Perhaps this discussion could be moved to a separate PR so we can focus on adding 6 lines of comments to SFML's source code?

Besides, any changes in SFML's implementation of the `.contains` functions cannot be merged until SFML 3 because of backwards compatibility. For now, better documentation is surely enough.

**Comment by MarioLiebisch** [comment]
Yeah, true, considering the current state isn't ideal, just get this one merged first.

**Comment by mantognini** [comment]
@Mischa-Alff  Could you squash the commits into one? :-)

**Comment by MarioLiebisch** [comment]
That can be done when merging, so no longer has to be done manually.

**Comment by eXpl0it3r** [comment]
> That can be done when merging, so no longer has to be done manually.

Except we don't use the merge button and everything is done manually...

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in 2fca58591e4acf33e5371f1eede7426d2b5f6a04 on branch 2.4.x.

**Comment by Hapaxia** [comment]
I do not think that this new documentation is correct.

Firstly, it states that "\[i\]f the point lies on the border of the rect, this function will return false", which is incorrect as both minX and minY are also compared with equality.

Secondly, the concept of the rectangle is not defined by its borders/edges and therefore there is no opposite edge. The width and height clearly define the amount of area that is included. The "max" variables used in the implementation of contains are not exposed.

Example:
If a rectangle is at (0, 0) and has a width of 10x10, it clearly does contain a point at (0, 0) and is not large enough to cover a point at (10, 10).
This also shows my first point above that the point can be on the edge of the position of the rectangle (most commonly the top-left).

**Pull request closed without merging**
