### PR TITLE
Prevent constructing `sf::Text` with a temporary `sf::Font`

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

By deleting this constructor overload, it fails to compile if you pass a temporary font to this parameter slot. That includes code like

```cpp
  sf::Text text("", sf::Font());
```

but more importantly it prohibits code like this

```cpp
  sf::Font getFont()
  {
    sf::Font font;
    // load a font...
    return font;
  }

  sf::Text text("", getFont());
```

Credit to @JonnyPtn for the idea.

---

We ought to copy this idea to other APIs that do similar things taking the address of a const reference.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by kimci86** [comment]
Nice, the same idea could be used for Sprite and Sound constructors too.

About "Co-authored-by", I think it needs to be at the end of the commit message if this blog post is still accurate https://github.blog/2018-01-29-commit-together-with-co-authors/#how-it-works.

**Comment by kimci86** [comment]
I just realized `= delete` can be used on any method, not only constructors or special methods.
So this approach could be applied to `setFont` too to make it safer.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
> Nice, the same idea could be used for Sprite and Sound constructors too.

https://github.com/ChrisThrasher/SFML/tree/lifetime_safety

I also found somewhere in `sf::Shader` where this trick would come in handy.

**Review by JonnyPtn — APPROVED** [review]

**Pull request merged**
