### PR TITLE
Fixes a bug where vorbis can't handle large buffers.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
This fixes the issue reported in [this forum thread](http://en.sfml-dev.org/forums/index.php?topic=19907.0).

### CODE REVIEW

**Comment by binary1248** [comment]
:+1:

**Comment by mantognini** [comment]
I can confirm both the bug and it fix. :+1: 

The PR's style however need a tiny bit of freshening:
 - missing space after `for` and `while` keywords
 - I would personally write `static const int` instead of `const static int`; I don't know if we decided anything on that, though.

**Comment by eXpl0it3r** [comment]
Added the spaces and since there are 3 occurrences of `static const int` and no occurrences of `const static int` I change it around as well.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
