### PR TITLE
Update Catch2

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

https://github.com/catchorg/Catch2/releases/tag/v3.5.1

### CODE REVIEW

**Review by eXpl0it3r — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
The MinGW Shared Release tests are consistently crashing in the `sf::SoundFileFactory` and `sf::InputSoundFile` jobs. I'm not sure what the cause is. I'll try to find someone who can reproduce this locally and provide a stack trace.

**Comment by vittorioromeo** [comment]
I cannot reproduce the crash locally. Rebased on `master` and trying again...

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by vittorioromeo** [comment]
Cannot reproduce locally with MSYS2 + MinGW and `cmake --preset dev -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_USE_MESA3D=TRUE -DCMAKE_CXX_COMPILER=g++ -GNinja -DBUILD_SHARED_LIBS=TRUE` as the CI does. Investigating the tests... Any chance for a MinGW upgrade on our CI?

**Comment by ChrisThrasher** [comment]
> Any chance for a MinGW upgrade on our CI?

I'm cool with upgrading our MinGW version in CI. If that fixes this crash then I'm fine merging this PR. I've already spoken with the Catch2 maintainer about this and he has no idea what's going on so we shouldn't expect an upstream fix anytime soon, if such a fix is even possible.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
By the way you don’t need manually trigger the extended CI pipeline for PRs that don’t come from a fork as is this PR.

**Comment by vittorioromeo** [comment]
@ChrisThrasher: so I played around with `SoundFileFactory` because I suspected that the `inline static` or the registration boolean was getting screwed up somehow (MinGW bug? Catch2 bug? Some hidden multithreading when running tests?) and it seems that my changes fixed the tests.

What I've basically done was remove dynamic registration of readers/writers, and just return a Meyers' Singleton instead. 

I've looked throughout GitHub and there's only one occurrence of someone using the dynamic registration -- is this something we want to support at all?

**Comment by vittorioromeo** [comment]
Rebased on https://github.com/SFML/SFML/pull/2899, let's see if it does the trick

**Pull request merged**
