### PR TITLE
Rewrite RenderWindow::capture

### PR DESCRIPTION
**Pull request by binary1248**
Implements what was discussed here: http://en.sfml-dev.org/forums/index.php?topic=19260.0

### CODE REVIEW

**Comment by LaurentGomila** [comment]
It makes this function look rather useless now. It would be more efficient for users to have their texture and just call update + copyToImage whenever they want to capture the window :stuck_out_tongue:

More seriously, is the performance improvement something that we're sure of? On all kind of platforms/drivers?

**Comment by eXpl0it3r** [comment]
Old (Release) [µs]:

Old

New (Release) [µs]:

New

Code used:

```cpp
#include <SFML/Graphics.hpp>
#include <iostream>
#include <vector>

int main()
{
    sf::RenderWindow window({1024, 768}, "Test");
    window.setFramerateLimit(60);

    sf::Clock cl;
    std::vector<sf::Time> times;

    while(window.isOpen())
    {
        sf::Event event;
        while(window.pollEvent(event))
        {
            if(event.type == sf::Event::Closed)
            {
                window.close();
            }
            else if(event.type == sf::Event::KeyPressed)
            {
                if(event.key.code == sf::Keyboard::Escape)
                {
                    double average = 0.;
                    for(auto t : times)
                        average += t.asMicroseconds();
                    average /= times.size();
                    std::cout << "AVG: " << average << "\n";
                }
                else
                {
                    cl.restart();
                    sf::Image img = window.capture();
                    sf::Time time = cl.getElapsedTime();
                    times.push_back(time);
                    std::cout << time.asMicroseconds() << "\n";
                }
            }
        }

        window.clear();
        window.display();
    }
}
```

> On all kind of platforms/drivers?

Feel free to test on all the other platforms and drivers...

**Comment by LaurentGomila** [comment]
> Feel free to test on all the other platforms and drivers...

That's not what I meant. The question was more "*is this a known technique that we can rely on, or something that we're trying*".

> Speed up: 1383%

That's huge! :smiley:
Would be interesting to run the same test, but with a pre-allocated texture and just calling update + copyToImage in the loop. If there is a significant difference, maybe we could just deprecate the function and advise to use Texture::update directly?

**Comment by eXpl0it3r** [comment]
> is this a known technique that we can rely on, or something that we're trying

Why shouldn't it be?

> maybe we could just deprecate the function and advise to use Texture::update directly?

If we deprecate the function, I'd still change the implementation, nobody will lose anything.

> we should not merge this until it is tested properly on mobile platforms, where Texture::copyToImage is implemented differently.

The mobile platforms are still experimental. Sure it's nice if we can test the change as soon as possible, but it should not be a reason to hold back the merge.

**Comment by zsbzsb** [comment]
>If we deprecate the function, I'd still change the implementation, nobody will lose anything.

:+1:

**Comment by eXpl0it3r** [comment]
Mark it as deprecated?
* [ ] Yes
* [ ] No

**Comment by binary1248** [comment]
* [X] Yes
* [ ] No

**Comment by LaurentGomila** [comment]
:+1:

**Comment by binary1248** [comment]
Rebased onto master and added `SFML_DEPRECATED`.

**Comment by eXpl0it3r** [comment]
You should add the `\deprecated` to the header documentation and briefly explain what to use instead.

**Comment by binary1248** [comment]
Fixed.

**Comment by MarioLiebisch** [comment]
**Android 6.0 - armeabi-v7a - Nexus 5**

Avg. *master*: 718866
Avg. *feature/capture*: 173961

**Comment by Bromeon** [comment]
Has anybody checked whether compilers are able to apply RVO here?

I'm asking because there are still quite a few lines of code necessary to achieve the same behavior as `RenderWindow::capture()`, and quite a few error sources (like forgetting to set the size before calling `update()`). If we reduce the usability of taking screenshots, we should not deprecate this function in my opinion.

**Comment by LaurentGomila** [comment]
> Has anybody checked whether compilers are able to apply RVO here?

Even if they do, there's still the unnecessary creation of a texture every time the function is called.
And if they don't, it will be "fixed" in SFML 3 when sf::Image supports move semantics.

> there are still quite a few lines of code necessary to achieve the same behavior as RenderWindow::capture()

Two lines of code, plus one other in the Resized event handler. If someone requested a new functon to replace 3 lines of user code, I think we all know what the answer would be ;)

If we keep this function, people will just use it and never wonder if they can do something better themselves. And everytime someone asks on the forum about the most efficient way to take a screenshot, we'll say "don't use capture(), use this code instead".

If we deprecate it, the most efficient code will be clearly mentioned in the doc and tutorials, and people will quickly get used to it without being confused by this capture() function.

**Comment by Bromeon** [comment]
> Two lines of code, plus one other in the Resized event handler. If someone requested a new functon to replace 3 lines of user code, I think we all know what the answer would be ;)

It's more than that. The user has to keep both a `sf::Image` and `sf::Texture` instance around, react to events and know how 3 classes interact. It's not a big deal, but still rather complicated for somebody who may only be interested in taking a screenshot once :wink:

And I still don't know about the `setActive()` call. Is it needed for correctness? If not, why does `capture()` have it?

> On the other hand, if we deprecate it, the most efficient code will be clearly mentioned in the doc and tutorials and FAQ, and people will quickly get used to it without being confused by this capture() function.

If we clearly document it, okay. I think we should even include such a code in the `RenderWindow::capture()` documentation, to make the transition easier.

**Comment by LaurentGomila** [comment]
> The user has to keep both a sf::Image and sf::Texture instance around

Just the texture.

> react to Resized events

He can also compare the size every time he takes a screenshot, so all the code is kept at the same place and doesn't involve events.

> and know how 3 classes interact

He just needs to know 2 functions, which are (or will be, if not) properly documented and explained in the tutorials.

> And I still don't know about the setActive() call. Is it needed for correctness? If not, why does capture() have it?

setActive is only needed for raw OpenGL calls. So it's not needed anymore with the new implementation (Texture::update correctly calls it).

> If we clearly document it, okay. I think we should even include such a code in the RenderWindow::capture() documentation, to make the transition easier.

:+1:

**Comment by Bromeon** [comment]
:+1: if we add some transition code to the deprecated function's documentation. And so we can remove `setActive()` from this PR, right?

**Comment by LaurentGomila** [comment]
> And so we can remove setActive() from this PR, right?

Yes, unless I'm missing something.

**Comment by binary1248** [comment]
Fixed.

**Comment by eXpl0it3r** [comment]
Looks good!

docs

**Comment by mantognini** [comment]
Ignore the build failure for OS X... I'll have to look into why it fails but it's most certainly not related to this PR.

:+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
