### PR TITLE
Fixed texture edge clamp extension not being detected properly

### LINKED ISSUE #880: "SGIS_texture_edge_clamp unavailable" but "GL_EXT_texture_edge_clamp: OK"
OpenGL extension SGIS_texture_edge_clamp unavailable
    Artifacts may occur along texture edges

Many people seem to be getting this warning now. And I have indeed noticed artifacts along texture edges, but the same happened in older versions. As I understand it, the problem was always there, just that the warning message appeared only in SFML 2.3. 

I have this on an old NVIDIA graphics card, other people reported the same on new ones.

And the thing is...

```bash
glewinfo | grep texture_edge_clamp
```

    GL_EXT_texture_edge_clamp:                                     OK 
    GL_SGIS_texture_edge_clamp:                                    MISSING 

Some graphics cards seem to have this feature under a different name. It may be worth adding a fallback like this.

### PR DESCRIPTION
**Pull request by binary1248**
Fixes #880

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
FYI: The MSVC builds only failed because I accidentally turned my PC off too early.


@BlaXpirit could you test this and give feedback on it?

**Comment by BlaXpirit** [comment]
Everything seems to work, the warning is gone. Don't know what else I could test...

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged into 2.3.x soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in 45577de60a172cd1c92a278320688736134a0ed1 on branch 2.3.x

**Pull request closed without merging**
