### PR TITLE
Fix wrong types passed to XChangeProperty

### LINKED ISSUE #1168: sf::Window:setIcon causes segfault on Linux
Using sf::Window::setIcon leads to a segfault on Linux. This [example](https://gist.github.com/mstraube/a557ee06660fc95aa7a374f641fc27ce) gives following gdb output:
```
Reading symbols from ./sfml...done.
(gdb) r
Starting program: /home/john/sfml/sfml 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffecdb4700 (LWP 28918)]
[New Thread 0x7fffec3ae700 (LWP 28919)]
[New Thread 0x7fffebbad700 (LWP 28920)]
[New Thread 0x7fffeb3ac700 (LWP 28921)]
[New Thread 0x7fffeabab700 (LWP 28922)]
Success loading icon.png

Thread 1 "sfml" received signal SIGSEGV, Segmentation fault.
0x00007ffff6082c50 in _XData32 () from /usr/lib/libX11.so.6
(gdb) bt
#0  0x00007ffff6082c50 in _XData32 () from /usr/lib/libX11.so.6
#1  0x00007ffff605d683 in XChangeProperty () from /usr/lib/libX11.so.6
#2  0x00007ffff79752da in sf::priv::WindowImplX11::setIcon (this=0x7f3a40, width=256, height=256, 
    pixels=<optimized out>) at /build/sfml/src/SFML/src/SFML/Window/Unix/WindowImplX11.cpp:859
#3  0x000000000040151d in main () at sfml.cpp:20
(gdb) q
```
Seems 9996b7abb6c6e216dc40d527b0339c89880709c5 is the problem. I tested the last revision before that commit and it worked. Problem is also present in latest revision 746bb9c8cab04d44774ea1338c14f903cbaff3ae

I ran into this on x86_64 Arch Linux installation with sfml-2.4.1-1

### PR DESCRIPTION
**Pull request by binary1248**
Fixes #1168.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Could you elaborate? I can't find where your new code differs from the previous one, except on big-endian systems but I doubt this is the case in #1168.

**Comment by binary1248** [comment]
[`sizeof(long)` is 8 on LP64 systems](http://en.cppreference.com/w/cpp/language/types) (this includes Unix). Xlib was reading past the end of the allocated buffer because even though it only reads the low-order 32-bits out of each element, it still expects elements that are `sizeof(long)` large. Don't ask me why... it's Xlib.

**Comment by achpile** [comment]
tried bugfix/xlib_set_icon, crashes on XCreateImage (btw its call not affected by commit). building in steam runtime --i386 (https://github.com/ValveSoftware/steam-runtime).


```
#include <SFML/Graphics.hpp>

int main() {
	sf::Image *res = new sf::Image();
	res->loadFromFile("icon.png");

	sf::Window *win = new sf::Window(sf::VideoMode(800, 600), "test");
	win->setIcon(32,32,res->getPixelsPtr());

	delete res;
	delete win;
}
```

**Comment by achpile** [comment]
Wow, just tried one thing and it's not crashes anymore. 

```
    Uint8* iconPixels = static_cast<Uint8*>(std::malloc(width * height * 4));
    for (std::size_t i = 0; i < width * height; ++i)
    {
        iconPixels[8 + i * 4 + 0] = pixels[i * 4 + 2];
        iconPixels[8 + i * 4 + 1] = pixels[i * 4 + 1];
        iconPixels[8 + i * 4 + 2] = pixels[i * 4 + 0];
        iconPixels[8 + i * 4 + 3] = pixels[i * 4 + 3];
    }
```

here we have width * height * 4 array, but [8 + i * 4 + 0]. So 

`Uint8* iconPixels = static_cast<Uint8*>(std::malloc(width * height * 4 + 8));`

fixed crash

**Comment by MarioLiebisch** [comment]
Consider me confused.

**Comment by achpile** [comment]
btw this works too. so there's simple going out of array boundaries

```
    Uint8* iconPixels = static_cast<Uint8*>(std::malloc(width * height * 4));
    for (std::size_t i = 0; i < width * height; ++i)
    {
        iconPixels[i * 4 + 0] = pixels[i * 4 + 2];
        iconPixels[i * 4 + 1] = pixels[i * 4 + 1];
        iconPixels[i * 4 + 2] = pixels[i * 4 + 0];
        iconPixels[i * 4 + 3] = pixels[i * 4 + 3];
    }
```

**Comment by achpile** [comment]
I mean that the segfault can be caused by memory corruption after going out of boundaries and two issues caused by one problem

**Comment by MarioLiebisch** [comment]
Could you try this PR but replace `unsigned long` with `sf::Uint32`?

**Comment by mantognini** [comment]
> btw this works too. so there's simple going out of array boundaries

Question is: why is there this 8 padding in the first place? Some X-related format?

**Comment by achpile** [comment]
@MarioLiebisch in my case app crashed before any changes made in this commit. I got crash at line 789, but this commit starts at line 838. And there's obvious going out of boundaries.

the array is width*height*4, but last element in the loop accessed is
(8 + (width * height - 1) * 4) = 4 * (width * height - 1 + 2) = 4 * (width * height + 1), so next 8 bytes after the end of the array are overwritten by this.

**Comment by achpile** [comment]
@mantognini I think it's copy&paste from line 841

**Comment by MarioLiebisch** [comment]
@mantognini The offset skips the bytes used to store the image dimensions., 2 times 4 bytes.

**Comment by achpile** [comment]
@MarioLiebisch the offset is needed only here:

`// ICCCM also wants the first 2 unsigned 32-bit values to be width and height`

but not at the converting to BGRA.

**Comment by MarioLiebisch** [comment]
The offset is no longer there that way in the new commit.

Have to try that myself I guess. How do I set up the Steam Runtime?

**Comment by achpile** [comment]
@MarioLiebisch you're looking wrong way :) offset used 2 times. This commit removed second one.

https://github.com/SFML/SFML/blob/bugfix/xlib_set_icon/src/SFML/Window/Unix/WindowImplX11.cpp#L777

**Comment by achpile** [comment]
I'm sorry guys for lots of messages. So here's the last (i hope :) )

In the commit ca03b646efd042c6efd4a864f2608fc0bafafa99 iconPixels was expanded to (width * height * 4 + 8) and assignment in the loop was offset by 8.

After in commit 9996b7abb6c6e216dc40d527b0339c89880709c5 iconPixels' size was decreased back to (width * height * 4), but offset was left. So the bug is here.

@binary1248 thank you very much for returning to Xlib again. Yeah, that patch is huge, so it was easy to miss something

**Comment by binary1248** [comment]
Fixed.

**Comment by eXpl0it3r** [comment]
@achpile Can you give this a try again?

**Comment by achpile** [comment]
@eXpl0it3r i think there's no need to do it :) because I made same changes for steam release and it looks like it works fine :)

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
