### PR TITLE
Generate shape outline vertices only if necessary.

### PR DESCRIPTION
**Pull request by Foaly**
Improved the logic of the shape class so that the outline vertices are only updated if they exist.

Original, now abandoned #925

### CODE REVIEW

**Comment by Foaly** [comment]
This is a really small fix. @LaurentGomila @Bromeon would one of you guys mind reviewing? Thanks :)

**Comment by MarioLiebisch** [comment]
Don't forget to rebase it onto the current `master` branch.

**Comment by eXpl0it3r** [comment]
> Don't forget to rebase it onto the current `master` branch.

Doesn't really matter as long as there's no conflict. It just won't auto close. :wink:

**Comment by Foaly** [comment]
Thanks! I rebased to make it easier :)

**Pull request merged**
