### PR TITLE
Use iterator and correct string insert

### PR DESCRIPTION
**Pull request by b0guslaw**
* [x] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before? Mentioned it on Discord
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

This PR fixes the compiler warning I have encountered when building SFML in C++20 on gcc 12 by using a different, more appropriate function signature.

This PR is related to the issue #2217 

## Tasks

* [x] Tested on Linux
* [ ] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

The fix does not change any functionality and as such no special tests are required

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Review by vittorioromeo — APPROVED** [review]
I am happy with this change as it works around a compiler bug and makes the code a bit nicer (IMHO) at the same time. I see no risk in merging it, assuming CI is happy.

**Review by ChrisThrasher — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
Can you please retarget this to `2.6.x`?

**Review by eXpl0it3r — APPROVED** [review]
Generally don't want to work around compiler bugs that might be fixed soon-ish, but it's not like this hurts us.

**Comment by vittorioromeo** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
Thank you for this fix 🥳

**Pull request merged**
