### PR TITLE
Only compile Catch main once

### PR DESCRIPTION
**Pull request by ChrisThrasher**
Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

Because Catch is so expensive to compile, it's really helpful for initial compile times if this target doesn't have to be recompiled so often. This won't make a huge impact on developers who are mostly doing incremental builds but can have a meaningful impact on CI runners that are always doing clean builds.

## Tasks

* [ ] Tested on Linux
* [ ] Tested on Windows
* [x] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
@vittorioromeo Here's an atomic PR for you while I work on rearranging some commits for #1898

**Comment by ChrisThrasher** [comment]
On second thought, I will include this in #1898 instead since.

**Comment by ChrisThrasher** [comment]
Reopening to prevent having more than one commit in a given pull request.

**Comment by ChrisThrasher** [comment]
PR still shows as closed. Maybe that's because I deleted the remote branch then recreated it. I'm not sure. The "Reopen and comment" button is greyed out.

**Comment by vittorioromeo** [comment]
> PR still shows as closed. Maybe that's because I deleted the remote branch then recreated it. I'm not sure. The "Reopen and comment" button is greyed out.

Feel free to create another. But I would rename `sfml-test-config` to `sfml-test-main`, it seems more appropriate.

**Comment by ChrisThrasher** [comment]
See #1918

**Comment by ChrisThrasher** [comment]
@eXpl0it3r This can be removed from the 3.0 project.

**Pull request closed without merging**
