### PR TITLE
Remove GCC 4 workaround

### PR DESCRIPTION
**Pull request by ChrisThrasher**
Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

No more need to work around GCC 4 shortcomings. 

## Tasks

* [ ] Tested on Linux
* [ ] Tested on Windows
* [x] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

### CODE REVIEW

**Review by eXpl0it3r — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by Bromeon** [comment]
Just to understand the context, why is this no longer needed? Because we don't support that version anymore?

If so, do we want to make it explicit? Would be nicer than weird errors down the line.
```cpp
#if __GNUC__ < 4
   #error This version of g++ is not supported by SFML.
#endif
```

**Comment by eXpl0it3r** [comment]
GCC 4 doesn't support C++17, so it should fail when trying to enable C++17

https://gcc.gnu.org/projects/cxx-status.html#cxx17

**Comment by ChrisThrasher** [comment]
@eXpl0it3r is right. It's because GCC 4 only supports some subset of C++14.

**Pull request merged**
