### PR TITLE
Adding values to usageToVirtualCode

### PR DESCRIPTION
**Pull request by vitor251093**
Adding values to HIDInputManager::usageToVirtualCode and commenting items that return 0xff instead so they are easier to find in case someone discover their values.

Added F16, F17, F18, F19, F20, Mute, Volume Up and Volume Down.

Reference: http://stackoverflow.com/a/16125341/4370893

### CODE REVIEW

**Comment by mantognini** [comment]
Thanks for your PR.

> Adding values to HIDInputManager::usageToVirtualCode 

Your reference seems valid, so why not indeed. Did you test those on a keyboard? (I only have the basic key set on mine.)

> and commenting items that return 0xff instead so they are easier to find in case someone discover their values.

What the reasoning behind this conclusion? As it currently is (i.e. on master) you can use a debugger to trap your program on any of those `0xff` case and directly know which constant was unknown. With your PR you can only trap the program in the `default` case and then you have to manually look up the constant to which `usage` refer to. Or did I miss something?

**Comment by vitor251093** [comment]
> Did you test those on a keyboard? (I only have the basic key set on mine.)

I can test Volume Up, Volume Down and Mute on my keyboard, but not the others. I will do it in some minutes and return with the answer ;)

> As it currently is (i.e. on master) you can use a debugger to trap your program on any of those 0xff case and directly know which constant was unknown. With your PR you can only trap the program in the default case and then you have to manually look up the constant to which usage refer to. Or did I miss something?

I guess I was the one who missed something ;P I was considering the code readability when suggested that so it would be easier to find the keys that were 'filled' yet.

**Comment by mantognini** [comment]
Let me know when you have time to test those additional keys. :-)

BTW, could you squash the two commits into one? That'd be better for the git history.

**Comment by mantognini** [comment]
And only now do I remember SFML keyboard enumeration has no entry for F17+ or volume keys so those changes are not directly relevant. I suggest we keep this PR in mind when working on #7.

**Pull request closed without merging**
