### PR TITLE
Revert to Xlib event handling

### PR DESCRIPTION
**Pull request by binary1248**
XCB event handling just breaks too many things.

* Breaks X input method
* Breaks DRI2 buffer swap and invalidate messages
* Breaks subtle interaction with X Shape events that might be important in some window managers
* Breaks integration with other toolkits that still use Xlib events
* Does not automatically handle keyboard layout changes

The only thing this PR changes is the event queue owner. Even within the switch cases, the events are still handled using XCB, so the changeset is kept relatively small and there are no disadvantages that would have been the case had Xlib been used everywhere.

This fixes among other things #908 and [this](http://en.sfml-dev.org/forums/index.php?topic=18536.0).

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Sounds fair. Any Linux users who could test this?

**Comment by victorlevasseur** [comment]
Tested on Fedora 22. The integration with GTK+ works perfectly now (was not the case in 2.3/2.3.1).

**Comment by TankOs** [comment]
Tested on Arch Linux w/Awesome WM. All examples work. :+1: :cat2:

**Comment by TankOs** [comment]
Btw, can we set this to 2.3.2?

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon into the branch 2.3.x, unless someone raises any concerns.

**Pull request merged**
