### PR TITLE
Improved method used to filter KeyRelease in X11

### LINKED ISSUE #1223: setKeyRepeatEnabled(false) doesn't work after second window.create() call on Linux
setKeyRepeatEnabled(false) doesn't work after second window.create() call on Linux.

Here is the minimal code:

`
#include <iostream>
#include <SFML/Graphics.hpp>

sf::RenderWindow window;

void createWindow() {
    window.create(sf::VideoMode(100, 100), "Window");
    window.setKeyRepeatEnabled(false);
}

int main (int argc, char* argv[]) {
    createWindow();

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            switch(event.type) {
                case sf::Event::Closed:
                    window.close();
                    break;

                case sf::Event::KeyPressed:
                    if(event.key.code == sf::Keyboard::H) createWindow();

                    std::cout << "Key Pressed: " << event.key.code << std::endl;
                    break;

                case sf::Event::KeyReleased:
                    std::cout << "Key Released: " << event.key.code << std::endl;
                    break;
            }
        }
    }

    return 0;
}
`

### PR DESCRIPTION
**Pull request by texus**
This should fix #1223.

The event behind KeyRelease is now only retrieved from the same window. Because peeking did not work well, the event is instead removed from the queue and put back afterwards (unless the event is KeyPress and key repeating is disabled).

### CODE REVIEW

**Comment by mantognini** [comment]
SFMLBuildMaster: Build this please. (again)

I quickly tested this, it seems to indeed fix the issue. @naezith, can you confirm it works as well on your system?

**Comment by naezith** [comment]
@mantognini It's working exactly the same for me.

**Comment by mantognini** [comment]
@naezith Strange.. I did check again in a Ubuntu VM (at work I'm under Mint), this PR fixed the issue. Did you make sure to remove the old binaries and do a clean build?

**Comment by eXpl0it3r** [comment]
> Did you make sure to remove the old binaries and do a clean build?

@naezith

**Comment by naezith** [comment]
Yes.

**Comment by texus** [comment]
There seems to be a second issue. My fix should solve the issue caused by multiple windows (tested on both manjaro and on ubuntu). However, even with a single window I sometimes get the Release & Press repeats (more common on my pc with ubuntu), just at a much slower rate (e.g. once every second instead of many events per second which happened with multiple windows before my fix).

While debugging I noticed that the repeats stop entirely when there is a cout on top of the function. I added a short sleep now when a KeyRelease event occurs to allow some time for the KeyPress to arrive. Now all key pressed and released events always seem to occur like they should.

@naezith Could you test this new version?

**Comment by naezith** [comment]
I think sleep call should not be there no matter what.

**Comment by texus** [comment]
I agree with that. The behavior was a bit inconsistent on my ubuntu pc without that sleep call, that commit was more for testing than to really be included in SFML.

**Comment by eXpl0it3r** [comment]
So what's the status of this? Is the first commit okay? Did you manage to find out why there are additional repeats?

**Comment by texus** [comment]
The first commit should solve the issue. I tested it on two computers and mantognini also confirmed that it worked.
Only @naezith claims that it didn't fix the issue for him. So he probably has to figure out why it isn't working for him (if absolutely certain the code with the fix is used, try outputting some variables inside `WindowImplX11::processEvent` and see if anything weird shows).

I have no idea why on my ubuntu pc there were additional repeats unrelated to the first issue (they were much less often and more irregular, so the distinction with the original issue was very clear). But considering they only happen on that pc and the repeats didn't always occur (e.g. plugging in a keyboard or creating a new window or doing some other things could cause the repeats to stop), I'd suggest to just forget about this ever happening until someone else ever faces a similar issue. I'll remove the second commit later today.

**Comment by eXpl0it3r** [comment]
@binary1248 mentioned that this isn't really a good fix. Can you elaborate on a better approach to fix this issue, @binary1248?

**Comment by binary1248** [comment]
I submitted an alternative patch in #1291.

**Comment by eXpl0it3r** [comment]
There's a better implementation by @binary1248 in #1291

**Pull request closed without merging**
