### PR TITLE
Unit test updates

### PR DESCRIPTION
**Pull request by JonnyPtn**
Rebased onto master and updated travis/appveyor configs to build and run the tests

Should make #1475 ready for merge

### CODE REVIEW

**Comment by LaurentGomila** [comment]
> Should make #1475 ready for merge

What about "Find a solution for dynamic library not being found for the runtests target"?

**Comment by JonnyPtn** [comment]
Good point, appears to only be an issue on Windows so I'll look into it when I get on a windows machine.

Also seems like an odd error on iOS which I'll look into

**Comment by LaurentGomila** [comment]
Why do you add `${CMAKE_BINARY_DIR}/lib/Debug` to the PATH? I would rather use generator expressions to get the actual output path of one of the sfml-xxx targets.

**Comment by JonnyPtn** [comment]
Fixed and ready for review.

iOS is currently disabled as it's not possible to run iOS unit tests the same way as all the other platforms. There may be some way using the xctest support [here](https://cmake.org/cmake/help/v3.3/module/FindXCTest.html) which I'll look into when I can

Anyone know what the deal with unit testing on android is? I'll add it to my list but for now I'd say let's get this going to cover the main platforms

**Comment by LaurentGomila** [comment]
That was quickly merged...

Why don't we build everything into a "${CMAKE_BINARY_DIR}/bin" folder, rather than copying SFML DLLs in every sub-folder they are needed?

**Comment by eXpl0it3r** [comment]
It was simply merged onto our feature branch, see #1475

**Comment by LaurentGomila** [comment]
Ah, ok.

But anyway, even if it's not merged into the master branch, it would have been convenient to end this review here rather than having to open a new PR 😛

**Pull request merged**
