### PR TITLE
Update Xcode template material

### PR DESCRIPTION
**Pull request by mantognini**
Supersedes #968.

These are only minor changes that can be merged right away.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by mantognini** [comment]
BTW, I had to edit the main logo available for download on sfml-dev.org to look like this:
icon_256x256

Do you think it's worth adding this version on the website too? (I've got svg and png versions.)

PS: the error Jenkins is currently reporting is due to a connection error. I can safely be ignored.

**Comment by eXpl0it3r** [comment]
Yeah, I think a logo-only version might be useful. Had to create my own a few times...

**Comment by mantognini** [comment]
Okay, I'll create a PR for that later on.

**Pull request merged**
