### PR TITLE
Added CONTRIBUTING guidelines

### PR DESCRIPTION
**Pull request by mantognini**
So here it is... ;-)

### CODE REVIEW

**Comment by Bromeon** [comment]
Looks good! :+1:

**Comment by zsbzsb** [comment]
:+1:

**Comment by binary1248** [comment]
:+1:

**Comment by Bromeon** [comment]
Can we merge this soon? The number of unjustified issues/PRs grows with every day...

**Comment by eXpl0it3r** [comment]
Merged in 20756e3539d6e382ba555b9cdd3777f70df12789 on branch 2.3.x.

**Pull request closed without merging**
