### PR TITLE
Add tests for `sf::RenderTarget` and `sf::RenderTexture`

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

We're close to 50 test cases!
Screenshot 2023-09-01 at 9 58 13 PM

I could use a hand with the `sf::RenderTarget::mapPixelToCoords` and `sf::RenderTarget::mapCoordsToPixel` if anyone has a better idea for what inputs are the most meaningful for testing. I just pulled out some random numbers for the sake of covering those code paths but I don't understand these functions well enough to test them any better than that.

These two classes should be the last two Graphics module classes without tests.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Screenshot 2023-09-01 at 11 19 54 PM

nice

**Review by binary1248 — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
> I could use a hand with the `sf::RenderTarget::mapPixelToCoords` and `sf::RenderTarget::mapCoordsToPixel` if anyone has a better idea for what inputs are the most meaningful for testing. I just pulled out some random numbers for the sake of covering those code paths but I don't understand these functions well enough to test them any better than that.

As the point of these function is to convert between screen space and world/render space, it might make sense to move or otherwise transform the view, so that there isn't a 1:1 mapping.

**Comment by ChrisThrasher** [comment]
> As the point of these function is to convert between screen space and world/render space, it might make sense to move or otherwise transform the view, so that there isn't a 1:1 mapping. For example, if you move the view by 100px, then the top left (0, 0) corner of the render target isn't (0, 0) in the world space anymore, but it's (100, 0).

Good idea. I added an offset to the views to further test more of the internal logic.

**Comment by ChrisThrasher** [comment]
I added a few more `RenderTexture` tests after seeing them missing from the codecov report. While I was in there I also added tests for `sf::Texture::generateMipmap` which is used by `sf::RenderTexture::generateMipmap`.

**Review by eXpl0it3r — APPROVED** [review]

**Pull request merged**
