### PR TITLE
Added IPv6 implementation

### PR DESCRIPTION
**Pull request by blinkofaneye**
## Description

This is an IPv6 implementation. It uses [C++ networking TS reference implementation](https://github.com/chriskohlhoff/networking-ts-impl).

## Tasks

Tested on Linux.

## How to test this PR?

```cpp
#include <iostream>
#include <SFML/Network.hpp>

using namespace std;

// compiled with:
// $ g++ -I networking-ts-impl/include/ -lsfml-network -lsfml-system -lpthread main.cpp
// Run these before running this program
// $ echo 'Hi UDP client!' | nc -u -lp8080
// $ net-server host ::1/ipv6 port 8081

int main()
{
    {
        // Test IPv4 first
        // TCP socket
        sf::IpAddress addr("www.facebook.com", 4);
        sf::TcpSocket tsock;

        if(tsock.connect(addr, 80) != sf::Socket::Done)
        {
            cout << "TCP IPv4 connection error..." << endl;
            return 1;
        }

        char req[] = "GET / HTTP/1.1\r\n\r\n";
        char buffer[250] = {0};
        size_t received;

        // send the http request
        tsock.send(req, strlen(req));

        // receive the response
        tsock.receive(buffer, 249, received);

    
        cout << "*** Testing TCP with IPv4 ***" << endl;
        cout << "IPv4 local address: " << sf::IpAddress::getLocalAddress() << endl;
        cout << "IPv4 Address: " << addr << endl;
        cout << "TCP IPv4 Remote address: " << tsock.getRemoteAddress() << endl;
        cout << "TCP IPv4 Response: " << buffer << endl;
        cout << "TCP IPv4 Remote port: " << tsock.getRemotePort() << endl;
        cout << "TCP IPv4 Local port: " << tsock.getLocalPort() << endl;
        cout << "*** ----------------------***" << endl;


        sf::IpAddress server;
        unsigned short port;
        sf::UdpSocket usock;
        char message[] = "Hi UDP server!";
        size_t receive;

        // send message
        usock.send(message, strlen(message), sf::IpAddress::LocalHost, 8080);
        // receive response
        std::memset(buffer, 0, 250);
        usock.receive(buffer, 249, received, server, port);

        cout << "*** Testing UDP with IPv4 ***" << endl;
        cout << "UDP IPv4 response: " << buffer << endl;
        cout << "UDP IPv4 Remote port: " << port << endl;
        cout << "UDP IPv4 Local port: " << usock.getLocalPort() << endl;
        cout << "*** ----------------------***" << endl;
    }

    {
        // Test IPv6
        // TCP socket
        // my ISP doesnt provide IPv6 route so i tested on localhost only
        sf::IpAddress addr("::1");
        sf::TcpSocket tsock;
        
        if(tsock.connect(addr, 8081) != sf::Socket::Done)
        {
            cout << "TCP IPv6 connection error..." << endl;
            return 1;
        }

        char buffer[250] = {0};
        size_t received;

        // just receive what net-server sends
        tsock.receive(buffer, 249, received);

        cout << "*** Testing TCP with IPv6 on localhost ***" << endl;
        cout << "TCP IPv6 response: " << buffer << endl;
        cout << "IPv6 Address: " << addr << endl;
        cout << "TCP IPv6 Remote address: " << tsock.getRemoteAddress() << endl;
        cout << "TCP IPv6 Remote port: " << tsock.getRemotePort() << endl;
        cout << "TCP IPv6 Local port: " << tsock.getLocalPort() << endl;
        cout << "*** ----------------------***" << endl;
    }

    // more tests pls? xD
    return 0;
}
```

### CODE REVIEW

**Comment by blinkofaneye** [comment]
This is an IPv6 implementation. Now IpAddress is derived from NetworkAddress(maybe later UnixAddress or something could be derived it too).

Example code(tested on linux and windows):
#include <iostream>
#include <cstring>
#include <SFML/Network.hpp>

using namespace std;

int main()
{
    sf::TcpSocket sock;
    sf::IpAddress address("www.facebook.com", 6);
    cout << "address: " << address << endl;
    if(sock.connect(address, 80) != sf::Socket::Done)
    {
        cout << "Connection error!" << endl;
        return 1;
    }
    char buffer[251] = {0};
    size_t received;
    char req[] = "GET / HTTP/1.1\r\n\r\n";
    sock.send(req, strlen(req));
    sock.receive(buffer, 250, received);
    cout << "buffer: " << buffer << endl;
    cout << "local port: " << sock.getLocalPort() << endl;
    cout << "remote address: " << sock.getRemoteAddress() << endl;
    cout << "remote port: " << sock.getRemotePort() << endl;
    return 0;
}

**Comment by blinkofaneye** [comment]
Ah, i didn't think about that xD I didnt want to make a lot of changes in the Network module. Maybe i should wait the TS to be included in the C++ standard?

**Comment by binary1248** [comment]
Maybe you misunderstood me... I didn't mean implement this change to SFML using the networking TS. I meant use the networking TS in your own code instead of sfml-network. The networking TS is far more feature complete and powerful than sfml-network currently is, that is the reason why sfml-network will very likely be removed in the future and you shouldn't really invest too much effort into it.

**Comment by blinkofaneye** [comment]
hahaha okay, so i just close this PR then?

**Comment by binary1248** [comment]
If you want.

**Comment by kachim2** [comment]
I'd say the networking TS is quite more difficult to use, and doesn't have many helpful features and abstractions like the sf::Packet class. And it isn't simple.

**Pull request closed without merging**
