### PR TITLE
Assert Messages For Vector2 Functions

### PR DESCRIPTION
**Pull request by erikbolumburu11**
## Description

My pull request adds some assert messages into the new Vector2 functions from SFML3 that make it clearer that using a zero vector with these functions will cause an error.

This PR is related to the issue #2592

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## Testing

```cpp
#include <SFML/Graphics.hpp>

void Test() {
	sf::Vector2<float> v1;
	sf::Vector2<float> v2(1.0f, 1.0f);
	v1.normalized();
	v1.angleTo({ 1.0f, 1.0f });
	v2.angleTo({ 0.0f, 0.0f });
	v1.angle();
	v2.projectedOnto({ 0.0f, 0.0f });
}
```
### Resulting Errors
```c++
Assertion failed: ("Vector2::normalized() cannot normalize a zero vector", *this != Vector2<T>()), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 41
Assertion failed: ("Vector2::angleTo() cannot calculate angle from a zero vector", *this != Vector2<T>()), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 52
Assertion failed: ("Vector2::angleTo() cannot calculate angle to a zero vector", rhs != Vector2<T>()), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 53
Assertion failed: ("Vector2::angle() cannot calculate angle from a zero vector", *this != Vector2<T>()), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 64
Assertion failed: ("Vector2::projectedOnto() cannot project onto a zero vector", axis != Vector2<T>()), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 90
```

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
To fix the compiler errors you need to rearrange how you put the message in the assert. If you follow the below pattern you won't get any warnings. Plus for the sake of consistency I'd rather you use this pattern.

https://github.com/SFML/SFML/blob/b391be2316c0f9859a504deabb5225a02c1b3e89/src/SFML/Window/WindowBase.cpp#L248

**Comment by Bromeon** [comment]
Thanks!

What is the point of the lambda expressions? They add extreme syntax overhead.
```cpp
    [[maybe_unused]] const auto validateZeroVector = [this]() { return *this != Vector2<T>(); };
    assert(validateZeroVector() && "Vector2::normalized() cannot normalize a zero vector");
```
vs.
```cpp
    assert(*this != Vector2<T>() && "Vector2::normalized() cannot normalize a zero vector");
```

**Comment by erikbolumburu11** [comment]
ah I was following what the assert in the WindowBase assert example did, I guess that required it though because it had conditionals and stuff. I'll remove the lambdas

**Comment by erikbolumburu11** [comment]
Okay I've removed the lambda expressions, errors now look like this which I believe is succinct:
```c++
Assertion failed: *this != Vector2<T>() && "Vector2::normalized() cannot normalize a zero vector", file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 41
```

**Comment by Bromeon** [comment]
Thanks for the update! Could you squash your commits into a single one?

**Comment by erikbolumburu11** [comment]
Sorry I'm not too familiar with git yet, I think I might have squashed them? I'm not sure there is much I can do retroactively to squash all my commits into one.

**Comment by eXpl0it3r** [comment]
It's okay, if you don't know how, I'll can do once the code is correct 🙂

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by ChrisThrasher — APPROVED** [review]
Thanks for your contribution! This will surely help future users who trigger these assertions.

**Comment by ChrisThrasher** [comment]
On second thought, could you please document the assertions in Vector2.inl? There are only two more in that file in `cwiseDiv` which protect against divisions by zero.

https://github.com/SFML/SFML/blob/b391be2316c0f9859a504deabb5225a02c1b3e89/include/SFML/System/Vector2.inl#L97-L98

**Comment by erikbolumburu11** [comment]
ah i wasnt aware these existed, will do that now.

**Comment by erikbolumburu11** [comment]
Test
```cpp
void Test() {
	sf::Vector2f v = { 10.f, 5.f };
	v.cwiseDiv({ 0.0f, 1.0f });
	v.cwiseDiv({ 1.0f, 0.0f });
}
```

Assert Results:
```cpp
Assertion failed: rhs.x != 0 && "Vector2::cwiseDiv() cannot divide by 0", file C:\Users\erikf\dev\LIBRARIES\SFML3\include\SFML\System\Vector2.inl, line 97
Assertion failed: rhs.y != 0 && "Vector2::cwiseDiv() cannot divide by 0", file C:\Users\erikf\dev\LIBRARIES\SFML3\include\SFML\System\Vector2.inl, line 98
```

**Comment by ChrisThrasher** [comment]
Latest changes look good! Pending CI and a 2nd approval I think this is good to merge.

**Comment by eXpl0it3r** [comment]
I've done it once again and failed to update a non-origin remote master branch. I don't understand why `git push -u erik master` pushes our master to the erik remote master, instead of using the checked out branch that is setup as tracking, guess I'm just not mighty enough with git.

Aaanny ways, superseded by #2595 where I got rid of the merge commits and squashed the rest into two commits...

**Comment by Bromeon** [comment]
@eXpl0it3r Instead of:
```
git push -u erik master
```
which pushes _local_ master to `erik`, you would need:
```
git push -u erik my-local-branch:master
```

**Pull request closed without merging**
