### PR TITLE
Fix Visual Studio 2019 complaints regarding the int64_t type not being in the std namespace

### PR DESCRIPTION
**Pull request by PierceLBrooks**
This resolves the issue that I logged here:
https://github.com/SFML/SFML/issues/2211

### CODE REVIEW

**Review by ChrisThrasher — APPROVED** [review]
Thanks!

**Comment by ChrisThrasher** [comment]
TL;DR This problem only exists in older version of VS 2019. Because we can't rule out people still using such versions I'm fine merging this just in case.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
Thank you for the fix! 🥳

**Pull request merged**
