### PR TITLE
Remove implicitly defined `sf::Image` special member functions

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

None of these 6 special member functions have any non-trivial code in here and we can omit all of them. 

## Tasks

* [x] Tested on Linux
* [x] Tested on Windows
* [x] Tested on macOS
* [x] Tested on iOS
* [x] Tested on Android

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
I found many other instances of empty default destructors which implicitly disable move semantics. If we want to better support move semantics, I can go through and delete all of those empty destructors in another PR.

**Review by Bambo-Borris — APPROVED** [review]

**Review by vittorioromeo — APPROVED** [review]
LGTM.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
@eXpl0it3r @vittorioromeo Full CI pipeline is passing. Good to merge now?

**Pull request merged**
