### PR TITLE
Limit the scope of event object

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

Thanks to @eXpl0it3r for this neat little trick to limit the scope of the `sf::Event` object. I figured it was worth making this sweeping change to all event loops in the library so that anyone copy-pasting code gets slightly better code than before. I even changed the issue and PR templates.

## Tasks

* [x] Tested on Linux
* [x] Tested on Windows
* [x] Tested on macOS
* [x] Tested on iOS
* [x] Tested on Android

### CODE REVIEW

**Review by eXpl0it3r — APPROVED** [review]
I like the change, but I also want to hear the opinion from someone else 🙂

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by Bromeon — COMMENTED** [review]
To be perfectly honest, I think this makes things a bit less readable, because:
* `while (window.pollEvent(event))` is pretty expressive -- "while the window polls events". The same cannot be said about the `for` variant.
* We now have only one line which does everything instead of two, and the `for` loop without an update part is quite unusual. People will likely wonder what exactly happens.

Compared to that, the limited scope might be nice, but it doesn't look to me like it solves a real problem that we had in the past. Generally, I would try to check trade-offs of common C++ best practices depending on their context.

**Comment by eXpl0it3r** [comment]
> it doesn't look to me like it solves a real problem that we had in the past

What about all those issues people ran into when using the event object outside of the event loop?
That's not a one of thing and keeps happening quite regularly.
The source of the issue is usually also not very clear, as people report stuff like "moving my mouse, closes the window" or so, because the event object is in being checked in an invalid state.

Additionally it removes the discussions that happen less frequent of whether the event object should be a member variable, because "performance" (having to recreate the event object each iteration) etc.

> I think this makes things a bit less readable

I agree it's not as nicely matching the English phrasing, but in my opinion the issues it solves outweigh the slightly reduced readability.

**Comment by vittorioromeo** [comment]
I like the change as well, and it is similar in spirit to C++17's introduction of `if(/* init */; /* predicate */)`, so people will likely understand it if they know about that C++17 addition.

**Comment by Bromeon** [comment]
OK, seems like 3 people are in favor 🙂 

> I like the change as well, and it is similar in spirit to C++17's introduction of if(/* init */; /* predicate */), so people will likely understand it if they know about that C++17 addition.

Yep, I had to think of that as well. Whether it's more or less readable depends a bit of the complexity of both parts (and matter of taste/style of course). That made me wonder why they didn't also introduce `while (init; cond)`, that would fit perfectly here. Only found fairly non-convincing answers [here](https://stackoverflow.com/q/59985550).

**Pull request merged**
