### PR TITLE
Use `std::quoted`

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

While working on #2042 and #2043 I realized that there are a good number of instances of us manually adding quotes around something so I went about finding all those instances and replacing them with `std::quoted` which I think better expresses the intent of the code. This is my first time using `std::quoted` but I believe this is a valid use case for it. 

## Tasks

* [ ] Tested on Linux
* [ ] Tested on Windows
* [x] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Review by Bromeon — COMMENTED** [review]
Technically, we would need
```cpp
#include <iomanip>
```
in each file, no?

**Comment by ChrisThrasher** [comment]
> Technically, we would need
> 
> ```c++
> #include <iomanip>
> ```
> 
> in each file, no?

I don't think we technically need it as evident by CI passing but it's not a bad idea to add it anyways. Want me to do that?

**Comment by ChrisThrasher** [comment]
> Technically, we would need
> 
> ```c++
> #include <iomanip>
> ```
> 
> in each file, no?

I don't think we technically need it as evident by CI passing but it's not a bad idea to add it anyways. Want me to do that?

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
I find relying on transitive includes isn't the best idea, unless the transitivity is actually guaranteed.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by ChrisThrasher** [comment]
I added `#include <iomanip>` to all the files using `std::quoted`.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
Thanks! 🙂

**Pull request merged**
