### PR TITLE
Mark derived classes as `final`

### PR DESCRIPTION
**Pull request by rtkid-nt**
#2342

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Adding `final` to every single class removes lots of useful functionality from the library. If we are to use `final` it must be in very specific places where the benefits are provable and justify the reduced functionality of the library.

**Comment by Bromeon** [comment]
> Adding `final` to every single class removes lots of useful functionality from the library. If we are to use `final` it must be in very specific places where the benefits are provable and justify the reduced functionality of the library.

It's also possible to look at it from another perspective: classes are final by default, and can be opened up if designed to be inherited. While it restricts use cases, it can prevent mistakes and guide the user to use composition instead.

I'm not saying one or the other is the correct way, but this is e.g. how we handle `explicit` constructors. We consider it a design flaw of C++ itself to have chosen the wrong default. Kotlin for example restricts inheritance and requires the `open` keyword to enable it -- and this despite being Java-compatible, a language which is _extremely_ driven by inheritance based designs.

**Comment by JWStaiert** [comment]
Just $.02 from a long time c++ developer, in the general case, final should actually be the default. Unless classes are explicitly designed and (more importantly) tested for use by inheritance they frequently won’t work as expected. Moreover, code designed for composition typically performs better and can be better optimized by a compiler. Proper use of a library designed around inheritance is a much steeper learning curve.

**Comment by Bromeon** [comment]
So is this decision... final? 😁

**Comment by ChrisThrasher** [comment]
I'm open to adding `final` in select places where derivation is prone to cause bugs. We can also add type trait tests to enforce the presence of final and conversely to ensure that certain tests remain open to subclassing.

**Pull request closed without merging**
