### PR TITLE
Remove vendored doctest header

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

This PR uses the CMake FetchContent module to automatically download a specific release of Doctest and build it alongside the rest of SFML. This has the benefit of letting us removing another ~7000 SLOC from the repo. When updating Doctest in the future, the diff will be a single line as opposed to the status quo that requires many thousands of lines of changes.

Because we now have access to the entire repo, we also have access to the additional CMake modules Doctest provides including the module which includes the `doctest_discover_tests` function. I expect this will come in handy later. It isn't available to those who only have a copy of the doctest.h. See [this commit](https://github.com/ChrisThrasher/SFML/commit/e969658c6fb2af59a6cbc129131b78d8181eafe4) to see what that would look like.

Because the doctest header is now no longer a `SYSTEM` include, there were some warnings generated that I had to fix, hence the minor changes to the source code of the tests. 

## Tasks

* [x] Tested on Linux
* [x] Tested on Windows
* [x] Tested on macOS
* [x] Tested on iOS
* [x] Tested on Android

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by Bromeon** [comment]
I think `FetchContent` is nice and probably the way to go in the future, possibly also for other libraries. We should however be aware of the downsides mentioned in https://github.com/SFML/SFML/issues/1991:

> [...] `FetchContent` at build time would make us rely on several third-party resources to be available, or the build is broken. C++ doesn't have a centralized, stable, always-up dependency repository like crates.io, so we would have to trust each provider individually. [...] Downtime is not the only problem. GitHub repos change, are renamed, deleted, transferred, ...
> 
> I don't like the thought of people's build to break because one of the dependency maintainer decides to changes something or makes a mistake. You probably heard of the [leftpad](https://www.theregister.com/2016/03/23/npm_left_pad_chaos/) disaster, or just a few weeks ago, [colors and faker](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/). The first case made every single dependent code break, the second still broke everything with "use latest version" policy. And those are published in npm, likely the most widespread package manager, which at least has some basic stability. Unlike a GitHub repo which can change entirely through git push or two clicks.
> 
> And those are just some of the issues, security is another one. If any contributor with push access in any of these repos decides to go rogue (or is hacked), and even if this only remains undetected for a few hours, a SFML user can end up downloading malware.
>
> If we don't want to version external code in SFML's own repo, we can always create a separate SFML/extlibs repo and let the user pull dependencies from there. But this remains in our organization, under our control, and dependency updates are a conscious decision.

So what do you guys think about a `SFML/extlibs` repo? It can have a structure like:
```
Repos.txt
doctest/
freetype2/
ogg/
OpenAL/
stb_image/
...
```
and the `Repos.txt` would contain each link to a dependency on a separate line, which then could be cloned and checked into Git by some CI job.

**Comment by Bromeon** [comment]
To clarify my last comment; this doesn't have to be a blocker for this PR -- the upstream repo for `FetchContent` could be moved to SFML in a later step. I'm fine with directly depending on `doctest` as an *intermediate* solution (to unblock development quicker).

But I'd like us to have a somewhat aligned vision of SFML's supply chain, and the general direction we want to take to migitate such risks.

**Comment by ChrisThrasher** [comment]
> But I'd like us to have a somewhat aligned vision of SFML's supply chain, and the general direction we want to take to migitate such risks.

I can't make up my mind on what solution I most like so I don't have much to share at the moment, sorry. I'm following along but don't have much to contribute on that topic.

**Review by eXpl0it3r — APPROVED** [review]

**Comment by eXpl0it3r** [comment]
Personally, I don't think supply chain issues are as big of an issue, but let's maybe continue the discussion over at #1991

**Comment by eXpl0it3r** [comment]
Thanks for this initial step of using FetchContent 🙂

**Pull request merged**
