### PR TITLE
Corrected typo.

### PR DESCRIPTION
**Pull request by binary1248**

### CODE REVIEW

**Comment by MarioLiebisch** [comment]
Was that really worth a PR? ;)

**Comment by eXpl0it3r** [comment]
Was that really worth a comment? :wink:

**Comment by MarioLiebisch** [comment]
Probably, yes. :D

**Comment by Bromeon** [comment]
I also think such things can be committed to master directly. 
More importantly... why is it still not merged? :grin:

**Comment by eXpl0it3r** [comment]
Because I don't know where to merge it to, see internal discussion.

**Comment by LaurentGomila** [comment]
You can merge it to master, and if we create a 2.3.x branch we can easily cherry pick the commit to that branch later.

**Comment by TankOs** [comment]
Or you can merge to 2.3.1 and it will be automagically merged into master later, without the need to cherry-pick at all. Given that 2.3.1 comes before 2.4.0, it makes sense IMHO. ;)

**Comment by TankOs** [comment]
Another note: I think it even makes sense to send such stuff in as a pull request: We can clearly see that even small changes have to be integrated properly. :P eXpl0it3r pays much attention at integrating things well, so we probably don't want to mess with that.

**Comment by Bromeon** [comment]
Yes... I just think it can reduce the unnecessary bureaucratic overhead, and we can focus our efforts on important tasks. I'm also glad if I'm not flooded with dozens of notifications every time I visit GitHub, or if I don't have to skim through hundreds of issues in order to find a specific one :wink: 

But yes, I'd say it's in the eyes of the one making the change, let's just be reasonable :grinning:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged to 2.3.x soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in e38a26ec25bc3540eb6745a99d8db55a185e317c on branch 2.3.x

**Pull request closed without merging**
