### PR TITLE
Consolidate redundant gl.h headers

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

I consolidated 3 identical headers into 1. This saves thousands of lines of code, simplifies maintenance, and makes search results clearer by not repeating results.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Review by vittorioromeo — APPROVED** [review]
LGTM, thanks!

**Comment by eXpl0it3r** [comment]
I rather have self-contained examples than "save" some lines of code...

**Comment by Bromeon** [comment]
Maybe we should get into the habit of letting at least 1-2 days pass before merging (unless _several_ people approve it before) 🙂 

Probably this PR seemed uncontroversial, but it that's often subjective.

**Comment by vittorioromeo** [comment]
> Probably this PR seemed uncontroversial

Yeah, that's why I went ahead. It only touches examples and it's an internal refactoring change that is not visible to users. Otherwise I wouldn't have be so quick.

Happy to revert if you feel like this was the wrong move!

**Pull request merged**
