### PR TITLE
Add move semantics to 'sf::Packet'

### PR DESCRIPTION
**Pull request by vittorioromeo**
## Description

This PR makes `sf::Packet`'s move operations actually move the internal buffer instead of silently copying it. 

> Why doesn't `sf::Packet` actually move the buffer?

https://www.foonathan.net/images/special-member-functions.png

> Can you prove it?

https://gcc.godbolt.org/z/57hnW4fEh

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

CI.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
Couldn't we just remove the empty destructor instead?

**Comment by vittorioromeo** [comment]
> Couldn't we just remove the empty destructor instead?

It's `virtual`, there might be someone out there using `sf::Packet` as a base class...

**Comment by binary1248** [comment]
Based on existing copy assignment operators, I think the style is `Packet& operator =(const Packet&);` (note the space between `operator` and `=`). Disclaimer: I didn't invent this style. 😄

**Comment by vittorioromeo** [comment]
> Based on existing copy assignment operators, I think the style is `Packet& operator =(const Packet&);` (note the space between `operator` and `=`). Disclaimer: I didn't invent this style. 😄

There are 31 occurrences of `operator=` and 44 occurrences of `operator =` in the entire codebase. One more reason to switch to `clang-format` :)

**Comment by ChrisThrasher** [comment]
> There are 31 occurrences of operator= and 44 occurrences of operator = in the entire codebase. One more reason to switch to clang-format :)

#1861 is in a great state!

**Comment by binary1248** [comment]
I think a search in the 2.1 codebase would yield more conclusive results, there was only a single ~de-facto maintainer~ style back then. 😄

**Review by binary1248 — APPROVED** [review]

**Comment by Bromeon** [comment]
Should we declare the virtual destructor as `= default`, too?

It doesn't seem to do any TU trickery (like a `T` in `unique_ptr<T>` as an incomplete type in the header).

**Comment by vittorioromeo** [comment]
> Should we declare the virtual destructor as `= default`, too?
> 
> It doesn't seem to do any TU trickery (like a `T` in `unique_ptr<T>` as an incomplete type in the header).

Possibly, but it doesn't really make a difference here. I'd rather remove the `virtual` altogether, to be fair. Who would derive from `sf::Packet` and why...?

**Comment by kimci86** [comment]
> Who would derive from sf::Packet and why...?

There is an example `ZipPacket` in the tutorial: https://www.sfml-dev.org/tutorials/2.5/network-packet.php#custom-packets

**Comment by vittorioromeo** [comment]
> > Who would derive from sf::Packet and why...?
> 
> There is an example `ZipPacket` in the tutorial: https://www.sfml-dev.org/tutorials/2.5/network-packet.php#custom-packets

Hm, interesting. I'd argue that it would make more sense to compress/decompress an entire packet, though... not convinced that's a good use case.

**Pull request merged**
