### PR TITLE
Assorted unit testing improvements

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

This PR contains a few minor improvements to the tests that I had been wanting to make but didn't belong in any other PR so I combined them into one.

## Tasks

* [x] Tested on Linux
* [x] Tested on Windows
* [x] Tested on macOS
* [x] Tested on iOS
* [x] Tested on Android

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by vittorioromeo** [comment]
What are the consequences for `DOCTEST_CONFIG_REQUIRE_STRINGIFICATION_FOR_ALL_USED_TYPES`? What's the benefit of enabling this?

**Comment by ChrisThrasher** [comment]
> What are the consequences for DOCTEST_CONFIG_REQUIRE_STRINGIFICATION_FOR_ALL_USED_TYPES? What's the benefit of enabling this?

The extended commit message has more information.

> This ensures that if a printing function is not provided, compilation
fails. This prevents problems where a header is accidentally removed
that was previously providing an operator<< overload or prevents
new tests from being added without print support for all directly
tested types.

**Review by Bromeon — COMMENTED** [review]
Enforcing concious `<<` overloads is a good idea!

The new #include style makes me wonder, would it make sense to add the directory above to the include path or add one level of nesting, in order to enable this?
```cpp
#include <Tests/GraphicUtils>
```
(This is very deep into cosmetics territory; I would also be OK with the current way 🙂)

**Comment by ChrisThrasher** [comment]
> The new #include style makes me wonder, would it make sense to add the directory above to the include path or add one level of nesting, in order to enable this?

I don't suppose I feel strongly either way. I could be convinced one way or another.

**Review by vittorioromeo — APPROVED** [review]

**Pull request merged**
