### PR TITLE
No need to check *_FOUND because REQUIRED already specified

### PR DESCRIPTION
**Pull request by ruslo**
When REQUIRED used in find_package there is no need to check *_FOUND
variable since processing already will stop with error.

From documentation (https://cmake.org/cmake/help/v2.8.3/cmake.html#command:find_package):

  The REQUIRED option stops processing with an error message if the package cannot be found.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Is it something that you've tested? I know that some packages won't raise a fatal error if not found, especially those -- like X11 or XCB -- that also search many extra libraries..

And the extra copyright notice seems a little bit too much.

**Comment by ruslo** [comment]
> Is it something that you've tested?

Yes. Ubuntu 14.04 and CMake 2.8.3.

> like X11 or XCB -- that also search many extra libraries

"X11 not found" was the error I've experienced. Generation stops immediatelly.

> And the extra copyright notice seems a little bit too much.

I did surf the code, test it and hack it. So what is the problem exactly?

**Comment by LaurentGomila** [comment]
> I did surf the code, test it and hack it. So what is the problem exactly?

It is your right to enforce a copyright on your work, but although there's no explicit rule regarding this part of contributions (there should definitely be one), I don't think we'll accept that. There are many many contributors on SFML source code, often with small patches, and we don't really want to deal with the mess of maintaining copyright information, and most of all contacting all the involved authors, whenever something changes in source code.

I don't know what the rest of the team thinkgs about it though, so just take it as my personal point of view for now :smiley:

**Comment by eXpl0it3r** [comment]
So you remove nine, add two lines and the whole file should fall under your copyright?

**Comment by ruslo** [comment]
> the whole file should fall under your copyright?

No. I just add my name (feel free to add yours). That's what I usually do and it's the only things left after I spend some of my time for doing investigate and improves.

Feel free to close if you don't see it's appropriate. I see no problems here.

**Comment by LaurentGomila** [comment]
The problem is not you leaving your name. We *do* want authors to be rewarded for their work; they appear in the commit history and we could even edit a public list of contributors upon each release.

The point is, it's not just about your name. If you're part of the copyright, it means that we can't modify this whole file (because nobody will remember which exact lines you edited) without your permission. This is pretty much unmaintainable.

Not so long ago, we've asked the libsndfile author if he could change its license (or at least make an exception) to allow static linking on iOS. The answer was *"I don't care, but there are too many copyright holders and I can't track them all to get their approval"*. The consequence is that we've got rid of that library and rewrote all its features ourselves. We certainly don't want to fall into such a scenario, especially for such a tiny modification. If you had written a brand new part of SFML we could leave your name in the copyright, but not here.

**Comment by zsbzsb** [comment]
>We certainly don't want to fall into such a scenario, especially for such a tiny modification. If you had written a brand new part of SFML we could leave your name in the copyright, but not here.

This is certainly how I feel about this scenario. For such a small change there is absolutely no reason to write a copyright notice, especially when you only added a small piece of functionality (arguably a bugfix) to existing code. This is why the git history is so important, as it tracks exactly who made what changes to a file.

@SFML/sfml maybe this should be clarified in the contributing docs that small changes will require surrender of copyright to SFML? And that only new large features/rewrites will not require a surrender (at the desecration of the SFML team).

**Comment by ruslo** [comment]
one... two... three... deep breath...


> So you remove nine, add two lines

> If you had written a brand new part of SFML we could leave your name in the copyright, but not here

> For such a small change there is absolutely no reason to write a copyright notice, especially when you only added a small piece of functionality (arguably a bugfix)

Again I don't see what is the difference between writing small module about 100 lines or removing 2 lines of code - it's work, I spent my fucking time to solve problems in your code. If you have any kind of respect to developers please never mention such stupid arguments.

> If you're part of the copyright, it means that we can't modify this whole file

I'm not a lawyer but as far as I know this copyright note (or absent of that!) literally means nothing until somebody sign some papers digitally or physically. Anyway that is something that you should care about, not me. I don't give a fuck, really.

One more time `I just add my name (feel free to add yours). That's what I usually do`, I did it for:
* [Qt](https://github.com/qtproject/qtmultimedia/blob/579a7d620284c277966e590518374aefa141c481/src/plugins/android/src/mediacapture/qandroidviewfindersettingscontrol.h#L4)
* [Boost](https://github.com/boostorg/thread/blob/382ac5a4269045fc5431c2f445c430f10f5b0420/include/boost/thread/with_lock_guard.hpp#L1)
* [spdlog](https://github.com/gabime/spdlog/blob/cef7eb0667d998ace38e5f5122805107f22b5042/CMakeLists.txt#L2)
* or even [CMake itself](https://github.com/Kitware/CMake/blob/7d2a0aa76c25d92f1e2a03778f5666bdd7e56b92/Source/cmFileLock.h#L3)

I think that this talking can be continued for:
* we can discuss technical details of pull request
* I can update copyright notice in any form you think it will be better

Any other discussion make no sense to me. You have enough courage to start this crap, please have enough courage to close this pull request yourself.

Cheers, Ruslo

**Comment by LaurentGomila** [comment]
*You* added it so *you* must explain your reasons. If "it doesn't involve anything" and "you're not the one who should care about it", then don't see any reason to add this notice in first place. If you add your copyright you must have valid reasons, and I can only see two: are you trying to protect something, or is it just to have your name in SFML?

If you're trying to protect something, then it's not clear what, and as I said, it is not something we want to deal with in the long term. In any case you should explain your intention.

If it's just to show your name, then there are other ways to do so that we prefer, and that are less ambiguous.

**Comment by ruslo** [comment]
Dear @LaurentGomila, I already explain everything. I have repeated it twice and will repeat it third time: if you don't like this pull request (for any reason) then please close it, stop wasting my time. Thank you.

**Comment by LaurentGomila** [comment]
No, you never explained the reason behind this copyright. Which is quite important in my opinion.

So now it's up to you: either you can't leave without your name in SFML sources and close this PR, or you just want to contribute to the project because you've found something useful and remove this copyright notice.

**Comment by ruslo** [comment]
> No, you never explained the reason behind this copyright. Which is quite important in my opinion.

Just like I said - that what I usually do, no more, no less. If you're finding it offensive or suspicious it is really your problem. If you want to protect yourself from something you should do it in another way.

**Comment by mantognini** [comment]
> I'm not a lawyer but as far as I know this copyright note (or absent of that!) literally means nothing until somebody sign some papers digitally or physically.

This is where you are wrong, @ruslo. Especially, adding "All rights reserved." ***IS*** a constraint on the code. I talked to a lawyer specialised in IP a while back and it was very clear for him that this kind of © gives you every right on the material.

And again, as @LaurentGomila and @zsbzsb said, @SFML/sfml cannot afford this kind of maintenance burden for obvious reasons that were, again, illustrated above.

@zsbzsb: we could indeed update the contribution guideline to include that, although it should be quite obvious from the current state of the source code. Beside, people don't read this document anyway (or we would be discussing those issues/PRs on the forum)...

**Comment by TankOs** [comment]
@ruslo 
At first: Thank you for your contribution.

Your claim of copyright and all rights on the file is illegal, because others are holding a valid copyright already, and you can't just *void* that without explicit permission from the respective copyright holders.

So in order to submit your pull request, that text has to be removed. You automatically hold copyright on your changes, and you'll be listed in the contributors list by GitHub automatically, which hopefully gives you enough credit. (We don't maintain a contributors file ourselves.)

@zsbzsb @mantognini 
The contribution guidelines (or rather: contributor *agreement*) should indeed cover that, because copyright still remains with the original authors. One could argue that the active zlib license, which only lists Laurent Gomila as copyright holder, takes care of that. But I doubt that's the case. In order to transfer copyright, contributors must explicitly agree to that (at least in most European countries; this library holds most copyright in France I guess).

So, even when @LaurentGomila said that we are not going to make the same mistake libsndfile did, we already have.. ;-) In case we plan to change from zlib to something else, the only option we have is sub-licensing, but not replacing the license. Replacing requires to contact every single contributor.

Good thing is: A license change is not really required, is it? :-)

**Pull request closed without merging**
