### PR TITLE
Fix macOS resize bug

### PR DESCRIPTION
**Pull request by dogunbound**
https://github.com/SFML/SFML/pull/2611

kimci86 stated that this may have better behavior than the previous pull request. I'm going to leave this up and see how we feel about it.

### CODE REVIEW

**Comment by shane-tran-whitmire** [comment]
@kimci86 This is what you recommend, right?

**Comment by kimci86** [comment]
> @kimci86 This is what you recommend, right?

Yes this works best for me.

**Review by kimci86 — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
@kimci86 was telling me that instead of simply cherry picking #2631 we need to use this PR since some other changes in `sf::WindowBase` require that this PR be a bit different?

**Review by ChrisThrasher — APPROVED** [review]
I can confirm this PR makes resizing seem to work just fine on macOS

**Pull request merged**
