### PR TITLE
Added 'SFML Community' to the author list.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
**SFML Tasks**

* [x] Provide feedback
* [x] Change to "And many other members of the SFML community"

----

See discussion on [the forum](https://en.sfml-dev.org/forums/index.php?topic=22755.0).

Also I'm not sure if it really just should be `SFML Community` or if it also should have "The" or "The entire" or some other prefix.

### CODE REVIEW

**Comment by mantognini** [comment]
I'd say `The SFML Community` but I'm not an expert with determiners...

**Comment by eXpl0it3r** [comment]
Can we get some more opinions on this?

**Comment by LaurentGomila** [comment]
I really don't care about this stuff, so... 😸

**Comment by rubenwardy** [comment]
Should probably be "the sfml community" or "and the sfml community". Just sfml community makes it sound like an actual entity, like a fan website called that

**Comment by MarioLiebisch** [comment]
How about "and many other members of the SFML Community"? Otherwise sounds like those named are excluded or some kind "above" them or whatever.

**Pull request merged**
