### PR TITLE
Modernize management of Udev pointers

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

Follows the same pattern as #2540, #2759, and #2801. Using `unique_ptr` makes for safer and more expressive code that can more easily be modified without introducing subtle resource management bugs.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Just reminded me - not blocking for this PR - wasn't there a discussion once to replace udev with something not as ancient?

**Comment by ChrisThrasher** [comment]
> Just reminded me - not blocking for this PR - wasn't there a discussion once to replace udev with something not as ancient?

Not that I recall. Perhaps you're thinking of talks about using alternative Windows APIs for joysticks?

**Comment by eXpl0it3r** [comment]
Ah yeah, I think it might have been in connection with that.

**Comment by binary1248** [comment]
There is no need for such heavy templating:
```cpp
struct UdevDeleter
{
    void operator()(udev_device* device) const
    {
        udev_device_unref(device);
    }
    void operator()(udev_monitor* monitor) const
    {
        udev_monitor_unref(monitor);
    }
    void operator()(udev_enumerate* enumerate) const
    {
        udev_enumerate_unref(enumerate);
    }
    void operator()(udev* context) const
    {
        udev_unref(context);
    }
};

template <typename T>
using UdevPtr = std::unique_ptr<T, UdevDeleter>;
```

**Review by binary1248 — APPROVED** [review]

**Pull request merged**
