### PR TITLE
Fixed issues reported by Coverity Scan static analysis

### PR DESCRIPTION
**Pull request by binary1248**
The issues that fall under the category "Insecure data handling" are all the result of the way `sf::Packet`s function. Due to their nature (as for anything that relies on incoming network data), there is no way to make them "secure".

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Nicely done! :+1:

**Comment by LaurentGomila** [comment]
What's wrong with the `std::ios` stuff?

**Comment by binary1248** [comment]
You don't restore stream precision after the first time you set it, meaning when you start playing the second sound, it only displays the duration using 2 instead of the full number of decimal places.

**Comment by LaurentGomila** [comment]
Then I'd rather add a call to `std::setprecision` where we need to restore the default precision, or remove all the iomanip calls. I like when examples focus on what they want to demonstrate, with as little clutter as possible around it.

**Comment by binary1248** [comment]
Done.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
