### PR TITLE
Added support for VS 2015.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
After a lot of fiddling, I think/hope that all the issues are gone now.

### CODE REVIEW

**Comment by Bromeon** [comment]
Great, I can confirm that it works! :grinning: 

Why is the directory called `libs-msvc-universal`? Isn't that misleading if it only works for versions >= 14 (VS 2015)? Or if it is actually universal, why keep the old directory?

**Comment by eXpl0it3r** [comment]
Because the new CRT is called [Universal CRT](http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx) and they are not compatible with the old Visual Studio CRT.

**Comment by Bromeon** [comment]
Ah, that makes it clear, thanks!

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
