### PR TITLE
Updated ImageLoader::saveImageToFile to support .jpeg

### PR DESCRIPTION
**Pull request by kikiotsuka**
Extract the extension after finding the dot, then compare it to the list of valid extensions

https://github.com/SFML/SFML/issues/929#issuecomment-123998596

### CODE REVIEW

**Comment by Foaly** [comment]
Looks good. One thing I would change: you should use [`std::string::find_last_of()`](http://www.cplusplus.com/reference/string/string/find_last_of/) or [`std::string::rfind()`](http://www.cplusplus.com/reference/string/string/rfind/) instead of a raw for loop. Also assigning an empty string to `extension` right after instantiation (in line 229) is pointless. `std::string extension;` will do just fine.

**Comment by LaurentGomila** [comment]
Duplicate of #931... guys no need to rush and make the work twice :stuck_out_tongue:

#931 is better (see comments above) so I think we should close this one.

**Comment by TankOs** [comment]
Duplicate? It more looks like the patch that originated from here. And it's PR vs. issue. IIRC we kept both open?

**Comment by LaurentGomila** [comment]
The issue is #929. From this issue, two PRs were created in parallel by two different persons, #930 (this one) and #931.

**Comment by TankOs** [comment]
Oh Jesus, GitHub will always manage to confuse me. Sorry! :-)

**Pull request closed without merging**
