### PR TITLE
Clean up implementation of `sf::Shader`

### PR DESCRIPTION
**Pull request by ChrisThrasher**
## Description

I found these while working on `sf::Shader::loadFromFile` tests a little while back.

### CODE REVIEW

**Review by kimci86 — COMMENTED** [review]
This is assuming a file cannot be empty but it is not true. Being empty is not the same as being missing.

**Comment by ChrisThrasher** [comment]
> This is assuming a file cannot but empty but it is not true. Being empty is not the same as being missing.

Both function push back a null character before returning the buffer so even if the file is empty these should still work.

**Comment by kimci86** [comment]
> Both function push back a null character before returning the buffer so even if the file is empty these should still work.

Ok that makes sense. However that is not the case in `getStreamContents` when the stream size is 0.

**Comment by ChrisThrasher** [comment]
SFMLBuildMaster: Build this please.

**Review by eXpl0it3r — APPROVED** [review]

**Pull request merged**
