### PR TITLE
Use PImpl idiom for 'AudioDevice'

### PR DESCRIPTION
**Pull request by vittorioromeo**
Pretty self-explanatory, reduce some transitive includes and hide implementation details.

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
These are all implementation details so nothing is hidden from users. I don't think adding this extra complexity is worth it.

**Comment by vittorioromeo** [comment]
> These are all implementation details so nothing new is hidden from users.

Internal components that use `AudioDevice` are *users* of `AudioDevice`. Neither `AudioResource` nor `Listener` use `miniaudio.h` or `<optional>` yet they're getting included transitively from `AudioDevice.hpp`. This PR removes those unnecessary transitive dependencies.

> I don't think adding this extra complexity is worth it.

I'd argue that it is worth it. The added complexity is minimal, this is an idiom we have used many times in the library and we're familiar with it. Using PImpl wherever possible and sensible (i.e. we can afford the allocation) moves us closer to ideal header and dependency hygiene.

**Comment by ChrisThrasher** [comment]
Sorry but I'm a firm "no" on this. Header hygiene for the sake of header hygiene isn't enough justification for me to tolerate this increase in complexity.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2749#issuecomment-2041186467

We already discussed this in the original Miniaudio PR. Here is some hard evidence showing that PIMPL in this exact case was not helpful.

**Comment by vittorioromeo** [comment]
We clearly disagree on the added complexity/benefit ratio. I still genuinely think it's worth it *even* if the compilation time stays unchanged, but it's definitely not worth arguing over this. I'll apply these improvements and others to my own fork.

**Pull request closed without merging**
