### PR TITLE
Fix keypad keys not being detected on Linux

### PR DESCRIPTION
**Pull request by mickelson**
This pull request fixes keypad keys not being detected on Linux.

Tested on Debian 8.0.

### CODE REVIEW

**Comment by binary1248** [comment]
Thanks for the fix. Your patch however, is based on an outdated revision. The current codebase looks quite different (albeit still containing the bug), so it would be nice if you could modify your commit to apply to the current master instead.

Also, you shouldn't bother keeping the old lines. SFML should only look up a single keysym that maps to an `sf::Keyboard::Key` value. If multiple keysyms that map to the same `sf::Keyboard::Key` value are looked up then it is another bug that has to be fixed.

**Comment by mickelson** [comment]
My apologies, I appear to have completely failed at updating this to master

**Comment by mickelson** [comment]
Ok, I believe I've got it sorted out now: I've updated to master and removed the old lines as requested.

**Comment by mantognini** [comment]
I confirm this works on Ubuntu 15.04 with ch-fr keyboard. Ready to be merged for me. :+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon into the 2.3.x branch, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in da8a325fa3b7d35ca4b6906bb9e313497a0974aa on branch 2.3.x

**Comment by Hapaxia** [comment]
It looks like the merged patch does not match the one by mickelson.
For some reason, the keys that are 'patched' in InputImpl in the merged version are not the number pad keys.

**Comment by eXpl0it3r** [comment]
Not sure what you're looking at but [this](https://github.com/SFML/SFML/pull/910/files) and [this](https://github.com/SFML/SFML/commit/da8a325fa3b7d35ca4b6906bb9e313497a0974aa) are the same expect for spacing. The commit ID won't be the same since I had to rebase the patch onto the 2.3.x branch.

So the question is, how do you come to your conclusion?

**Comment by Hapaxia** [comment]
They aren't the same.
First one:
keycodeMap[sf::Keyboard::Numpad0]   = getKeycode(XK_KP_0);
Second one:
keycodeMap[sf::Keyboard::Num0]      = getKeycode(XK_0);

**Comment by eXpl0it3r** [comment]
Oh, now I see it. This must have been a mistake on my side, I'll make sure to fix it asap. Sorry for the inconvenience.

**Comment by silverweed** [comment]
Sorry for asking, but is this fix working in the downloadable 2.3.1 version or should I get the repository version to make it work?

**Comment by mantognini** [comment]
It will be available in the 2.3.**2** version (see [here](https://github.com/SFML/SFML/blob/master/changelog.txt#L22)), which you can already get by compiling SFML yourself. :wink:

**Comment by eXpl0it3r** [comment]
And if you use Linux, you should anyways build from source, to remove any chances of mismatching dependencies versions.

**Comment by silverweed** [comment]
Thank you very much, will do. :)

**Pull request closed without merging**
