### PR TITLE
Bump the required CMake version to 3.1.0 and enforce compiler C++14 support.

### PR DESCRIPTION
**Pull request by binary1248**
Yes...

### CODE REVIEW

**Comment by JonnyPtn** [comment]
Cool, this will actually make #1206 redundant too

**Comment by MarioLiebisch** [comment]
#1206 should be fixed for master though.

**Comment by binary1248** [comment]
> Cool, this will actually make #1206 redundant too

Not really... This is pending to be merged into unstable i.e. 3.x. It will be a while until it will be officially released.

**Comment by JonnyPtn** [comment]
I Know it's pointless to ask for a timescale, but I can't find any details about what the various branches are intended for (currently master is up to date with unstable, so I don't think it's unreasonable to guess that they're close). Perhaps worth adding somewhere?

**Pull request merged**
