### PR TITLE
Android: Accept touch events from "multiple" devices

### PR DESCRIPTION
**Pull request by MarioLiebisch**
Fix for issue #953, although I can't really say whether this is indeed some driver thing. All snippets I've found use exact comparison only (usually switches).

Considering this fix is pretty minor, only affects Android, and won't have any effects on other devices, I think we should even try to include it in 2.3.2/#952, what do you think?

### CODE REVIEW

**Comment by binary1248** [comment]
The Android people don't get anything pre-built. Including any Android specific fixes into any milestone makes no sense because they always build from master anyway. If they don't want to do so although we clearly label the mobile ports as still being experimental then they probably misunderstood the term "experimental".

**Comment by MarioLiebisch** [comment]
Right, forgot about that. :D

**Comment by eXpl0it3r** [comment]
Looks like either GitHub or Jenkins messed up, but it doesn't matter anyways. :smile: 

This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Merged in 4f3c26660ee852b6a85f1ea257a567c15e1a9f4a

**Pull request closed without merging**
