### PR TITLE
Correct docstring in SoundFileReader::seek

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Per request https://github.com/SFML/SFML/pull/1259#discussion_r163906568

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Look at the commit (c78c8106dad49dd458aa3624df06d2a989f3d0ed) when that was added, seems like there's another place that needs to be changed.

Since it's your original commit, do you agree with this change, @Foaly?

**Comment by SergioRAgostinho** [comment]
I'll grep and replace all occurrences upon confirmation.

**Comment by LaurentGomila** [comment]
Tiny improvement: I would make it more explicit, with something like "If you have a time offset instead, you can easily find the corresponding sample offset with the following formula:".

**Comment by Foaly** [comment]
Oh yes absolutly! I appologize for spreading wrong information 😄 But looking at the commit you linked there is actually 5 places where it has to be changed.

**Comment by eXpl0it3r** [comment]
Merged in 6d4e870e320be743cb7699de7e964bb308dea05a

**Pull request closed without merging**
