### PR TITLE
Added subset of modernize-* to .clang-tidy

### PR DESCRIPTION
**Pull request by gnawme**
Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [x] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [x] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

Supersedes #2334; adds

-   modernize-use-equals-default,
-   modernize-use-equals-delete,
-   modernize-use-nullptr,
-   modernize-use-override,
-   modernize-use-using,

to `.clang-tidy`

This PR is related to the issue #2321 

## Tasks

* [x] Tested on Linux
* [ ] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

Describe how to best test these changes. Please provide a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) if possible, you can use the follow template as a start:

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::Vector2u modeSize{200, 200};
    sf::RenderWindow window(sf::VideoMode(modeSize), "SFML works!");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}

g++ main.cpp -o sfml-app -I ./include/ -L./build/lib -lsfml-audio -lsfml-graphics -lsfml-system -lsfml-window

./sfml-app
```

### CODE REVIEW

**Comment by ChrisThrasher** [comment]
As I watch this PR grow, I worry that adding 5 new checks all at once will make it hard to know why specific changes were made and will make the code review pretty difficult.

**Comment by gnawme** [comment]
> As I watch this PR grow, I worry that adding 5 new checks all at once will make it hard to know why specific changes were made and will make the code review pretty difficult.

17 files, ~200 lines, which is right at the limit for a comfortable size for a PR. What do you suggest? Break up the checks? Maybe the `-default` and `-delete` together, and the `-nullptr` and `-override` checks in a separate PR?

**Comment by ChrisThrasher** [comment]
It's not about file or line count, it's about this PR having multiple distinct motivations. The PR that added clang-format changed 420 files and 10k lines of code but it had a single focus so reviewing it was manageable.

Once you get your first PR merged you no longer need maintainer approval to run the CI pipeline which will speed things up. How about your first PR only adds a single clang-tidy check and once that's in the books, later PRs can combine multiple related checks. Does that sound okay?

**Comment by gnawme** [comment]
> It's not about file or line count, it's about this PR having multiple distinct motivations. The PR that added clang-format changed 420 files and 10k lines of code but it had a single focus so reviewing it was manageable.
> 
> Once you get your first PR merged you no longer need maintainer approval to run the CI pipeline which will speed things up. How about your first PR only adds a single clang-tidy check and once that's in the books, later PRs can combine multiple related checks. Does that sound okay?
> 
> Having one commit per check you add is also acceptable. If you add a single check, fix everything, ensure CI passes, then lump that all into a single commit, you can put a few of those commits in a single PR. It lets reviews review the PR on a per-commit basis which helps when understanding a huge set of changes. That requires an extra level of git obsession that may be less attractive than making multiple PRs but that's up to you.

Works for me, thanks. You're talking about squashing commits once everything runs? Sure, can do.

**Comment by ChrisThrasher** [comment]
> You're talking about squashing commits once everything runs?

Squashing all commits related to the addition of a single clang-tidy check, to be precise.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/compare/master...ChrisThrasher:SFML:clang-tidy

Here's an example of what I mean. I've found some modernize- checks that are easy to add. Some of them require zero changes to add. Because the addition of each check happens in a single commit, it's really easy to read the commit history and see what's changed and why it changed.

**Comment by ChrisThrasher** [comment]
Superseded by #2343

**Pull request closed without merging**
