### PR TITLE
Fix audio stream replay for server example

### PR DESCRIPTION
**Pull request by davi-v**
Fix replay feature of this example. Tested on Windows.

### CODE REVIEW

**Comment by MrZeusTheCoder** [comment]
@davi-v is this connected to a known issue? I am working on example improvements and I might add this too the list. I don't have a Windows machine to test this on.

**Comment by davi-v** [comment]
> @davi-v is this connected to a known issue? I am working on example improvements and I might add this too the list. I don't have a Windows machine to test this on.
I don't think this is an issue. Maybe when this example was created, SFML internally already set the playing offset to the beginning when the sound ended, but now you need to do it manually?

**Comment by MrZeusTheCoder** [comment]
But if it isn't an issue why are you fixing it, :P. It is not working for you?

**Comment by MrZeusTheCoder** [comment]
Bump @davi-v .

**Comment by davi-v** [comment]
> But if it isn't an issue why are you fixing it, :P. It is not working for you?

The example claims to be able to hear the recording after it finishes (replay feature), but it didn't work for me, *unless* I set the playing offset to the beginning before replaying the sound. I said I don't think it's an issue in SFML's implementation, but I think it's an issue in this example code.

**Comment by LaurentGomila** [comment]
> I said I don't think it's an issue in SFML's implementation, but I think it's an issue in this example code.

That's a possibility. However this should be investigated further, since this example has existed for years and you're the first one to report such a bug.

And note that `sf::Time::Zero` is slightly more expressive than `sf::Time()` 😉

**Comment by eXpl0it3r** [comment]
This has been fixed with #2037

Can you give SFML master another try @davi-v?

**Comment by davi-v** [comment]
It's working as documented now 👍

**Pull request closed without merging**
