### PR TITLE
Add 'NetworkUtil' for network module tests

### PR DESCRIPTION
**Pull request by vittorioromeo**
Depends on #1921, I plan to add more tests here when we add stuff like move semantics so I wanted to make this module consistent with the rest.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Pushed the wrong revision?

**Comment by vittorioromeo** [comment]
> Pushed the wrong revision?

Yup, should be fixed now..

**Comment by eXpl0it3r** [comment]
@vittorioromeo Is this still relevant?

**Comment by eXpl0it3r** [comment]
I believe the testing setup has undergone a larger iteration, that it's easier to just recreate this PR, once it's actually needed. As such I'll close this one.

**Comment by ChrisThrasher** [comment]
I'm closing this issue. We can always add this later should the need arrive.

**Pull request closed without merging**
