### PR TITLE
Implemented sf::Image::saveToVectorPng (jpg, bmp, tga also) + Update stbi_image_write.h

### PR DESCRIPTION
**Pull request by Starl1ght**
Issue -> https://github.com/SFML/SFML/issues/988
Forum -> http://en.sfml-dev.org/forums/index.php?topic=2164.msg14166#msg14166

This feature is now possible to be implemented due to update of stbi_image_write.h (which is also in my commit).

The idea - 4 new similar functions, I'll take one as example -> sf::Image::saveToVectorPng.
I've decided to implement this as vector, due to raw memory is prone to leak, be lost and so on, and adding small overhead as vector we are, basically, have raw memory, which is controlled and with embedded size().

Minor code example:

```
Image.saveToVectorPng(vec); // vec is std::vector<unsigned char>
memcpy(DEST, vec.front(), vec.size()); // same behavior as for raw memory
```

Test code is available here -> http://pastebin.com/SiGX08x7

---

Let me know what to fix, edit and so on, I'm really excited to contribute something :+1:

### CODE REVIEW

**Comment by Bromeon** [comment]
When you write a PR before a discussion has even started, you risk having to rewrite major parts or even getting rejected completely... That's why we highlight the importance of forum discussions in our [contribution guidelines](http://www.sfml-dev.org/contribute.php). Ideally current ones, not from half a decade ago... :wink:

Personally I don't agree with the API for various reasons:
* It is not symmetric with the `loadFromMemory()` counterparts -- `saveToFile()` is.
* `std::vector<unsigned char*>` is not flexible enough. It forces the user to hold `std::vector` instances, while he may as well allocate his array differently.
* Writing a different function for every format is not ideal. It requires more case differentiations on user side. A change in the list of supported formats leads to a modification of the API. In case SFML supports more formats in the future, another function has to be written for every single format.

Futhermore, please read the [code conventions](http://www.sfml-dev.org/style.php) or have a look at existing SFML code, you differ in many places.

Don't change those things now, you'll only have to rewrite everything again... Wait for further feedback from other team members and users.

**Comment by Starl1ght** [comment]
>You don't follow our code conventions in various places
I've tried to comply, but I guess, missed some parts. Ok.

> Use of malloc() and free() where std::vector would do the job
Got it.

>How do you know the output size in advance? There are some magic constants, are you sure this is correct? What if the allocated buffer is bigger than necessary?
Googled a bit for maximum values for different formats. The idea that we can sacrifice some memory, because, probably, we are not going to store it for a long anyway, but strictly say no to any re-allocations of vector. If buffer is bigger - once vector destoryed - it frees.

But, I still think, vector is better, that raw memory, because it's simpler. If we use raw memory there are - either we allocate memory inside - this is exactly same as vector, but vector is far better (RAII).
Or someone allocate memory - this is problem, if not enough memory is allocated and so on.

So, no problem, I am waiting feedback, and I'll rewrite code.

**Comment by Bromeon** [comment]
> But, I still think, vector is better, that raw memory, because it's simpler. If we use raw memory there are - either we allocate memory inside - this is exactly same as vector, but vector is far better (RAII).
 Or someone allocate memory - this is problem, if not enough memory is allocated and so on.

I agree that `std::vector` is safer and more convenient, but it may be too high-level in some cases. What if the user wants to store the data in a different data structure? He would then have to copy the whole image again. The counterpart `loadFromMemory()` also works on pointers and not STL containers, for this very reason.

> Googled a bit for maximum values for different formats. The idea that we can sacrifice some memory, because, probably, we are not going to store it for a long anyway, but strictly say no to any re-allocations of vector. 

Yes, we need to be conservative with the memory allocation and allocate the maximum amount, to be sure that stb doesn't write past the buffer. 

I delved deeper into stb_image's write API, which looks as follows (see [here](https://github.com/nothings/stb/blob/master/stb_image_write.h)):
```cpp
int stbi_write_bmp_to_func(stbi_write_func *func, void *context,
    int w, int h, int comp, const void *data);
// func = user-defined callback
// context = user data (untouched by stb_image)
// w, h = image size
// comp = channel count (1, 2, 3 or 4)
// data = pointer to raw image data

void stbi_write_func(void *context, void *data, int size);
// context = user data (untouched by stb_image)
// data = pointer to memory where image was temporarily allocated
// size = size of the image
```

This callback API allows for efficient writing to *any* kind of storage (stb_image allocates already one memory buffer, so one copy *is* required, but there seems to be no way around that). The advantage of the callback API is that the user knows the number of bytes directly, **so there's no need for the dangerous guess how big the image might be.**

I know this such callbacks are not typical for an SFML API, but any other option needs an additional copy. For example, a potential
```cpp
bool Image::saveToMemory(const std::string& format, std::vector<Uint8*>& out) const;
```
is terribly inefficient:

1. stb_image allocates its internal memory buffer
2. this buffer is passed to the `stbi_write_func` callback, which copies it into the `std::vector`
3. a user possibly needs a different format, so he has to copy from `std::vector` into his own buffer *again*

On the other hand, an API like:
```cpp
bool Image::saveToMemory(const std::string& format, Callback callback) const;
// with:
typedef void (*Callback)(const Uint8* image, std::size_t size)
// or in the future:
typedef std::function<void(const Uint8*, std::size_t)> Callback;
```
allows to write the image directly to the desired destination, with only one copy from stb_image's internal buffer to wherever the user wants.

**Comment by LaurentGomila** [comment]
> abstract base class with virtual write() function -- the Java way

And why not a ```saveToStream(sf::OutputStream&)``` function? That would make everyone happy, and we can even provide a sf::MemoryOutputStream for those who don't care the cost of an extra buffer.

**Comment by Bromeon** [comment]
Great idea, that's even more generic. How would such a  `sf::OutputStream` class look?
```cpp
class OutputStream
{
    virtual ~OutputStream();
    virtual void write(const void* data, Int64 size) = 0;
};
```

It would also get the whole content at once rather than in multiple blocks of memory, so the term "stream" is not 100% accurate anymore.

If others agree, I could start to come up with such an implementation, and then @Starl1ght can base his image-saving work on it.

**Comment by LaurentGomila** [comment]
> How would such a sf::OutputStream class look?

Hmm yes, it would probably only contain a ```write``` function.

> // return if successful (or should it be bytes written and -1 on error?)

We should be consistent with ```sf::InputStream```.

> It would also get the whole content at once rather than in multiple blocks of memory, so the term "stream" is not 100% accurate anymore.

In this particular case, yes (and it's just an implementation detail, nobody's supposed to know it). And don't forget that if we have a ```sf::OutputStream``` class, we can start using it in many other places where "stream" makes more sense.

**Comment by Bromeon** [comment]
> > // return if successful (or should it be bytes written and -1 on error?)
>
> We should be consistent with ```sf::InputStream```.

What would the caller of `write()` (within SFML) do if not all bytes have been written? Call the function again with the rest of the buffer? Or is it an error?

In other words, what useful information does the return value convey?

Btw, for inline code, a single ` is enough :)

**Comment by LaurentGomila** [comment]
> Call the function again with the rest of the buffer?

That. For example, we can imagine a buffered stream that rejects data if there's no more room in its internal buffer (concrete example: a stream that wraps a TCP socket).

> Btw, for inline code, a single ` is enough :)

`You just changed my life` :)

**Comment by Bromeon** [comment]
But that means that every place that calls `OutputStream::write()` must be prepared to handle that (or we write some kind of abstraction). And does it make sense to just call the function immediately again, i.e. in a loop? If an output stream fails to process all bytes at once, why would it be able to do so one microsecond later? Or how can the call site meaningfully determine how to react in such cases?

I'm just thinking that if this *bytes written* return value exists purely for buffering purposes, it had better be implemented within the concrete `OutputStream` implementation itself, which knows the specific scenario (ideal buffer size, how to handle errors, etc.)

Maybe I'm also just thinking of the wrong use cases :)

**Comment by Bromeon** [comment]
Let's continue the discussion about output streams here:
http://en.sfml-dev.org/forums/index.php?topic=19275

**Comment by Bromeon** [comment]
Should now be integrated as https://github.com/SFML/SFML/pull/1669.
Output streams could still be an interesting feature for SFML 3.

**Pull request closed without merging**
