### PR TITLE
Converted Unix Window implementation from XCB back to Xlib.

### LINKED ISSUE #1089: Gnome flags SFML windows unresponsive.
As discussed on the topic: http://en.sfml-dev.org/forums/index.php?topic=19715
There is a fix #947 that is not working for me. I'm on Arch Linux with Gnome 3.20 and tried the SFML/CSFML from the official repos along with compiling the latest git versions of both of them and the window is still flagged as unresponsive. It doesn't have to be fullscreen as suggested. It always happens.

@binary1248, After a quick chat with a "Clutter" developer on IRC, it's certain that this only happens if the application doesn't respond properly to _NET_WM_PING. I asked specifically if anything else can cause this and the answer was no. I don't know if that helps but that's the only information I got.

### PR DESCRIPTION
**Pull request by binary1248**
After almost 2 years of poking around XCB, it is time to declare defeat and go back to good old stable Xlib.

In retrospect, there weren't really many if any advantages for us in switching from Xlib to XCB in the first place. The main advantage users of XCB are supposed to have comes from its non-blocking nature. This might make sense in certain applications, however the way SFML interacts with the X server completely counteracts this usage pattern. There is simply no performance difference between using Xlib and XCB for SFML. The second advantage users of XCB are supposed to have is "less legacy (buggy) code" in its implementation. Being a thin (autogenerated) wrapper on top of the X wire protocol, I think it is kind of obvious: If there is no implementation to speak of, there also can't be that many bugs.

We take for granted how many other things Xlib actually does for us on the side. Those things were supposed to be supported in XCB at some point as well, but considering that it is an open source project and Wayland is arriving faster than many anticipated, one can understand the lack of motivation to continue development on XCB.

Even when using XCB, SFML still has to make use of Xlib to interact with GLX since that is still the primary API that the graphics drivers expose to this day. Mixing Xlib and XCB is a nightmare as well, which is why I already reverted the event processing back to using Xlib events a while ago.

The Unix sfml-window implementation could be considered relatively stable up to 2.2. Most of the instability came in 2.3 when we switched over to XCB. This PR seeks to restore the stability of 2.2 so that we can focus our efforts on other more pressing issues and remain an attractive library for users on Unix platforms. Once Wayland support becomes ubiquitous, we can consider supporting it in parallel to Xlib.

Fixes #1089 and possibly other bugs (requires re-evaluation if this gets accepted).

### CODE REVIEW

**Comment by achpile** [comment]
Thank you, Binary!!! Your branch helped me again!
(first time was 3 years ago, it was about ALContext)

PS: This fixes  #921 

Ubuntu 14.04 (XFCE4) 64bit

**Comment by mantognini** [comment]
Once this is merged, #827 will need rebasing and the linux implementation can be started.

**Comment by BlaXpirit** [comment]
Works for me. I notice no change.
(Arch Linux, NVIDIA, KDE)

**Comment by eXpl0it3r** [comment]
> I see that in ldd libxcb-* libs are not used anymore, but libxcb still is.

Did you rerun CMake as well?

**Comment by BlaXpirit** [comment]
> Did you rerun CMake as well?

Sure. I think the change in the list of referenced libraries confirms that.

**Comment by MarioLiebisch** [comment]
>> Did you rerun CMake as well?
> Sure. I think the change in the list of referenced libraries confirms that.

That's completely normal, since xcb will be loaded (or even injected?) by some X11 stuff. It's showing up in that list due to the way LDD works.

Running `ldd lib/libsfml-window.so`:

```
    linux-vdso.so.1 =>  (0x00007ffd7e2ec000)
    libsfml-system.so.2.4 => /home/mario/git/SFML/lib/libsfml-system.so.2.4 (0x00007fee94d4f000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fee94a06000)
    libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fee947fa000)
    libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fee947da000)
    libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fee94569000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fee9434b000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fee93fc9000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fee93db3000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fee939e9000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fee937e1000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fee935bf000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fee933ba000)
    libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fee931a8000)
    libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fee92f9e000)
    /lib64/ld-linux-x86-64.so.2 (0x00005591d8db2000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fee92d74000)
    libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fee92b71000)
    libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fee9296e000)
    libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fee92766000)
    libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fee92563000)
    libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fee92335000)
    libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fee92131000)
    libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fee91f2b000)
    libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fee91d29000)
    libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fee91b0f000)
    libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fee9190a000)
    libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fee91704000)
    libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fee914f4000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fee911eb000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fee90fe6000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fee90de0000)
```

But you can also read that information directly from the binary using `readelf -b lib/libsfml-window.so | grep NEEDED`:

    0x0000000000000001 (NEEDED)             Shared library: [libsfml-system.so.2.4]
    0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
    0x0000000000000001 (NEEDED)             Shared library: [libXrandr.so.2]
    0x0000000000000001 (NEEDED)             Shared library: [libudev.so.1]
    0x0000000000000001 (NEEDED)             Shared library: [libGL.so.1]
    0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
    0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
    0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
    0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

As you can see, everything is fine, no direct reference to XCB anymore. :)

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
