### PR TITLE
Remove unnecessary includes from public-facing headers

### PR DESCRIPTION
**Pull request by vittorioromeo**
Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

This PR cleans up some include directives from public headers, sometimes removing them entirely, other times replacing them with a forward declaration. The purpose is to reduce transitive include usage and to improve compilation parallelism.

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

CI.

### CODE REVIEW

**Comment by binary1248** [comment]
I think you might have accidentally reverted the changes from 66339bc09c9470b5a809743459ce5b942288765b in this commit. 😄

**Comment by Bromeon** [comment]
Very nice, thanks for thinking of this!

What's with the codecov removals? A not-yet-rebased issue?

**Review by Bromeon — APPROVED** [review]
Great work!

Out of curiosity, have you used a tool or found those unused symbols manually? 🕵️‍♂️

**Comment by vittorioromeo** [comment]
Manually :)

**Pull request merged**
